### ISSUE TITLE
DateTimePicker: Displays "Invalid entry" after selecting a valid date

### ISSUE THREAD

**Issue by CristianDDias** [SAP/ui5-webcomponents#1760] opened 2020-06-09 14:13 UTC
**Describe the bug**
I'm using a `DateTimePicker` component with `minDate` props. When I open the calendar and select a date, it displays "invalid entry" (red borders on the input element), but the date is valid. When I click on the "OK" button, it still displays "invalid entry", but when I do this again (select a new valid date), it works fine. 

Besides that, when I use `minDate` props, it's not possible to use an empty value on the component (clear the field). In my case, I need a date/time field which is optional, which means, I may or may not enter a date.

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/jolly-bassi-xlpc5?file=/src/App.js)

**To Reproduce**
- Click on the "Open Picker" icon (open the calendar)
- Select September 15
- Notice that it displays "invalid entry" (red borders on the input element)
- Click on "OK" button
- Notice that it still displays "invalid entry" (red borders on the input element)
- Click on the "Open Picker" icon (open the calendar)
- Select September 16 and then select September 15 again
- Notice that it removes the "invalid entry"
- Click on "OK" button
- Notice that it removes the "invalid entry"

**Expected behavior**
Do not display "invalid entry" when selecting a date on the calendar. It should only display "invalid entry" after clicking on the "OK" button or when typing a invalid date.

It should also allow an empty value when using `minDate` props, without displaying "invalid entry".

**Screenshots**
![image](https://user-images.githubusercontent.com/30023600/84158096-d7e61e00-aa41-11ea-9619-7e0bc67a5673.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11
Operating System: Windows
Browser: Chrome

**Comment by ilhan007** [comment] 2020-06-14 04:15
Hello @CristianDDias,

Yes, in RC.7 the issue is present indeed, but in our latest development it has been fixed.

If you change the version of webcomponents to 0.21.2 and the version of webcomponents for react to 0.100.0 (special versions we released lately) you can see it yourself. These versions are newer than RC.7 and you can see that the issue is no longer present.

And later probably this month, RC.8 will be released having this fixed.

BR,
ilhan

**Closed by ilhan007** 2020-06-14 04:15 UTC
