### ISSUE TITLE
Counter/Badge for Tree Items

### ISSUE THREAD

**Issue by MaxRumpf** [SAP/ui5-webcomponents#3130] opened 2021-04-09 10:23 UTC
Hi Guys,

Would it be possible to have a counter or badge for Items in the Tree?
It is not necessary to have a color background (like a typical badge), but that option would be even better of course.
Please see the attached screenshot.
If possible, it would be nice if this feature is also available in the React-Webcomponents, because those are the ones we are using in our project.

<img width="496" alt="Screenshot 2021-04-09 at 12 50 17 (1)" src="https://user-images.githubusercontent.com/4653567/114166833-83941f00-992e-11eb-9828-e75a69930127.png">

**Comment by yanaminkova** [comment] 2021-04-09 10:48
Hello @SAP/ui5-webcomponents-topic-p ,

I am forwarding this feature request to you as it is in relation with the TreeItem component.

Regards,
Yana

**Comment by yanaminkova** [comment] 2021-04-09 11:04
@ilhan007 Could you take a look at this feature request?

**Comment by MaxRumpf** [comment] 2021-04-09 11:52
One Comment:
A similar thing can be achieved by using the "info" parameter of a Tree Item.
But it turns out, the created ui5-li-tree-info has a min-width, which shifts short texts to the left. So for using this as a "Badge" for small numbers (1-2 digits), the min-width needs to be reduced to 0.
Code Sandbox: https://codesandbox.io/s/amazing-pike-lznwv?file=/src/App.js

Still, it would be "nice" to have badge-like coloring and additional styling options.

**Comment by ilhan007** [comment] 2021-04-09 12:01
Hi @yanaminkova I will pre-process the request before forwarding to the team.

**Comment by ilhan007** [comment] 2021-05-19 13:55
Hello @nnaydenow could check if the issue is fixed in the master already. Currently the info-text is shifted to the left, it's not correctly right aligned as expected.


The author created a sample
https://codesandbox.io/s/amazing-pike-lznwv?file=/src/App.js


But, in the sample he added custom CSS so the issue is fixed, you would have to comment that line and see the result on wide screen.

BR,
ilhan

**Closed** 2021-05-20 06:55 UTC
Labels: Medium Prio, TOPIC P
