### ISSUE TITLE
[Menu & MenuItem | 1.14.0]: The Dynamic Menu is not working on the second sub-level

### ISSUE THREAD

**Issue by rv97** [SAP/ui5-webcomponents#7391] opened 2023-07-31 06:49 UTC
### Bug Description

When the main menu has two levels of sub-menu where the second level sub-menu should be rendered dynamically, then the loading indicator is stuck and does not render the content automatically. We need to go one level back and then open the sub-menu to show the rendered content.
The same works in the case of the first-level sub-menu.

### Affected Component

Menu, MenuItem

### Expected Behaviour

How many ever sub-levels are there, the busy indicator should be gone automatically and render the content.

### Isolated Example

https://codesandbox.io/s/prod-bird-mjtv35?file=/src/App.js

### Steps to Reproduce

1. Open the sandbox link shared.
2. Click on "Show Menu"
3. Open the "New File" sub-menu.
4. Again open the "Open" sub-menu
...

You can observe that the sub-menu inside a sub-menu does not render the content automatically.

### Priority

High

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment] 2023-07-31 07:03
Hello @SAP/ui5-webcomponents-topic-b,

This issue is for us.

Best regards,
Boyan

**Comment by unazko** [comment] 2024-02-12 09:43
Hi @rv97,

Apologies for the late reply. We've got stuck with merging the previously related PR.
Currently there is a new related PR, which will most probably fix this issue.
We're currently testing if the issue will be resolved with the PR.

Best regards,
Boyan

**Comment by unazko** [comment] 2024-03-05 08:01
Hello @rv97,

Unfortunately the I've managed to fully test the provided sample and the previously linked PR's aren't going to fix this issue:
I suspect you're already using the following workaround:
https://codesandbox.io/p/sandbox/boring-solomon-92qknd?file=%2Fsrc%2FApp.js

There is a workaround at least. We're going to continue debugging this behavior.

Best regards,
Boyan

**Comment by shubhamnazare** [comment] 2024-04-30 06:25
Hi @unazko,

I'm from @rv97' team working on this issue. The workaround you proposed is not working in our case. We have a complex reusable component which is used to render all the menus across the entire application. Introducing the workaround in our application brings in a lot of code refactoring and unnecessary errors. Hence, we request the UI5 Web Components Team to check if it is possible to fix this issue in the `Menu` component itself.

Thanks & Regards,
Shubham.

**Comment by rv97** [comment] 2024-05-09 04:31
Hi @DMihaylova ,

Thanks for the update.

Regards,
Vignesh R

**Comment by unazko** [comment] 2024-05-22 09:12
Hello @rv97,

The issue is fixed with the following PR (https://github.com/SAP/ui5-webcomponents/pull/8722) for the latest ui5-webcomponents release.

We'll have to develop separate fix for 1.24 release though as the upper change is a major refactoring of the ui5-menu.

Best regards,
Boyan

**Comment by rv97** [comment] 2024-05-24 10:27
Thanks @unazko. Please let us know once you have finalized the version this fix would be available from.

Thanks,
Vignesh R

**Comment by unazko** [comment] 2024-06-04 10:48
Hi Vignesh R,

This behavior will be fixed with webc v2 currently. We'll be working on a transport as a separate fix.
From the following URL you could see the release candidate for v2 marked with @next tag:
https://www.npmjs.com/package/@ui5/webcomponents?activeTab=versions 

You could perform internal testing with the release candidate ([2.0.0-rc.4](https://www.npmjs.com/package/@ui5/webcomponents/v/2.0.0-rc.4)).

There is also information about the incoming releases down on the following page: https://github.com/SAP/ui5-webcomponents/projects?type=classic

We expect to have an official release containing the working behavior at the end of June.
That will be webc v2.

Best regards,
Boyan

**Comment by Abanindra** [comment] 2024-06-11 05:25
Hi @unazko,

Since we are yet to move to v2, we are expecting the fix in one of the V 1.x. Appreciate if you can let us know by when we can expect the fix.

reagrds
Aban

**Comment by unazko** [comment] 2024-07-09 13:16
Hi @Abanindra,

I've referenced a PR, which will fix this issue for `webc `.24` once merged.
Currently the PR is in the review phase.

Best regards,
Boyan

**Comment by unazko** [comment] 2024-07-29 10:59
Hi @Abanindra,

The fix is done and it is transported into `1.24` release. The solution could be consumed with `1.24.8` patch, which is expected to be release in the beginning of August.

Best regards,
Boyan

**Comment by Abanindra** [comment] 2024-07-30 13:46
Thank you @unazko for the update.

**Comment by rv97** [comment] 2024-08-01 04:08
Thanks @unazko !

**Comment by shubhamnazare** [comment] 2024-08-22 08:07
Hi @unazko 

I was validating the fix with the above codesandbox example and unfortunately the issue is still reproducible. The versions I used were - `ui5/webcomponents: 1.24.8` and `ui5/webcomponents-react: 1.29.6`.

Could you please validate from your side and confirm the same if possible.

Thanks a lot!

**Comment by rv97** [comment] 2024-09-17 07:15
Hi @unazko ,

I opened the sandbox link which you had mentioned. I am still able to reproduce the issue.
Here is the video of me doing the same: https://sap-my.sharepoint.com/:v:/p/vignesh_r02/EahKUzIpMblNsW5dGYVsaggByZ9iCPOjl1KdAwurmy2Elg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=DoriS7

Steps:
Show Menu -> New File -> Open

You can see it is stuck at the loading indicator forever until i go back one level and open it again.

CC @shubhamnazare @Abanindra

**Comment by unazko** [comment] 2024-09-17 07:54
Hi  @rv97,

Thanks for the reproduction steps.
I've managed to reproduce the issue again.
It seems as an additional scenario to the same issue. Hopefully I'll manage to fix it faster.
We'll be aiming for a next release next week or the week after.

**Comment by unazko** [comment] 2024-09-20 08:46
Hi @rv97, @shubhamnazare, @Abanindra,

The issue should be now fixed via related PR request in 1.24.10 patch, which was just released.
Please do perform a re-test at your side via the provided sample:
https://stackblitz.com/edit/vitejs-vite-pekkod?file=public%2Findex.html
I've switched on 1.24.10 patch and the issue isn't reproducible any longer.

**Closed by unazko** 2024-09-20 08:46 UTC
Labels: bug, High Prio, TOPIC B
