### ISSUE TITLE
[ui5-list]: ui5-content-native-scrollbars not take effect 

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#9720] opened 2024-08-21 14:06 UTC
### Bug Description

ui5-content-native-scrollbars not take effect for ui5-list

### Affected Component

ui5-list

### Expected Behaviour

when set ui5-content-native-scrollbars, should use browser native scrollbar

### Steps to Reproduce

1. open list sample https://stackblitz.com/edit/github-nnzvzv-afrgrj?file=src%2FApp.tsx

### Log Output, Stack Trace or Screenshots

![image](https://github.com/user-attachments/assets/a2cee9af-2fb4-417b-80cb-efced0249e0c)

### Priority

Medium

### UI5 Web Components Version

1.24.x

### Browser

Chrome

### Operating System

MAC OS

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment] 2024-08-21 17:20
Hello @SAP/ui5-webcomponents-topic-p  ,

Could you please review the issue with the `ui5-content-native-scrollbars` not applying correctly to the `ui5-list` component?

Thanks and Best regards,
Yana

**Comment by plamenivanov91** [comment] 2024-09-11 10:45
Hell @GongRichard ,

The issue is fixed with changes that @nnaydenow mentioned.

Regards,
Plamen Ivanov

**Closed by plamenivanov91** 2024-09-11 10:45 UTC
Labels: bug, Medium Prio, TOPIC P
