### ISSUE TITLE
<ui5-multi-combobox>-token cannot be deleted

### ISSUE THREAD

**Issue by steffenknoeller** [SAP/ui5-webcomponents#6444] opened 2023-02-08 08:23 UTC
### **Bug Description**
The ui5-multi-combobox-token cannot be deleted if the token text is too long and the MultiComboBox is too small.

### **Expected Behavior**
By clicking the "X"-button within the token, the token should be removed.

### **Isolated Example**
https://codesandbox.io/s/cuvo99
https://cuvo99.csb.app/

      <ui5-multi-combobox>
          <ui5-mcb-item selected text="Stock Transport Order Overdue"></ui5-mcb-item>
      </ui5-multi-combobox> 

### **Context**
- UI5 Web Components version: 1.9.3
- OS/Platform: *
- Browser: *
- Affected component: ui5-multi-combobox

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**
- Organization: SAP

**Comment by dobrinyonkov** [comment] 2023-02-08 08:49
Hello @steffenknoeller, this is duplicate of #6048 and it's already fixed: https://codesandbox.io/s/ui5-webcomponents-forked-q69ye6

**Closed by dobrinyonkov** 2023-02-08 08:49 UTC
