### ISSUE TITLE
[urgent]Application is hanging after exit the wizard

### ISSUE THREAD

**Issue by c5324266** [SAP/ui5-webcomponents#4372] opened 2021-11-22 07:00 UTC
### **Bug Description**
I have added function to exit the wizard. but the wizard steps are hanging i.e) when I close the wizard and come back the steps are hanging for a long time.

### **Expected Behavior**
The application should work fine even though I come back for the second time.

### **Steps to Reproduce**
https://rpmtenant-irp-approuter-rplocal4.cfapps.sap.hana.ondemand.com/cp.portal/logoff.html?sap-language=en
Username: returnablepackaging1@gmail.com
Password: Rpm@123456

Log on the above url
Go to "Upload Master Data" tile
Select the checkbox for "returnable packaging account" and go to step2.
click on cancel button and select the close wizard button. Now the application is exited and move to the home page.\
Now Click "Upload Master Data" tile and repeat the steps by selecting the returnable packaging account and click "step2" button.
Now the application is hanging and it is not entering into the next steps.

View.xml
https://github.wdf.sap.corp/returnable-packaging/returnablepackaging-core/blob/rplocal4/app/masterdataupload/webapp/view/MasterDataWizard.view.xml

controller.js
https://github.wdf.sap.corp/returnable-packaging/returnablepackaging-core/blob/rplocal4/app/masterdataupload/webapp/controller/MasterDataWizard.controller.js

Cancel fragment
https://github.wdf.sap.corp/returnable-packaging/returnablepackaging-core/blob/rplocal4/app/masterdataupload/webapp/view/Cancel.fragment.xml

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: windows10
- Browser: chrome
- Affected component: UI5

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**

-  Very High
- 
Thanks,
Ragu

**Comment by niyap** [comment] 2021-11-22 08:48
Hello @c5324266,

Thanks for sharing your findings!

First of all, the affected control is sap.m.Wizard, not ui5-wizard web component. So, here is not the right place for reporting issues regarding the OpenUI5 controls.
Moreover, this is a public github, so please use the internal communication channels.
Also, there is no any specific issue found out in the control. First of all, the issue should be analyse from the application developer.After the pre-analysis, if you ensure that the issue is caused by the control itself, then you can forward the issue to UI5.

I am closing the incident, since it does not have anything in common with UI5 Web Components.

Kind Regards,
Niya

**Closed by niyap** 2021-11-22 08:48 UTC

**Comment by c5324266** [comment] 2021-11-22 08:52
Hi Niya,
             I am using the following command to exit the application.
history.go(-1);

This command is hanging the application, Please let me know the alternate solution for this.

**Comment by niyap** [comment] 2021-11-22 09:03
Hello @c5324266,

As I told you in my previous reply, that is not the right place, for discussing the issue. Also, I am a UI5 developer, so I am responsible only for UI5 Web Components and UI5 controls related issues.

 Please, use the internal communication channels.

Kind Regards,
Niya

**Comment by c5324266** [comment] 2021-12-02 04:50
Hi,
     I will follow up internally. I removed all the links. Is there any possibility to remove the history or Is it possible to delete this issue?
