### ISSUE TITLE
[MultiComboBox] - Not able to select multiple items when clicked on label in mobile view mode

### ISSUE THREAD

**Issue by yoganjan** [SAP/ui5-webcomponents#8076] opened 2024-01-10 10:45 UTC
### Bug Description

For multicombobox, we are not able to select more than 1 item at a time by clicking on label. We are able to select multiple item when we click on checkboxes. 

### Affected Component

MultiComboBox

### Expected Behaviour

We should be able to select multiple checkboxes even by clicking on the label

### Steps to Reproduce

1. Open https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multicombobox--docs
2. Select mobile view from chrome dev tools
3. Try selecting the options
4. Click on label , we can see dialog gets closed and to check one more item we have to click on it again
5. Click on checkboxes ,we are able to select more than one item
...

### Priority

Medium

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yoganjan** [comment] 2024-01-10 10:48
https://github.com/SAP/ui5-webcomponents/assets/16238780/790ccb0c-f6a8-4eea-9333-a199e3b87876

**Comment by kgogov** [comment] 2024-01-11 12:35
Hi @yoganjan,

Thank you for bringing this to our attention. Our team will review this.

Best,
Konstantin

**Comment by kgogov** [comment] 2024-01-11 12:48
Hello @SAP/ui5-webcomponents-topic-rl,

It appears there may be an issue with the ui5-multi-combobox functionality on **mobile devices**.
Specifically, when an item is selected and then the close button on the popup is clicked, previously selected items do not appropriately display upon closing the popover.

I am unsure if this is the intended behavior. Could you kindly investigate this matter to confirm or rectify the issue?

Thank you in advance.

Best,
Konstantin

**Comment by niyap** [comment] 2024-01-12 06:03
Hello @yoganjan,

Thanks for sharing your findings!

Actually, that is the expected behaviour both on mobile and desktop device. 
Here are our UX Guidelines: https://experience.sap.com/internal/fiori-design-web/multi-combobox/  "**Clicking the label of an entry closes the option list and creates a token for the selected option. To enable multi-selection, every entry also has a checkbox. Clicking a checkbox creates a token. The option list remains open.**" 

Kind Regards,
Niya

**Closed by niyap** 2024-01-12 06:03 UTC
Labels: bug, Medium Prio, TOPIC RL
