### ISSUE TITLE
[TabContainer] Tab is collapsed by default

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#8454] opened 2024-03-15 12:47 UTC
### Describe the bug

We have a TabContainer with 2 tabs, all wrapped in a Dialog.
With UI5WCv1.22.0/UI5WC4Rv1.25.1, the UI looks like this:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/110408767/d2525483-0928-433c-92b2-c7616bb5a297)

With UI5WCv1.23.1/UI5WC4Rv1.26.0, the UI looks like this:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/110408767/191e539f-fddf-4693-a124-f0826f76daaa)

Notice how Tab 1 is collapsed by default. To see the contents of Tab 1, I have to either collapse and re-expand Tab 1, or switch to Tab 2 and back to Tab 1.
I didn't find anything in the changelog that could explain this change of behavior.

Thanks a lot in advance!

### Isolated Example

Being unfamiliar with StackBlitz, I prefer sending you a modified App.tsx of your linked template:
```
import React from 'react';
import {
  Dialog,
  Form,
  FormItem,
  Switch,
  Tab,
  TabContainer,
} from '@ui5/webcomponents-react';
function App() {
  return (
    <Dialog open={true}>
      <TabContainer>
        <Tab text="Tab SAP/ui5-webcomponents-react#1">
          <Form>
            <FormItem label="Something something">
              <Switch />
            </FormItem>
          </Form>
        </Tab>
        <Tab text="Tab SAP/ui5-webcomponents-react#2">
          <Form>
            <FormItem label="Something something">
              <Switch />
            </FormItem>
          </Form>
        </Tab>
      </TabContainer>
    </Dialog>
  );
}

export default App;
```

### UI5 Web Components for React Version

1.26.0

### UI5 Web Components Version

1.23.1

### Browser

Chrome

**Comment by ndeshev** [comment] 2024-03-17 18:46
Hello @SAP/ui5-webcomponents-topic-b,

As Lukas said, currently in v. 1.23 the TabContainer doesn't show initially the content of the first tab if no 'selected' property is set.

Could you please check.

Regards,
Nikolay

**Comment by ilhan007** [comment] 2024-03-17 20:19
Forwarding to @SAP/ui5-webcomponents-topic-rd as owners

**Comment by nnaydenow** [comment] 2024-03-20 07:58
Hello @SAP/ui5-webcomponents-topic-p,

FYI: Issue might come from: https://github.com/SAP/ui5-webcomponents/pull/8201

**Comment by TeodorTaushanov** [comment] 2024-03-26 15:55
The issue is fixed in the main branch.

**Closed** 2024-03-26 15:55 UTC
Labels: bug, Medium Prio, TOPIC RD
