### ISSUE TITLE
ui5-shellbar: shellbar search responsive behavior is not as per UX design spec.

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6576] opened 2023-02-23 16:52 UTC
### **Bug Description**
- shellbar search is not centrally aligned at XL size
- When slowly decreasing the screen from XL to S, the
  search does not collapse into a search
  button, but the shell bar is replaced by
  the search
- The collapsed search of a decreased
 screen does not expand when the
 screen is increased to XL size
 
### **Expected Behavior**
According to https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697898394
- shellbar search should be centrally aligned at XL size
- When slowly decreasing the screen from XL to S, the
  search field should collapse to search button
- When slowly increasing the screen from S to XL, then 
  collapsed search should be expanded.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/'
2. Verify the responsive behavior

### **Context**
- UI5 Web Components version: {1.10.0}
- OS/Platform: {All}
- Browser: {All}
- Affected component: {ShellBar}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}

**Comment by TeodorTaushanov** [comment] 2023-02-24 09:35
Hi @SAP/ui5-webcomponents-topic-p, can you check this one?

**Comment by JarrettChan** [comment] 2023-02-27 23:52
By the way this looks like a duplicate of #6455

**Comment by dobrinyonkov** [comment] 2023-03-09 11:40
duplicate of https://github.com/SAP/ui5-webcomponents/issues/6455

**Closed by dobrinyonkov** 2023-03-09 11:40 UTC
Labels: bug, Medium Prio, TOPIC P, SF
