### ISSUE TITLE
[Select] Component not scrollable

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#941] opened 2019-11-15 15:04 UTC
**Describe the bug**
options in a select are not scrollable. It leads to hidden options.

**To reproduce**
create a select component with enough elements to have a higher height than the window size.

**Isolated example**
https://codesandbox.io/s/vue-template-p4we3

**Expected behavior**
options should be scrollable inside a select view.

**Context**
- UI5 Web Components version
- OS/Platform: MacOS
- Browser *(if relevant)*: chrome

**Affected components**
* ui5-select
* ui5-option

**Comment by MapTo0** [comment] 2019-11-18 08:18
Duplicate of https://github.com/SAP/ui5-webcomponents/issues/853

**Comment by MapTo0** [comment] 2019-11-18 08:18
Hello @mehdijouan 

We've already fixed this issue. Expect the fix in he next release.

Regards,
Martin

**Closed by MapTo0** 2019-11-18 08:18 UTC
