### ISSUE TITLE
Modals: flickering position

### ISSUE THREAD

**Issue by tkeiner** [SAP/ui5-webcomponents#10211] opened 2024-11-18 13:03 UTC
### Describe the bug

On rendering of a Modal component (e.g. Toast or MessageBox) the position of the component is not fixed, which makes it look like the component flickers into the screen.

This behaviour does not always occur but is easily reproducible by opening a Modal multiple times and changing the width of the screen between render.

### Isolated Example

https://stackblitz.com/edit/github-d34zwy?file=src%2FApp.tsx

### Reproduction steps

1. Create Modal Component
2. Trigger Modal Component to open

### Expected Behaviour

Ideally the Component should be rendered at the correct position without a change position being noticeable by a human.

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment] 2024-11-20 11:45
Hello @tkeiner,

Thank you for reaching out.

Indeed the issue is basically the same as the one mentioned in the above reply. It is reproducible with all popup components even without the `Modals` provider - https://stackblitz.com/edit/github-8upxfb-ndn9tp?file=index.html,main.js.

I am closing this issue as a duplicate, therefore please track the progress there.

Kind regards,
Ivaylo

**Closed by ivoplashkov** 2024-11-20 11:45 UTC
Labels: bug
