### ISSUE TITLE
[storybook]: API table unwanted string

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#7407] opened 2023-08-03 13:52 UTC
### Bug Description

The API table has some unwanted "UI5" string (reported here: https://github.com/SAP/ui5-webcomponents/issues/7284):
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/720100f6-a84b-42b4-a8bd-44c6487225db)
It comes from the Story book file of the component:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/0bcdf702-ea87-4acb-9513-23c922759df0)
It will fix the issue if for the "component" we set an Object similar to the one for the "subcomponent",
but this is not possible - we receive the following error in the Story book:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/fbf5a939-cb4c-44e8-b1a1-41f4f57a418f)

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

main

### Browser

Chrome

### Operating System

Windоws

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment] 2023-09-14 07:02
Hi, @LidiyaGeorgieva ,
I am not able to reproduce this issue anymore.

Can you, please, re-check?
Thank you!

Best regards,
Petya Markova.
(UI5 WC Developer)

**Comment by LidiyaGeorgieva** [comment] 2023-09-14 07:53
Hi, @PetyaMarkovaBogdanova it is OK now. 
I check and it is fixed with this pull request: https://github.com/SAP/ui5-webcomponents/pull/7436

**Comment by PetyaMarkovaBogdanova** [comment] 2023-09-14 08:23
@LidiyaGeorgieva Thank you for the research. I am closing the issue.

**Closed by PetyaMarkovaBogdanova** 2023-09-14 08:23 UTC
Labels: bug, Medium Prio, TOPIC P, author action, Storybook
