### ISSUE TITLE
TabContainer: Selecting tab programmatically, does not refresh selected tabs in the toolbar and the overflowButtons

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5172] opened 2022-05-04 15:26 UTC
**Describe the bug**
Selecting tab programmatically, does not refresh selected tabs in toolbar and overflowButtons.

**Isolated Example**
https://codesandbox.io/s/jovial-cloud-zilwwr?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/jovial-cloud-zilwwr?file=/src/App.js
2. Click on Button "Tab 5"
3. Tab 5 content is now visible and selected but the toolbar and the overflowButtons didn´t refresh the tab selection

**Expected behavior**
If you select a tab programmatically, the toolbar and the overflowButtons should refresh too and should show the currently selected tab visually.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: Latest
`@ui5/webcomponents-react` version: Latest
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by C3ntraX** [comment] 2022-05-04 15:47
Hi @Lukas742 

thanks.

Additional, is there a way to remove the focus, when the selected element changes? I used a swipe left/right algorhytmus, but this way, the selected tab changes but the focus keeps.

**Comment by C3ntraX** [comment] 2022-05-08 00:02
Hello @ilhan007,

is this bug considered or in some way duplicated? I mean the TabContainer is very buggy at the moment with many issues. 

Best regards

**Comment by niyap** [comment] 2022-05-10 08:50
Hello Colleagues,

Could you please look over the issue?

When the tab container has overflow menu and you programatically try to change the selected tab from the current one to one of those in the overflow menu, the selection is change but the newly selected one does not become the active one, just the focus is removed from the current one but it stays the active one.
I checked in Snippix and in openUI5, when the selection is changed in a similar way, the active tab becomes the newly selected one.
The issue could be reproduced in the CodeSandbox provided and in the sample test page if you adjust one of the samples with the same behaviour as the one from the sample provided.

If all tabs are visible (remove the defined width and height from the CodeSandbox added to the TabContainer), the issue is not reproducible and the selection is changed successfully.

Kind Regards,
Niya

**Closed** 2022-08-12 12:20 UTC
Labels: bug, Medium Prio, TOPIC RD
