### ISSUE TITLE
Link: Unreadable text with fiori_3_dark

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents#5307] opened 2022-06-01 13:40 UTC
### **Bug Description**
The text when using the `Link` component is not readable when using `sap_fiori_3_dark` theme.

### **Expected Behavior**
The text should be readable on dark theme.

### **Isolated Example**
I am not able to provide a sandbox since importing 
`@ui5/webcomponents/dist/Assets.js`
crashes the sandbox

https://codesandbox.io/s/ui5-webcomponents-forked-lkre2e?file=/src/index.js
### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Windows 10
- Browser: Edge - 101.0.1210.53
- Affected component: Link

### **Log Output / Stack Trace / Screenshots**
The provided screenshots are from our application. It might be possible the link is darker color because it is visited. 
However, it still does not seem correct.

After version 1.3.0
![image](https://user-images.githubusercontent.com/21200806/171417274-8520c14b-6e48-46ba-a8b5-3c9ada54fcbf.png)

Before
![image](https://user-images.githubusercontent.com/21200806/171417370-eef135d8-59ea-439f-ba8a-fc200e5a251c.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: RBSC
- Business impact: {...}

**Comment by AndrianStoikov** [comment] 2022-06-01 14:51
Hi @PetyaMarkovaBogdanova,

As I mentioned I am not able to create a working sandbox for this issue as well. As I mentioned when I import the `@ui5/webcomponents/dist/Assets.js` it crashes. However, to work with the themes you need this import as far as I understand. If someone from the team does know why it happens it will be greatly appreciated.

**Comment by AndrianStoikov** [comment] 2022-06-01 14:54
@PetyaMarkovaBogdanova,

Another option to observe the behavior is in the web-components docs.

https://sap.github.io/ui5-webcomponents/playground/components/Link/?sap-ui-theme=sap_horizon_dark&isrtl=false

![image](https://user-images.githubusercontent.com/21200806/171434616-c889f3e5-f93a-41aa-a795-0bd284f84730.png)

**Comment by AndrianStoikov** [comment] 2022-06-24 10:07
Hello colleagues,

Is there any update on this issue?

**Comment by tsanislavgatev** [comment] 2022-06-28 06:47
Hello @AndrianStoikov ,

The issue is fixed with the latest versions:
https://sap.github.io/ui5-webcomponents/playground/components/Link/?sap-ui-theme=sap_horizon_dark&isrtl=false
https://sap.github.io/ui5-webcomponents/playground/components/Link/?sap-ui-theme=sap_fiori_3_dark&isrtl=false

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2022-06-28 06:47 UTC
Labels: bug, High Prio, TOPIC B, RBSC
