### ISSUE TITLE
The "Standard" button from the Fiori Guidelines does not exist on the ui5-webcomponents button

### ISSUE THREAD

**Issue by ekeyur** [SAP/ui5-webcomponents#7144] opened 2023-06-02 14:16 UTC
### Bug Description

The "Standard" button from the Fiori Guidelines does not exist on the ui5-webcomponents button. SFSF

### Affected Component

Button

### Expected Behaviour

There should be a "Standard" button or the "default" button should look like the standard button in ui5-webcomponents. Below are the Fiori guidelines for the button component: https://experience.sap.com/fiori-design-web/button/#button
![ui5_button_guidelines](https://github.com/SAP/ui5-webcomponents/assets/19393644/a0d4a85e-bf63-4826-b295-5f6571d6ea03)

Below are the options available on the ui5-webcomponents: https://sap.github.io/ui5-webcomponents/playground/components/Button/
![ui5-webcomponents-button](https://github.com/SAP/ui5-webcomponents/assets/19393644/4c7b7b4d-0402-4001-ae56-d5aecee5dae3)

As you can see, there is no "Standard" button or the "Default" button does not look like the "Standard" button. 

### Isolated Example

https://experience.sap.com/fiori-design-web/button/#button

### Steps to Reproduce

The Default button does not look like Fiori Guidelines Standard button. There is a discrepancy on the types of buttons available.  

### Log Output, Stack Trace or Screenshots

![ui5-webcomponents-button](https://github.com/SAP/ui5-webcomponents/assets/19393644/403631cb-5193-402f-a53c-c60ff5cae1da)
![ui5_button_guidelines](https://github.com/SAP/ui5-webcomponents/assets/19393644/253f9ed8-67e2-43fb-91bf-9eee2321c791)

### Priority

High

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Operating System

MAC OS

### Organization

SFSF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment] 2023-06-02 14:52
Hi team,
can you, please, check the background of the standard button type?

Kind regards,
Petya Markova
(UI5 WC Dispatcher)

**Comment by hxempty** [comment] 2023-07-12 08:25
I have the same issue with  ekeyur

**Comment by hxempty** [comment] 2023-07-18 09:15
any update on this issue? could you please help provide an ETA? thanks.

**Comment by tsanislavgatev** [comment] 2023-09-14 08:37
Hello @ekeyur ,

The issue is fixed in the master branch.

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2023-09-14 08:37 UTC
Labels: bug, High Prio, TOPIC B, SF, SAP Design
