### ISSUE TITLE
[SF][ui5-menu]: JS error when mouse over on icon area of none-icon menu item

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5654] opened 2022-08-10 12:37 UTC
### **Bug Description**
Menu with icon item and none-icon item. When  mouse over on icon area of none-icon menu item, there will have js error.
Please fix it in 1.6.X or 1.7.0.

### **Expected Behavior**
No js error.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Menu/'
2. click button "Open Menu"
3. mouse over on left area of "Close" menu item
4. check console and there has js error.

### **Context**
- UI5 Web Components version: {1.6.0}
- OS/Platform: {macOS}
- Browser: {Chrome}
- Affected component: {ui5-menu}

### **Log Output / Stack Trace / Screenshots**
<img width="898" alt="image" src="https://user-images.githubusercontent.com/13098801/183902430-84bd4669-526f-4033-ba15-b5adc9f79095.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by ilhan007** [comment] 2022-08-31 09:08
FYI @SAP/ui5-webcomponents-topic-b lowering the priory.

Hello @GongRichard based on the recent priority list of SF issues, this is not a "HIgh", lowering to "Medium"

**Comment by tsanislavgatev** [comment] 2022-09-05 09:01
Hello,

@GongRichard The issue is fixed in the latest release: https://sap.github.io/ui5-webcomponents/playground/components/Menu/ 

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2022-09-05 09:01 UTC
Labels: bug, Medium Prio, TOPIC B, SF
