### ISSUE TITLE
[SF][ui5-table]: loadmore event will be triggered if set table row data later

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#6243] opened 2023-01-05 07:56 UTC
### **Bug Description**
loadmore event will be triggered if set table row data later

### **Expected Behavior**
loadmore event shouldn't be triggered if loading data finished after table rendering

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/jolly-northcutt-mcgron?file=/src/App.js'
2. adjust right side content with more width
3. refresh right side content
4. check console log and you will see  loadmore event was triggered

### **Isolated Example**
https://codesandbox.io/s/jolly-northcutt-mcgron?file=/src/App.js

### **Context**
- UI5 Web Components version: {1.9.1}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {ui5-table}

### **Log Output / Stack Trace / Screenshots**
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/13098801/210729654-7082a906-26d4-4fe9-9c62-69b76e8c3488.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by mindarelus** [comment] 2023-01-05 12:27
The bug is very easy reproducible in the example. According to the documentation:

**onLoadMore | Fired when the user presses the More button or scrolls to the table's end.
Note: The event will be fired if growing is set to Button or Scroll.**

**Comment by mindarelus** [comment] 2023-01-05 12:29
Hello @SAP/ui5-webcomponents-topic-rl , take a look of this issue.
The related doc:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-table--default-story

**Comment by elenastoyanovaa** [comment] 2023-01-05 14:25
Hello @mindarelus ,

Could you please verify if the issue is present with plain ui5-table and return the ticket back to us with a link to a sample, where we could reproduce the issue with ui5 web components?

Thanks in advance!

Kind Regards,
Elena

**Comment by ndeshev** [comment] 2023-01-20 09:01
Hello @GongRichard, 

I'm not able to reproduce the issue with plain` Table `UI5 WebComponent.

https://codesandbox.io/s/ui5-webcomponents-forked-fo2wor?file=/index.html

The `load-more` event is only triggered when the table is scrolled to the bottom.

If there is something missing in the snippet that needs to be added in order to reproduce the problem please do so.

**Comment by ndeshev** [comment] 2023-01-23 14:02
Hello again, seems like the event is triggered when the table is scrolled to the end, but that is also true on initial rendering if there is no scroll present. I will check this with my team and respond to you with update shortly.

**Comment by GongRichard** [comment] 2023-02-07 05:55
Hi @ndeshev,
As we has lots of rows, we need do pagination. And we want to let user to scroll down to trigger the 'load-more' event to load more data. In this case, for the first time, it will auto trigger the 'load-more' event and load 2 pages data. It doesn't make sense to us.
Thanks,
Richard

**Comment by ivoplashkov** [comment] 2023-02-15 11:13
Hello @GongRichard,

As @ndeshev has stated in his reply: "since the table bottom end is visible, the event is fired. We can not determine if there will be items added some time in the future."

I am closing this issue as we consider this to be the expeceted behavior of the event.

Best regards,
Ivaylo

**Closed by ivoplashkov** 2023-02-15 11:13 UTC
Labels: Medium Prio, TOPIC RL, SF
