### ISSUE TITLE
DatePicker: can't set value-state in change-event-listener

### ISSUE THREAD

**Issue by eswortmaler** [SAP/ui5-webcomponents#4695] opened 2022-02-03 15:52 UTC
### **DatePicker: can't set value-state in `change` event-listener**
When setting the `value-state` attribute inside the `change` event-listener, as showcased in the documentation for DatePicker (section "DatePicker with Placeholder, Tooltip, Events, ValueState and valueStateMessage"), the `value-state` attribute gets immediately overwritten, if a new date is set using the GUI.

### **Expected Behavior**
It should be possible to set the `value-state` attribute in an event-listener.
After executing the steps below I would expect the DatePicker to look like this:
![image](https://user-images.githubusercontent.com/23629712/152374614-33bdb980-b1fa-42dc-abed-23bf773dc05a.png)

### **Steps to Reproduce**
1. add DatePicker to html
```html
<ui5-date-picker id="myDatepicker">
    <div slot="valueStateMessage">Some text</div>
</ui5-date-picker>
```
2. register the event-listener:
```javascript
const dp = document.getElementById("myDatepicker");
dp.addEventListener("change", (e) => {
  dp.setAttribute("value-state", "Error"); // setting value-state explicitly
  console.log(dp.getAttribute("value-state")); // checking that value-state has been set
  setTimeout(() => {
    console.log(dp.getAttribute("value-state")); // checking 1 ms later
  }, 1);
});
```
3. click on the calnder icon to open the date picker GUI
![image](https://user-images.githubusercontent.com/23629712/152373213-05bf5c72-13e5-44d6-ada8-79cce19f47e0.png)
4. click to select a date. The date is now displyed in the DatePicker, however the error is not displayed
(red outline, if not selected + message, if selected)
![image](https://user-images.githubusercontent.com/23629712/152373798-36379d1e-01b9-462e-b28d-4704fb7865d4.png)
Looking at the console output:
![image](https://user-images.githubusercontent.com/23629712/152374047-00f40a81-662e-46b7-b846-71f738e1f2ef.png)
It seems like the `value-state` attribute gets overwritten, after the event-listener executes

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-l8e24?file=/src/index.js

### **Context**
- UI5 Web Components version: tested on 1.0.2 (linked example) and 1.1.2
- OS/Platform: Windows 10
- Browser: Firefox, Chrome, Edge
- Affected component: DatePicker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: rit-edv consulting
- Bussiness impact: I have a use case, where the allowed values for a DatePicker depend on other DatePickers and TimePickers, so I need to do custom validation and set the valueStateMessage accordingly. I belive this should be possible, since even the documentation has an example like this.

**Comment by eswortmaler** [comment] 2022-02-03 15:56
This might be a duplicate of  #4684

**Comment by Shtilianova** [comment] 2022-02-04 08:56
Hello @eswortmaler,
Thank you for detailed explanation. As the issue is duplicated I'm closing this one. Please track the progress the the case in [#4684](https://github.com/SAP/ui5-webcomponents/issues/4684) 
Regards,
Diana

**Closed by Shtilianova** 2022-02-04 08:56 UTC
