### ISSUE TITLE
[Dialog]: the initialFocus property of Dialog not working in mobile view

### ISSUE THREAD

**Issue by saurabhmehta13** [SAP/ui5-webcomponents#8399] opened 2024-03-06 09:48 UTC
### Bug Description

We can use Dialog "initialFocus" property to set focus on the element inside the dialog once the dialog is launched.
This property is working fine in the web view but when the dialog is used in the context of hybrid mobile app, the focus is not getting set.

### Affected Component

Dialog

### Expected Behaviour

The focus should be set to the element specified in "initialFocus" property.

### Steps to Reproduce

In the attached image, dialog component has been used in a web page which is embedded in the Hybrid mobile app.
When user launches this screen, ideally focus should be set on the "Search for attribute" input field but its not focusable.

Because of this issue, this particular UI is no longer accessible.

![WSM-23639](https://github.com/SAP/ui5-webcomponents/assets/60343832/87e80493-dc74-40cd-ac39-ed2908f2d850)

### Priority

Medium

### UI5 Web Components Version

1.20.0

### Browser

Chrome, Safari

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment] 2024-03-06 13:01
Hello @saurabhmehta13 ,
Could you please share more information about your hybrid app and how we can test and reproduce the issue? If there is a sensitive information, you can share details internally.

Regards,
Iliana

**Comment by ndeshev** [comment] 2024-03-12 09:07
Hello @ui5-webcomponents-topic-rd,

Could you please discuss this issue and provide more details about the desired behaviour of the initially focused input in a `ui5-dialog` in UI5 Web Components. Currently, in UI5 classic, the keyboard opening is prevented on initial focus because of a viewport size issues with some of the mobile operating systems. That is not the case with the behaviour of the Dialog component at the moment. 

If it should be aligned, then this issue is contradicting with the desired functionality.

Kind regards,
Nikolay

**Comment by GerganaKremenska** [comment] 2024-03-14 06:50
Hello @saurabhmehta13, 

I have requested additional information for the issue internally as there is sensitive information. Setting the issue to author action until the information is received.

Best Regards,
Gergana

**Comment by saurabhmehta13** [comment] 2024-03-14 12:49
Hi @GerganaKremenska 
Required details have been shared internally.

Thanks,
Saurabh

**Comment by TeodorTaushanov** [comment] 2024-05-23 07:43
This issue is fixed in 2.0 branch.

**Closed by TeodorTaushanov** 2024-05-23 07:43 UTC
Labels: bug, Medium Prio, TOPIC RD, SAP SF, SF_ACC
