### ISSUE TITLE
`<ui5-dialog>` content is not selectable to copy/paste

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3510] opened 2021-07-15 21:19 UTC
### **Bug Description**
We open `<ui5-dialog>` with text inside to show version information to the user for debug purpose, we refactor recently from ui5 to wc dialog. The wc version has text inside which cannot be selected by click/drag.

### **Expected Behavior**
We should be able to easily select text and copy/paste it.

### **Steps to Reproduce**
1. Go to the playground page
2. Run `(function(a,b) {a.innerHTML="hello world";b.appendChild(a);a.open();})(document.createElement('ui5-dialog'), document.body);` from the console
3. Try to select the text "hello world" to copy and paste somewhere

### **Isolated Example**
Not required.

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Bussiness impact: {...}

**Comment by alexandar-mitsev** [comment] 2021-07-16 12:42
Hello @SAP/ui5-webcomponents-team-rd , 

The issue can be reproduced with the given instructions or with the sample "Open Message Dialog" on the test page.
The text can not be selected.

Regards,
Alex

**Comment by gmkv** [comment] 2021-07-16 12:58
Hi @codefactor 
This issue is a duplicate of #3466
I will close this one, increase the priority of the other.
You can follow the progress on this bug there.

Regards,
Georgi

**Closed by gmkv** 2021-07-16 12:58 UTC
Labels: High Prio, SF, TOPIC RD, bug

**Comment by ilhan007** [comment] 2021-08-03 09:10
Hello @codefactor the fix has been released with 0.31.14
