### ISSUE TITLE
ui5-popover does not close when clicking outside of it

### ISSUE THREAD

**Issue by m-ignatov** [SAP/ui5-webcomponents#2266] opened 2020-09-29 06:49 UTC
Hi colleagues,
When we have a popover which opens a dialog, it seems that after the dialog has been closed, the popover cannot be closed when clicking outside of it. 

**To reproduce**
1. Open a popover and click on the button 'Open Dialog'.
2. In the dialog, click on the 'Dismiss' button to close the dialog.
3. Now, the popover cannot be closed when clicking outside of it.
However, the popover closes after pressing 'Escape' several times.

**Isolated example** 
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-304j8?file=/index.html)

**Context**
- UI5 Web Components version: 1.0.0-rc.8

**Comment by fifoosid** [comment] 2020-09-29 08:07
Hello @m-ignatov 

Not closing the ```ui5-dialog``` on click is the expected behaviour of the component.
However, it should be closed on the first press of ESC key.

In your example, I couldn't reproduce an issue. I am attaching a video where you can see that clicking doesn't close the dialog, but once I press ESC key, the dialog is closed. On the next press of ESC, the popover is closed.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/16850339/94530433-c4a2cc80-0243-11eb-827d-e1f14f1b25f0.gif)

**Comment by m-ignatov** [comment] 2020-09-29 08:14
I think there was a misunderstanding here 😄 
The issue is with the popover - when you close the dialog with the 'Dismiss' button, the popover remains open and it cannot be closed when clicking outside of it. Is this expected or I am missing something?

**Comment by fifoosid** [comment] 2020-10-01 07:07
The issue now is resolved 😄

**Closed** 2020-10-01 07:07 UTC
