### ISSUE TITLE
Input Fields inside Dialog can not be focused by mouse click in Safari

### ISSUE THREAD

**Issue by rebeccaspixel** [SAP/ui5-webcomponents#5980] opened 2022-10-28 11:29 UTC
### **Bug Description**
Input Fields inside a Dialog can not be focused by mouse click In Safari browser in case there is a dialog footer slot used, because the focus will switch to the button inside the Dialog Footer.

### **Expected Behavior**
Input Fields inside a Dialog can be focused via mouse click.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Dialog/ in Safari
2. Open the Basic Dialog Example
3. Click in the Email input field
4. The Email input is shortly focused, then the focus is switched back to the Register Button in the Dialog Footer (In case this works, try again after clearing the browser cache)

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-yiic82?file=/index.html)

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: Mac OS 12.6.1
- Browser: Safari version 16.1
- Affected component: Dialog

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

**Comment by MapTo0** [comment] 2022-10-28 13:47
Hello @SAP/ui5-webcomponents-topic-rd 

The issue is regarding popups and focus forwarding. I simplified the example a little bit:

```html
<body>
	<ui5-button id="openDialogButton" design="Emphasized">Open Dialog</ui5-button>

	<ui5-dialog id="hello-dialog" header-text="Register Form">
		<section class="login-form">
			<div>
				<button id="username">Click outside me</button>
			</div>
		</section>

		<div slot="footer" class="dialog-footer">
			<div style="flex: 1;"></div>
			<button id="closeDialogButton" design="Emphasized">Register</button>
		</div>
	</ui5-dialog>

	<script>
		var dialogOpener = document.getElementById("openDialogButton");
		var dialog = document.getElementById("hello-dialog");
		var dialogCloser = document.getElementById("closeDialogButton");

		dialogOpener.addEventListener("click", function () {
			dialog.show();
		});

		dialogCloser.addEventListener("click", function () {
			dialog.close();
		});

	</script>
</body>
```

Click on the body (non interactive element) of the dialog forwards the focus to the last focusable element of the dialog. 
**The issue is reproducible only in Safari**

Regards,
Martin

**Comment by kskondov** [comment] 2022-11-07 15:58
Hello @rebeccaspixel and @MapTo0 
Can you please confirm that the issue is still reproducible with the latest version of Safari as I was not able to reproduce even after clearing caches
Best Regards,
Konstantin

**Comment by rebeccaspixel** [comment] 2022-11-09 14:30
Hi @kskondov 
I was able to reproduce it on Safari 16.1, MacOS 12.6.1 and also on Safari 16.1, MacOS 13.0.
It always happens for me after loading the page once with developer tools open and the Caches disabled setting activated. Then after every page reload the bug occurs.
I retested it with the first example on this page: https://sap.github.io/ui5-webcomponents/playground/components/Dialog/ and the  [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-yiic82?file=/index.html) example
Kind regards,
Rebecca

**Comment by LidiyaGeorgieva** [comment] 2022-12-20 12:53
Hi @rebeccaspixel ,

I tested it on Safari 16.0 and 16.2
On 16.2 the issue is not reproducible.
Please retest with the latest version of Safari.

Best Regards,
Lidiya

**Comment by rebeccaspixel** [comment] 2022-12-28 12:28
Hi @LidiyaGeorgieva , 
I tested it again in Safari 16.2 (18614.3.7.1.5), Mac OS 13.1 (22C65) and it is still reproducible for the first example here:
https://sap.github.io/ui5-webcomponents/playground/components/Dialog/ 
Kind regards, 
Rebecca

**Comment by s-todorova** [comment] 2023-01-05 14:57
Hello,
After testing it multiple times on different machines with Safari 16.2 (18614.3.7.1.5) , Mac OS Version 13.1 (22C65), we haven't be able to reproduce this issue.
It seems that the problem arose from Safari, which has been fixed with the latest version.
Furthermore, we think that the circumstances in which this issue occurs are extremely specific (only with developer console оpen) and the typical application user will most likely not run into this issue.
Therefore, I am closing it.
Best regards,
Siyana

**Closed by s-todorova** 2023-01-05 14:57 UTC
Labels: bug, ACC, High Prio, TOPIC RD
