### ISSUE TITLE
[Feature Request]: Down arrow button in drop-down won't scroll the list

### ISSUE THREAD

**Issue by sanketzad** [SAP/ui5-webcomponents#8237] opened 2024-02-05 10:16 UTC
### Feature Request Description

Impacted components: `ui5-combobox` and `ui5-multi-combobox`

The drop-down is opened, and using the down arrow button, if the user starts navigating through items, once the user reaches the last item that is visible in the list, ideally that item should be visible in the drop-down, but it won't be there because scrolling is not working as expected when navigating through the keyboard.

Sample snippet: 

<img width="246" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/40885376/c8f5f331-7527-40ca-81a1-0633cba06889">

### Proposed Solution

Ideally, when the keyboard is used to navigate through the list items, the scroll should happen, displaying other list items that are hidden by overflow: none, bring selected and/or selected item + 2 items to the view port of the drop-down.

### Organization

Ariba

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment] 2024-02-05 12:24
Hello @SAP/ui5-webcomponents-topic-rl,

In the `ui5-combobox`, when the drop-down is opened and the user uses the arrows to scroll through items, the last items in the list can not be reached, because the scrolling is not working.
It could be reproduced on the following [codesandbox example](https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-9pzvlv?file=%2Findex.html)
Could you please have a look at it?

Thanks and Regards,
Yana

**Comment by elenastoyanovaa** [comment] 2024-02-06 14:59
Hello @sanketzad ,

Could you please provide a sample as I am not able to open the codesandbox from Yana, nor I am able to reproduce the issue with our available samples in the storybook?
Please use the following template and adjust accordingly:
https://stackblitz.com/edit/js-vsrpnb?file=index.js,index.html

Kind Regards,
Elena

**Comment by sanketzad** [comment] 2024-02-07 03:03
Hi @elenastoyanovaa ,

Please run following project created using the aforementioned URL shared by you.

Sample example: https://js-mcw9hl.stackblitz.io/

Please look for the combobox example and try navigating using the keyboard down arrow button; you will see the problem of responsive popover not getting scrolled.

With regards,
Sanket Zad

**Comment by elenastoyanovaa** [comment] 2024-02-07 11:03
Hello,

You should update to the latest 1.22 version as a fix for this issue is already available there.
Check the updated sample https://stackblitz.com/edit/js-naojmm?file=index.html

The fix is: https://github.com/SAP/ui5-webcomponents/pull/8044/

Kind Regards,
Elena

**Closed by elenastoyanovaa** 2024-02-07 11:03 UTC
Labels: bug, Medium Prio, TOPIC RL, SAP Ariba
