### ISSUE TITLE
【input】:  error when has showSuggestions props and in mobile scenario

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents#5367] opened 2022-06-15 12:59 UTC
**Describe the bug**
There is something wrong with`Input` component when it has `showSuggestions` props and in mobile scenario, adding screenshots for more details.

**Isolated Example**
*https://codesandbox.io/s/inspiring-pine-ismwsi?file=/src/App.js

**To Reproduce**
please see the isolated example

**Expected behavior**
`Input`can render correctly in mobile scenario with props `showSuggestions`

**Screenshots**
![image](https://user-images.githubusercontent.com/10113427/173832831-d408702c-3175-4ca2-8c9c-3c972904ccd5.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.1
Operating System:
Browser: Chrome

**Comment by dimovpetar** [comment] 2022-06-15 15:03
Hello @SAP/ui5-webcomponents-topic-rl ,

There is error on mobile devices thrown by Input.js - getInputDOMRefSync. It looks like this has been fixed 2 weeks ago by https://github.com/SAP/ui5-webcomponents/pull/5292 and can be directly closed, but please check.

Best regards,
Petar

**Comment by niyap** [comment] 2022-06-17 05:26
Hello @tandan0813,

Thanks for sharing your findings!

As Peter has mentioned, the issue is known and already fixed with the following change #5292 

Kind Regards,
Niya

**Closed by niyap** 2022-06-17 05:26 UTC
Labels: bug, Medium Prio, TOPIC RL
