### ISSUE TITLE
[List]: onLoadMore not always fired when the user scrolls to the bottom of the list

### ISSUE THREAD

**Issue by AlbertZ-prog** [SAP/ui5-webcomponents#7426] opened 2023-07-21 14:03 UTC
### Describe the bug

We are implementing a component using, among others, a list ui5 Web Component for React.
When the user scrolls to the bottom of the list, the OnLoadMore is not fired.

We provide bellow a SandBox where the issue occurs from time to time after resizing several times the AnalyticalTable , moving the splitter between the AnalyticalTable and the List.

The SandBox code has the same structure that our component where we reproduce the issue easily.

In our component we have found a workaround that fix the issue when :
- we replace our component ResponsiveFlexElementWrapper (implemented by Jermaine E in connection with your Team, see SandBox code),  that encapsulates the List component, by a div
- and we add a margin bottom of 1px value in the list.
Both steps are necessary to fix the issue.
The issue seems to be related to the height calculation of the list in its container, preventing it to fire the appropriate event.

### Isolated Example

https://codesandbox.io/p/sandbox/aged-architecture-683xrz

### Reproduction steps

iterate several times in the SandBox :
1. scrolls to the Bottom of the list
2. resize the Dialog
3. move the splitter
4. click on AnalyticalTable and List
It is not easy to reproduce with the SandBox.

### Expected Behaviour

onLoadMore always fired when the user scrolls to the bottom of the list

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome, Edge

### Operating System

Microsoft Windows, Mac OS

### Additional Context

If a fix was not possible, would it be possible to implement in the list component a behaviour similar to the one  in AnalyticalTable (infiniteScrollThreshold property to fire the onLoadMore before the user scrolls to the bottom of the list)?

Best Regards.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment] 2023-08-09 12:20
Hello @SAP/ui5-webcomponents-topic-p,

Please have a look at this issue reported for ui5-list.
See the comment from Lucas742.
When I tested on Windows with Chrome the load more event is not fired not even once.

Best Regards,
Lidiya

**Comment by petyabegovska** [comment] 2023-09-25 06:31
Raising to High due to impact in paging function of list in SF.

**Comment by DanielCavemann** [comment] 2024-01-17 09:50
Hi @petyabegovska and @dobrinyonkov ,
Will the fix be available very soon ?
This is a problem us and we don't have a workaround.
Thanks in advance

**Comment by dobrinyonkov** [comment] 2024-01-17 10:35
Hello @DanielCavemann,

Hello @DanielCavemann,

I wanted to update you on the issue you've reported. After investigating today, I found that this problem seems to be specific to the codesandbox iframe environment. When the example is opened in a separate tab, it triggers the 'load more' event as expected. This behavior is consistent with my local tests as well. It appears that when embedded in an iframe with a set height, the event doesn't activate. We're looking into why this is happening. Meanwhile, can you check if your application uses the ui5-list within an iframe, or is it functioning properly for you now as well?

To illustrate, here's what I've observed:

In the iframe on codesandbox, the issue persists: https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-g4s22h?file=%2Fsrc%2Findex.js%3A36%2C1

But when opened directly in a new tab, it works correctly: https://g4s22h.csb.app/ (the event is triggered every time you scroll to the bottom).

Regards,
Dobrin

**Comment by DanielCavemann** [comment] 2024-01-18 09:35
Hello @dobrinyonkov,
Thank you for your fast answer but unfortunately the issue is still reproducible with your sandbox (https://g4s22h.csb.app/)  :-(
With the default window size it works, but when the window size is not the same the issue occurs. We got these issue with Apple, but we get the issue with the following resolution:
- 1920x1024
- 1920 x 1080
- 1467 x 967
- 1728 x 1117
Regards

Daniel

**Comment by dobrinyonkov** [comment] 2024-01-19 08:48
Hi @DanielCavemann,

Thanks, I managed to reproduce this issue witht the following window dimensions:
innerHeight = 1411
innerWidth = 2085

I've prepared a fix: https://github.com/SAP/ui5-webcomponents/pull/8143

Expectations are to be merged and released with the next release start of Feb.

Kind Regards,
Dobrin

**Comment by DanielCavemann** [comment] 2024-01-19 09:57
Hi Dobrin (@dobrinyonkov),
Thanks a lot for your quick update !

Daniel

**Closed** 2024-01-19 10:03 UTC
Labels: bug, High Prio, TOPIC P, SF, SAC
