### ISSUE TITLE
ComboBox should have the option to disable free input

### ISSUE THREAD

**Issue by schempil** [SAP/ui5-webcomponents#5567] opened 2022-07-25 14:59 UTC
### **Feature Request Description**
As a developer that uses the ComboBox component I want to make sure that only valid values are getting entered in the input field. Valid values are for me values that also appear in the options. So we basically want to prevent to have shown values, that are not the same like a selected value out of the options. 

### **Proposed Solution**
Add a property to control if the input should only take valid options as an input. If an input is entered that is not a valid option it should get cleared out when losing focus. 

### **Proposed Alternatives**
Also it could be an idea to completely prevent the user from putting in values with free text. But if the input gets disabled at all, there needs to be an option to clear the selected value again.

### **Additional Context**
-

### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

I put the feature request to "high" as it currently impacts the UX negatively and can lead to confusion. The value that is shown does not necessarily need to be the selected option. Therefore the value can be different from the text that is displayed.

### **Stakeholder Info** (if applicable)

- Organization: SAP SE
- Business impact: UX is not consistent, because shown value in the input does not reflect the selected option of the component.

**Comment by stbodurov** [comment] 2022-07-26 08:45
Hi @schempil,

It is part of the Fiori Design Guidelines for the ComboBox to allow free input: "If the entries are not **validated** by the application, users can also enter custom values.", according to https://experience.sap.com/fiori-design-web/combo-box/. Please take note of the 'validated' keyword.

What are you proposing as a solution already exists as a pattern implemented from the app developer side. Check out the https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBoxValidation sample in UI5. If you try to enter a custom value there, you are presented with an Error value state message. The thing missing from the sample is reverting to a valid value on focusout. 

Also, please keep in mind that an API for disabling free input does not exist in the context of `sap.m.ComboBox` either. As a result, this might be more a feature request to the UX team, rather than the component owners.

Still, I am transferring this to the responsible team. @SAP/ui5-webcomponents-topic-rl, could you take a look at this feature request regarding `ui5-combobox`?

Regards,
Stanislav

**Comment by ilhan007** [comment] 2022-08-31 09:19
Hello @SAP/ui5-webcomponents-topic-rl @nikolay-kolarov 
the author filed the issue as "High", can you re-evaluate the priority. 

This is the input we have by the author:

" I put the feature request to "high" as it currently impacts the UX negatively and can lead to confusion. The value that is shown does not necessarily need to be the selected option. Therefore the value can be different from the text that is displayed."

Org: SAP SE
Business impact: UX is not consistent, because shown value in the input does not reflect the selected option of the component.

**Comment by nikolay-kolarov** [comment] 2022-08-31 12:21
Hi @schempil ,

Stanislav basically provided the answer.
The combobox is by design (https://experience.sap.com/fiori-design-web/combo-box/) allowing free input and if this is not required, you can either add validation in the application (by subscribing to the change event for example) or use the ui5-select component.

Best Regards,
Nikolay

**Closed by nikolay-kolarov** 2022-08-31 12:21 UTC
Labels: feature request, High Prio, TOPIC RL
