### ISSUE TITLE
DatePicker & StepInput: Setting `min-width` is not possible or causing elements to overflow

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#3377] opened 2021-06-02 13:52 UTC
### **Bug Description**
Since the problem with the `DatePicker` and the `StepInput` component have probably the same root cause I created only a single issue for this. In both cases there is a `min-width` set somewhere inside the shadow DOM which cannot be changed with CSS Vars, only by using `addCustomCSS`.

__DatePicker__: It is not possible to set a custom `min-width`.

The min-width is set here:
```
:host .ui5-date-picker-input {
    width: 100%;
    min-width: 12.5625rem;
    color: inherit;
    background-color: inherit;
    line-height: inherit;
    letter-spacing: inherit;
    word-spacing: inherit;
}
```

__StepInput:__ Icon wraps to next row if `min-width` smaller than `9rem`.

The min-width is set here:
```
:host .ui5-step-input-input {
    width: 100%;
    color: inherit;
    background-color: inherit;
    border: 1px solid transparent;
    box-sizing: border-box;
    vertical-align: top;
    margin-top: -1px;
    min-width: 8rem;
    position: relative;
    padding: 0px 2.5rem 0px 2.4375rem;
    outline: none;
}
```

### **Isolated Example**
See [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-3ob69?file=/index.html)

<img width="250" alt="Screenshot 2021-06-02 at 15 45 59" src="https://user-images.githubusercontent.com/9749730/120491577-a46e7300-c3b9-11eb-930b-d1f0b07622fa.png">

**Comment by ilhan007** [comment] 2021-06-02 13:58
@SAP/ui5-webcomponents-topic-b colleagues could you take a look. There are two issues describe, but might be result of a single root cause.

**Comment by tsanislavgatev** [comment] 2021-06-04 13:56
Hello @Lukas742 ,

The wrapping of the StepInput component will be fixed. But it still won't be possible to have smaller min-width. Having smaller min width will mean not showing all of the information. For example in some formats of the DatePicker, on smaller width, the information will be hidden, or in the StepInput, this means that we won't have enough width to present the both buttons for -/+ or the numbers.

Thanks and Best Regards,
Tsanislav

**Comment by Lukas742** [comment] 2021-06-07 06:55
Hi @tsanislavgatev 

makes sense to me, but I still wonder why you can overwrite the min-width of e.g. the `DateRangePicker`, but not that of the `DatePicker`.

**Comment by tsanislavgatev** [comment] 2021-06-08 06:41
Hello @Lukas742 ,

The DateRangePicker should also have a pre-defined min-width, just to ensure that we present the information and we don't hide anything important from the end user. 
And I totally agree that it's good to present such things in documentation, as they are limitations of some kind.

**Comment by Lukas742** [comment] 2021-06-08 07:28
Yup, but the only difference is that it can be overwritten without having to access the shadow DOM. In fact I think the `DatePicker` is the only input component where it's not possible to manually overwrite the min-width.

I know, in most cases it's better to leave the min-width alone, but I was just wondering why it's possible to customize the min-width of e.g. the `DateRangePicker` but not the one of the `DatePicker`. ;)

[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-oty26?file=/index.html) for reference.

<img width="217" alt="Screenshot 2021-06-08 at 09 26 30" src="https://user-images.githubusercontent.com/9749730/121141759-9e561780-c83b-11eb-8744-d21391d2e547.png">

**Comment by awolfish** [comment] 2024-07-15 13:54
There is no any response from the reporter since quite a while.
That's why I am closing it now. If the issue still persists, don't hesitate to reopen it.

**Closed by awolfish** 2024-07-15 13:54 UTC
Labels: bug, Medium Prio, TOPIC B, UI5_WEBC_4_REACT

**Comment by Lukas742** [comment] 2024-07-15 14:05
Hi @awolfish 

the behavior is still reproducible. Also, there wasn't a response requested, neither the `author action` label was added.

If the behavior is intended, then that's fine with me (although I find it still odd). With my last message I just wanted to clarify if this is really the case.

V2 example: https://stackblitz.com/edit/github-k2mqgk?file=index.html,main.js,package.json,node_modules%2F%40ui5%2Fwebcomponents%2Fdist%2FDateRangePicker.d.ts
