### ISSUE TITLE
[Mobile] Input Suggestions do not show for mobile

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4026] opened 2021-09-29 23:27 UTC
### **Bug Description**
In the ui5-wc playground, using the ui5-input as a search bar, attempt to search for a country. In web, an input popover will be displayed with the results. On mobile, there no popover displayed. In our application the user generates a search and when the response comes back we then loop through and create the suggested items. For mobile, the user will need to click the input a second time in order to display the responsive popover. This is because the `_click` function from [Input.js#L716](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Input.js#L716) will attempt to open the Suggestions, but the open function will only open the responsive popover if there are items. Please see: [InputSuggestions.js#L134](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/features/InputSuggestions.js#L134). Judging by design, I think the intent for mobile is that every time the user clicks on the input, the responsive popover should open regardless of items and all the searching and selecting a suggestion should be done within the responsive popover. 

![image](https://user-images.githubusercontent.com/38701667/135360646-bc607491-67c5-425e-95ed-2259e700ce56.png)

![image](https://user-images.githubusercontent.com/38701667/135360702-df898aec-bc36-40a3-b530-95ca9a378428.png)

For a workaround, I can wait for the render scheduler to finish then call `_click` when in mobile, but I think this should be handled internally. 

### **Expected Behavior**
In mobile, a user should be able to search in an input and see the results without having to click the input a second time.

### **Steps to Reproduce**
1. In the ui5-wc playground, select 'Input' and scroll down to the sample for 'Input with Suggestions'. You can see in mobile emulation the suggestion popover will never be displayed.
Mobile:
![image](https://user-images.githubusercontent.com/38701667/135361104-8bf8d70c-d5a5-44ba-b266-d9bc743f191a.png)
Web:
![image](https://user-images.githubusercontent.com/38701667/135361231-c3c83586-7792-4542-a711-5a376da6876f.png)

### **Context**
- UI5 Web Components version: > 0.31.x
- OS/Platform: Windows and Mac
- Browser: All
- Affected component: InputSuggestions

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by Todor-ads** [comment] 2021-10-01 07:47
Hi @SAP/ui5-webcomponents-topic-rl 
The Input component is part of your topic.

Best Regards,
Todor

**Comment by niyap** [comment] 2021-10-04 06:55
Hello @allen138,

Could you please check whether the issue is now reproducible with the following link: https://sap.github.io/ui5-webcomponents/master/playground/components/Input/
as an enhancement is already done via PR #4025 

Kind Regards,
Niya

**Comment by allen138** [comment] 2021-10-04 21:12
Hi @niyap,

Yes the issue seems to be resolved on the ui5 playground. Is it possible to downport those changes to 0.31.x? that is the version SF uses. I’ll also reach out to Han via our internal slack channel.

thanks,
Allen

**Comment by niyap** [comment] 2021-11-12 13:21
Hello Colleagues,

The issue was downported in 0.31, so I am closing the issue.

Kind Regards,
Niya

**Closed by niyap** 2021-11-12 13:21 UTC
Labels: bug, Medium Prio, TOPIC RL
