### ISSUE TITLE
ui5-step-input throwing in lit-html 2.2.2

### ISSUE THREAD

**Issue by lastmjs** [SAP/ui5-webcomponents#5109] opened 2022-04-20 20:44 UTC
### **Bug Description**

`<ui5-step-input>` breaks in lit-html `2.2.2` and snowpack `3.8.8`. The following error is thrown whenever trying to render the element: 

```
lit-html-5d8ac96f.js:formatted:74 Uncaught (in promise) Error: invalid template strings array
    at C (lit-html-5d8ac96f.js:formatted:74:15)
    at new E (lit-html-5d8ac96f.js:formatted:86:21)
    at N._$AC (lit-html-5d8ac96f.js:formatted:277:53)
    at N.T (lit-html-5d8ac96f.js:formatted:263:45)
    at N._$AI (lit-html-5d8ac96f.js:formatted:247:99)
    at x (lit-html-5d8ac96f.js:formatted:46:14)
    at Function.litRender (parameters-bundle.css-24a37f84.js:3141:2)
    at updateShadowRoot (parameters-bundle.css-24a37f84.js:1776:22)
    at HTMLElement._render (parameters-bundle.css-24a37f84.js:2663:4)
    at renderImmediately (parameters-bundle.css-24a37f84.js:768:15)
```

### **Expected Behavior**

`<ui5-step-input>` should not throw an error and should render correctly.

### **Steps to Reproduce**
1. Install lit-html `2.2.2`
2. Install snowpack `3.8.8`
3. Create an `html` tagget template literal and try to use an instance of `<ui5-step-input></ui5-step-input>`

### **Isolated Example**
I was having trouble getting the Code Sanbox environment setup and reproducing the issue there. If you use the versions of lit-html and snowpack that I've indicated, this file will show you the issue:

```html
<!DOCTYPE html>

<html>
    <head>
        <script type="module">
            import "@ui5/webcomponents/dist/StepInput.js";
            import { html, render } from "lit-html";

            class TestElement extends HTMLElement {
                connectedCallback() {
                    render(html`<ui5-step-input></ui5-step-input>`, this);
                }
            }

            window.customElements.define("test-element", TestElement);
        </script>
    </head>

    <body>
        <test-element></test-element>
    </body>
</html>
```

### **Context**
- UI5 Web Components version: 1.2.4
- OS/Platform: Ubuntu 20.04 focal (x86-64)
- Browser: Chrome Version 100.0.4896.127 (Official Build) (64-bit), Brave Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit), Firefox Version 99.0 (64-bit)
- Affected component: ui5-step-input

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

### **Stakeholder Info** (if applicable)

- Organization: Demergent Labs
- Business impact: Just an inconvenience for now, it would be nice to use this type of input but another input type will be okay for the time being

**Comment by lastmjs** [comment] 2022-04-20 20:56
I just tried to use `ui5-slider` in place of `ui5-step-input` and I am getting the same error. These two elements are simply unusable for me (which is a shame).

**Comment by MapTo0** [comment] 2022-04-21 13:45
Just tried to run it using codesandbox and looks good. https://codesandbox.io/s/new-framework-dmrn0p?file=/src/index.js

On the snowpack setup right now.

**Comment by MapTo0** [comment] 2022-04-21 13:57
Do you use a config file for the snowpack? Looks like it is somehow trying to bundle the whole content of `node_modules`, no? I am getting an error even on start without importing any module 
```
[17:57:06] [snowpack] Package "@ui5/webcomponents-base" exists but package.json "exports" does not inc
lude entry for "./dist/asset-registries/Icons.js".
```

**Comment by MapTo0** [comment] 2022-04-21 14:04
Feel free to [PR my repo ](https://github.com/MapTo0/snowpack-ui5-webcomponents)with reproducible setup so we can speed up processing

**Comment by lastmjs** [comment] 2022-04-21 14:36
@MapTo0 the error that you are running into (which I have run into in other situations) seems to be because of the "exports" property that is defined in the `package.json` files of the web components. See here: https://github.com/SAP/ui5-webcomponents/blob/master/packages/base/package.json#L20

That exports file does not include the file that Snowpack needs to import, so it is rejecting it. It seems like the field is being interpreted by some tools as the only exportable fields, I would recommend fixing that explicitly or not using the exports field.

**Comment by MapTo0** [comment] 2022-04-21 14:41
@pskelin any opinion on the `exports`?

**Comment by MapTo0** [comment] 2022-04-21 14:48
I am still getting stuck on the `snowpack build` step with the same error after your PR. Any suggestions?

**Comment by lastmjs** [comment] 2022-04-21 14:54
Or make sure that you deleted your node_modules and build directories entirely and start over from scratch, maybe that had something to do with it.

**Comment by lastmjs** [comment] 2022-04-25 13:41
Have you been able to reproduce the issue? I am running into the same issue now with radio buttons, the entire component is unusable: https://sap.github.io/ui5-webcomponents/playground/components/RadioButton/

**Comment by MapTo0** [comment] 2022-04-26 11:41
Hello @lastmjs 

Yes, I managed to reproduce the issue and we are working on it.
@vladitasev 

# Steps to reproduce

1. Clone https://github.com/MapTo0/snowpack-ui5-webcomponents
2. `npm install`
3. go to `node_modules` and delete `exports { ... }` from `package.json`s
4. `npm start` 

## Notes

- import and render `ui5-radio-button`. Without `text` attribute it renderes good, but when adding it an exception is thrown.
- when having the text set by a property / attribute the button renders `ui5-render` but an `ui5-label` rendered solo does not break the application
- When I remove the `scopeTag()` call from the renderer the issue seems to be solved.

## Other notes

- I tested if it is something with bundling plain `lit-html` with `unsafehtml` and `snowpack` but no issues with that so far.
- I also tested if importing and using the scoping feature solves the issue but - no

**Comment by pskelin** [comment] 2022-04-26 12:43
@lastmjs as a workaround until a fix is prepared and released, you can force the same lit-html version to be used by ui5-webcomponents and your app.

Just add the following to your `package.json`
```
  "resolutions": {
    "@ui5/webcomponents/**/lit-html": "2.2.2"
  },
```

remove `node_modules` and use `yarn` followed by `yarn start` (you will need to install yarn in case you don't have it already).

This will make your all parts of your project use the same version of `lit-html`, essentially the same as the fix.

**Comment by lastmjs** [comment] 2022-04-26 12:45
I see, okay I believe I have run into these kinds of issues before in other projects where I've used lit-html, it's a somewhat mysterious error. Thanks!

**Comment by vladitasev** [comment] 2022-04-26 13:43
Hi @lastmjs 

This seems to be an issue with having multiple lit-html versions. We've made our dependency declaration more liberal so that lit-html will only be bundled once.

The fix has been merged and we'll release a patch version (most probably `1.3.1`) early next week - my guess in Monday.

I'll update this issue once the fix is in NPM.

Regards,
Vladislav

**Closed** 2022-09-19 10:52 UTC
Labels: TOPIC Core
