### ISSUE TITLE
[ui5-calendar] Header buttons do not announce type/role and how to interact

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5766] opened 2022-08-31 18:23 UTC
### **Bug Description**
Hi team, 

When using any calendar, date-picker, date-range, ect, the calendar header buttons do not announce the element type and how to interact. Please see:
![image](https://user-images.githubusercontent.com/38701667/187750150-b1ef3f1b-bd39-475e-ad31-7fe978daf0a8.png)

### **Expected Behavior**
Calendar header buttons should announce '<month/year> Button. To activate press spacebar.'
Here is the example from the [sap.m.DatePicker](https://openui5.hana.ondemand.com/entity/sap.m.DatePicker/sample/sap.m.sample.DatePicker):
![image](https://user-images.githubusercontent.com/38701667/187750962-ea3f90c3-adda-40ce-b661-4a9c65c96ae7.png)

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
3. Press f4 to open the calendar popup. 
4. Tab to the month/year.
5. Notice screen reader only narrates the text and not the element type or how to interact with it.

### **Context**
- UI5 Web Components version: latest
- OS/Platform: all
- Browser: all (tested on Chrome and FF)
- Affected component: All Calendar components

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by ilhan007** [comment] 2022-09-01 08:07
Isn't this the same as
https://github.com/SAP/ui5-webcomponents/issues/5708

**Comment by ndeshev** [comment] 2022-09-01 09:23
Hello @allen138 I've checked the date-time components and the issue is now fixed with the change that @ilhan007 mentioned.

**Closed by ndeshev** 2022-09-01 09:23 UTC
