### ISSUE TITLE
Table: The space key doesn't work inside the table

### ISSUE THREAD

**Issue by Ezuti** [SAP/ui5-webcomponents#3517] opened 2021-07-15 14:56 UTC
**Describe the bug**
If an input is inside a Table, the space key doesn't work. When listening to the keyPress e, event listener can see that it is not triggered by the space key.

**Isolated Example**
[https://codesandbox.io/s/competent-dijkstra-dqmp5?file=/src/App.js](https://codesandbox.io/s/competent-dijkstra-dqmp5?file=/src/App.js
)

**To Reproduce**
1. Go to the input under "Input in ui5 table" or "TextArea in ui5 table"
2. Open the console
3. Try to write a space or a sentence with a space (you can then try outside the Table)
4. See error: The space doesn't appear in the selected component and in the console, the space key doesn't trigger keypress

**Expected behavior**
A space should appear in the text

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.0.0-rc.14 - latest
`@ui5/webcomponents-react` version: 0.17.0 - latest
Operating System: Windows 10
Browser: Chrome

**Additional context**

**Comment by ilhan007** [comment] 2021-07-23 10:20
Hello @SAP/ui5-webcomponents-topic-rl this issue is most probably

duplicate of: https://github.com/SAP/ui5-webcomponents/issues/3390
and fixed with: https://github.com/SAP/ui5-webcomponents/pull/3393

Could you confirm and close if this is the case?

**Comment by niyap** [comment] 2021-07-23 11:19
Hello @Ezuti,

Thanks for sharing your findings!

As Ilhan has mentioned, the issue is already known and fixed. It will be available with the next release.

Kind Regards,
Niya

**Closed by niyap** 2021-07-23 11:19 UTC
Labels: Medium Prio, TOPIC RL, bug
