### ISSUE TITLE
Select: Accessed items not read and/or not accessible at all

### ISSUE THREAD

**Issue by DLaskov** [SAP/ui5-webcomponents#3617] opened 2021-08-10 14:44 UTC
### **Bug Description**
On accessing Select control and opening it with spacebar or enter:
1. Items are not accessible with up/down keys (when accessed with the mouse, it is working, only not working when navigating to the Select item with Tab button and accessing it with enter or spacebar)
2. When the Select control is opened, the first item is not read out by Narrator.

### **Expected Behavior**
1. When Select input is navigated with Tab and items are accessed with spacebar after that all the options should be selectable with up/down arrow keys on the keyboard.
2. When the Select control is opened, the first item should be read out by Narrator.

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Select/

### **Context**
- UI5 Web Components version: latest
- OS/Platform: Windows 10
- Browser: Chrome latest version
- Affected component: ui5-select

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Additional info** (if applicable)
https://support.wdf.sap.corp/sap/support/message/2180312052

**Comment by GerganaKremenska** [comment] 2021-08-12 07:31
Hello @SAP/ui5-webcomponents-topic-p,

The first reported issue is not reproducable: "Items are not accessible with up/down keys (when accessed with the mouse, it is working, only not working when navigating to the Select item with Tab button and accessing it with enter or spacebar)"

The second is reproducable "When the Select control is opened, the first item is not read out by Narrator(JAWS 2021)."
But i am not sure that this is an issue.

Here can be tested: https://sap.github.io/ui5-webcomponents/playground/components/Select/

Can you put in your expretise?

**Comment by dimitar-trendafilov** [comment] 2021-09-14 13:26
This issue has been opened because of BCP ticket https://support.wdf.sap.corp/sap/support/message/2180312052 
The narrator is indeed working weirdly with this Select input. However, I am not sure how it is expected to be. In my opinion this needs to be discussed and clarified further with Jens Bombolowsky and Coders-19 team. I will send an email accordingly.

**Comment by nnaydenow** [comment] 2021-09-24 09:50
Hi @DLaskov ,

The issue is fixed with: #3705 

Regards,
Nayden

**Closed by nnaydenow** 2021-09-24 09:50 UTC
Labels: bug, Medium Prio, CBC
