### ISSUE TITLE
[BUG][UI5-List] Error edit icon direction in RTL mode

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#2962] opened 2021-03-18 05:31 UTC
**Dear colleagues,** 
I am from SuccessFactors Web Experience Shanghai team.
My name is Hubery Shen and this account is our team account.  

**Describe the bug**
Error edit icon direction in RTL mode
code: `<ui5-li icon="edit">edit</ui5-li>`
![image](https://user-images.githubusercontent.com/78520316/111578036-4c7a9400-87ee-11eb-8423-e6083bef2f44.png)

**Comment by d3xter666** [comment] 2021-03-18 07:24
Hi @sfsf-xweb-sh ,

I was not able to reproduce the issue in the [playground](https://sap.github.io/ui5-webcomponents/playground/components/List/) by [setting the mode to RTL](https://sap.github.io/ui5-webcomponents/playground/docs/configuration/)

Could you provide a sample with the issue in [JSBin](https://jsbin.com/), [Plunkr](https://plnkr.co/) or any other suitable tool.

**Comment by ilhan007** [comment] 2021-03-18 07:26
Hello @sfsf-xweb-sh 

by default it gets mirrored, but you can force the direction by:

```html
	<ui5-icon name="edit" dir="ltr" ></ui5-icon>
```

**Comment by ilhan007** [comment] 2021-03-18 07:31
Sorry, the solution above works for the Icon(ui5-icon) if used standalone, but I realised it is in a ListItem (ui5-li) and 
you can set the dir of the Icon( ui5-icon) trough the ListItem (ui5-li).
We will see about this.

**Comment by ilhan007** [comment] 2021-03-18 07:57
Hello @sfsf-xweb-sh 

the issue is  fixed long time ago with https://github.com/SAP/ui5-webcomponents/pull/2645

but not downported in 0.29.

It will be part of the next 0.29.X patch.

BR,
ilhan

**Closed by ilhan007** 2021-03-18 07:57 UTC
Labels: author action
