### ISSUE TITLE
MultiInput: When one Item is selected instead of token control shows "1 more"

### ISSUE THREAD

**Issue by gopisap** [SAP/ui5-webcomponents#5578] opened 2022-07-27 10:38 UTC
**Describe the bug**
When one Item is selected in MultiInput control instead of the selected item token, the control show "1 More". Which is not correct behaviour as per Fiori guidelines.

**Expected behaviour**
When one item is selected it should show the selected item token with truncated text based on the text.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: '1.5.0'
`@ui5/webcomponents-react` version: '0.26.0'
Operating System: MAC and windows
Browser: Chrome

**Comment by stbodurov** [comment] 2022-07-29 07:01
Hi @SAP/ui5-webcomponents-topic-rl,

Tokens with long text in `ui5-multi-input` do not truncate, and the component visualizes the nMore instead. 
You can use https://stackblitz.com/edit/js-qxuz2b to reproduce, if you have trouble loading try using a browser other than Chrome. This is how it behaves in UI5: https://ui5.sap.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInput, the last MI.

Regards,
Stanislav

**Comment by MapTo0** [comment] 2022-07-29 07:16
Duplicate of https://github.com/SAP/ui5-webcomponents/issues/5229

**Closed by MapTo0** 2022-07-29 07:16 UTC
Labels: bug, Medium Prio, TOPIC RL
