### ISSUE TITLE
Different version of CSS variables will cause conflict

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents#3805] opened 2021-09-02 08:56 UTC
### **Bug Description**
When I have multiple instance of UI5 with different versions for example, shell with 0.16, and one microfrontend with 0.18.4, some css paramters will impact on each other.

### **Expected Behavior**
I want both 0.16.x and 0.18.4 and any other version coexist on same page but without impact on each other for css variables, so I suggest we have suffix or prefix to different on css, just like the customElement registry, we can have different checkboxs, <ui5-checkbox-a-mfe /> and <ui5-checkbox-b-mfe />, and consider we also should have css like this and variables
:root {
--_ui5_checkbox_compact_wrapper_padding_a_mfe: 15px;
}

:root {
--_ui5_checkbox_compact_wrapper_padding_b_mfe: 25px;
}

in css

margin-right:var(--_ui5_checkbox_compact_wrapper_padding_a_mfe)
margin-right:var(--_ui5_checkbox_compact_wrapper_padding_b_mfe)

### **Steps to Reproduce**
N/A

### **Isolated Example**
N/A

### **Context**
- UI5 Web Components version: 0.18.4 and 0.16.x
- OS/Platform: Mac
- Browser: Chrome
- Affected component: All

### **Log Output / Stack Trace / Screenshots**
It's similar with https://github.com/SAP/ui5-webcomponents/issues/3781 but not exactly the same
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP CIC
- Bussiness impact: Microfrontend will impact each other's style

**Comment by ilhan007** [comment] 2021-11-19 20:37
Hello @JackieWei it's a duplicate of https://github.com/SAP/ui5-webcomponents/issues/3781
we are closing the current issue, but you can follow the progress in the other one.

**Closed by ilhan007** 2021-11-19 20:37 UTC
Labels: enhancement, Medium Prio, TOPIC Core
