### ISSUE TITLE
[ObjectPage]: Subsection dropdown menu position is not correctly aligned in RTL

### ISSUE THREAD

**Issue by lv-sap** [SAP/ui5-webcomponents#6605] opened 2023-02-27 23:45 UTC
### Describe the bug

_This is related to the JIRA ticket https://jira.successfactors.com/browse/WEF-39011._

In RTL mode, the subsection dropdown menu is not correctly aligned under the Tab button.

See the difference in RTL mode https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--docs&globals=direction:rtl;outline:!true
![Screenshot 2023-02-27 at 3 29 38 PM](https://user-images.githubusercontent.com/8533257/221714121-6c30b3d3-9b56-4f70-82b8-2a450543b172.png)

vs. LTR mode, https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--docs&globals=outline:!true:
![Screenshot 2023-02-27 at 3 26 04 PM](https://user-images.githubusercontent.com/8533257/221714318-17f2db7f-9e97-4482-b2f2-1aad0104cd8a.png)

### Reproduction steps

Use you own Docs page https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--docs&globals=outline:!true to reproduce

### Expected Behaviour

It should probably be aligned in RTL under the Tab button as it is in LTR mode

### UI5 Web Components for React Version

1.9.2

### UI5 Web Components Version

1.9.2

### Browser

Chrome

**Comment by dimovpetar** [comment] 2023-03-14 07:59
Hello @lv-sap ,

The issue is now fixed. Thanks for reporting it :) 

Best regards,
Petar

**Closed** 2023-03-14 07:58 UTC
Labels: bug, Medium Prio, TOPIC RD
