### ISSUE TITLE
`<ui5-button>` Axe Issue: `<svg>` has `role="presentation"` but is not focusable

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3954] opened 2021-09-17 17:32 UTC
### **Bug Description**
This is a break out issue copy from https://github.com/SAP/ui5-webcomponents/issues/3933

#### 3. Elements of role none or presentation should be flagged

_custom shellbar icon buttons should have role="img" on the `<svg>` ?_

This one comes up for shellbar icon buttons `<svg>`, but not all of them just the custom ones. The search button and the account menu seem fine. This one complains that the role is "presentation" but it's not focusable (i.e. because tabindex=-1) but we know it's not supposed to be focusable because it's just the `<svg>` and it's a child of a `<button>` that is focusable so probably the role should not be "presentation" it should be "img" that seems to work for some other buttons in the same level.

This appears to be because the `<ui5-icon>` needs a effectiveAccessibleName somehow, and then the role becomes `img` instead of `presentation` - it is not clear yet precisely how that is set.

### **Expected Behavior**
The Shellbar should have no Axe issues

### **Steps to Reproduce**
See https://github.com/SAP/ui5-webcomponents/issues/3933

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by ilhan007** [comment] 2021-09-21 06:50
Hi @PetyaMarkovaBogdanova could you process this one as well

**Comment by PetyaMarkovaBogdanova** [comment] 2021-09-21 12:47
Hi @SAP/ui5-webcomponents-topic-p,
can you, please, check if the cofiguration of role="presentation"and a tabindex "-1" is causing the AXE error?

Kind regards,
Petya Markova.
(UI5 Developer)

**Comment by PetyaMarkovaBogdanova** [comment] 2021-09-21 13:00
The priority of the issue is not due to the severity of the issue, but because of the deadline for resolving it

**Closed** 2021-09-29 07:05 UTC
Labels: ACC, TOPIC P, SF, Very High Prio

**Comment by ilhan007** [comment] 2021-09-29 07:06
Hello @codefactor there is a fix, merged into the master, please wait for the next patch release. 
Once there is a new version released, we will update you.

**Comment by ilhan007** [comment] 2021-10-04 06:57
Hello @codefactor the issue has been resolved in 0.31.20
