### ISSUE TITLE
List component: When the list prop 'mode' is set to 'MultiSelect', on accessing the list items, the corresponding list title and the state ‘Selected’ is not read. 

### ISSUE THREAD

**Issue by kolew96** [SAP/ui5-webcomponents#3707] opened 2021-08-20 11:44 UTC
**Describe the bug**
When the list prop 'mode' is set to 'MultiSelect', on accessing the list items, the corresponding list title, item level of level count information and the state ‘Selected’ is not read. 

**To Reproduce**
1. Set the list prop 'mode' to 'MultiSelect'
2. Turn on the Narrator
3. Try to navigate to the any list item above level 1

**Observed behavior**
On accessing StandartListItem from a List, when list mode is set to multiselect, navigation focus the StandartListItem's button first, then after pressing Arrow down key, the StandartListItem's children text is read only

**Expected behavior**
On accessing StandartListItem from a List, when list mode is set to MultiSelect, navigation should focus the whole StandartListItem's and give the information about the corresponding list header, item level, item title, and state of UI (selected or not). 

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version: v0.15.3

**Context**
Browser (if relevant): {...} Chrome

**Additional context**
Label association issue, state of UI not read
--removed--

**Comment by unazko** [comment] 2021-08-20 15:25
Hello @kolew96,

Could you edit the following snipped:
https://codesandbox.io/s/strange-davinci-boc66?file=/src/index.js
so we could reproduce the issue.

Thank you,
Boyan

**Comment by dimitar-trendafilov** [comment] 2021-09-14 11:49
Hello @unazko 

https://codesandbox.io/s/currying-frost-fl0ys?file=/src/App.js

Here, this is edited snipped. Hope this helps.

BR,
Dimitar

**Comment by ilhan007** [comment] 2021-09-14 14:05
Hello @dimitar-trendafilov now @terezamch is the issue dispatcher from our side.
@terezamch could you please process the issue.

BR,
ilhan

**Comment by terezamch** [comment] 2021-09-17 14:05
Hello @kolew96 and @dimitar-trendafilov,

I have tested the scenario in the given example and in an isolated from React one - with ui5-list - https://codesandbox.io/s/headless-fog-pb0js?file=/index.html

I can distinguish only one concern - when a selected item is focused, the reader is not announcing that it is selected. For unselected items, the reader is stating that they are not selected. Could you please confirm that this is the thing that you are reporting?

Thanks,
Tereza

**Comment by ilhan007** [comment] 2021-09-20 08:26
Hello @dimitar-trendafilov could you take a look of the previous comment by @terezamch so we can continue processing the issue?

**Comment by dimitar-trendafilov** [comment] 2021-09-22 08:11
Hi @terezamch 

Yes, this is exactly the behavior which I have observed.

**Comment by ilhan007** [comment] 2021-09-27 07:17
Hello @SAP/ui5-webcomponents-topic-p could please take over? 

The selected state of the List Item is not announced by the screen reader. Although the author did not mentioned which tool has been used, the dispatcher from our side has tested the isolated example https://codesandbox.io/s/headless-fog-pb0js?file=/index.html and confirmed the issue, so I guess it is reproducible with Jaws.

BR,
ilhan

**Comment by nnaydenow** [comment] 2021-09-27 11:00
Hi @kolew96,

Could you please share which version of the project you are currently using?

Seems that the problem is fixed with #3952 and the fix will be available with the next version.

BR,
Nayden

**Comment by ilhan007** [comment] 2021-10-05 14:41
Hi @nnaydenow they are using older version - RC.15.

**Comment by ilhan007** [comment] 2021-10-05 14:43
Hello @kolew96 could you retest using an updated version of the reproducible sample https://codesandbox.io/s/magical-smoke-uqndt

The sample now loads the very latest development.

**Comment by ilhan007** [comment] 2021-11-29 07:26
Hello @kolew96 closing the issue due to inactivity. Feel free to provide more input as requested and we will re-open the issue.

**Closed by ilhan007** 2021-11-29 07:26 UTC
Labels: bug, ACC, High Prio, TOPIC P, CBC, author action
