### ISSUE TITLE
[Feature Request]: Support hide on scroll feature to ResponsivePopover

### ISSUE THREAD

**Issue by Lukewxg** [SAP/ui5-webcomponents#6829] opened 2023-03-30 04:57 UTC
### Feature Request Description

When ResponsivePopover mode=false, and the popover is displayed, we can click/tab outside of the popover to get it hide.
But there is no way to hide it when scrolling.
Now we got a issue: if there is some other floating panel which z-index is 120 for example, and click an none floating icon will display the popover, the the z-index will be > 120, and when scrolling, the popover will following icon to scroll. When icon scrolling behind the floating panel, the popover will following to the icon position, but because it's z-index is > 120, the popover will always be displayed at top of the page.
![image](https://user-images.githubusercontent.com/58862237/228733624-06f1e240-1602-4c1f-8f58-042fd6adf59f.png)

So it looks like the only solution is add a feature of hide popover on scrolling. 

### Proposed Solution

Add a feature of hide popover on scrolling. 

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Neeeko** [comment] 2023-06-26 22:47
FYI this also needs to be applied with `select` components
<img width="1290" alt="Screenshot 2023-06-26 at 3 44 45 PM" src="https://github.com/SAP/ui5-webcomponents/assets/7316793/2900d71e-523b-4de6-a54c-95009fd81609">

**Comment by alexandar-mitsev** [comment] 2023-09-15 11:47
Hello @Lukewxg , @Neeeko ,

After in depth analysis and further discussions we can not find a good option to resolve this issue. When there is a sticky header or a fixed header on top - there is no good, performant and reliable way in the browser to detect that the opener has gone outside of the visible area in this case.

This is browser limitation and can be observed across multiple technologies and in the native browser popovers as well.

The proposal to close the popover when scrolling was also considered and will be further reviewed by design team and architecture team. But so far it may not be applied in the near future because it will give inconsistent user experience and also can not solve the problem with popovers for Select, Date Picker and other input fields.

Therefore I am closing the issue as a browser limitation. We will get back to you if we have further solutions.

Thanks and Best Regards,
Alexandar Mitsev

**Closed by alexandar-mitsev** 2023-09-15 11:47 UTC
Labels: feature request, High Prio, TOPIC RD, Planned

**Comment by alexandar-mitsev** [comment] 2023-09-15 16:22
Additionally @Lukewxg - if you are in control of the z-indexes, you can put your header in z-index 2 and your content, if it includes the popover, in z-index 1 and you can solve the problem for this page.

**Comment by Lukewxg** [comment] 2023-10-10 04:29
Thanks @alexandar-mitsev , we can control header z-index, in fact we already set it to be 108, but we cannot control content z-index, it should be default. Will discuses within my team to see if we can try your suggestion.
