### ISSUE TITLE
ui5-icon: not support decorative mode

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2383] opened 2020-10-22 07:36 UTC
**Describe the bug**
WC icon doesn't support decorative mode.
For our cases, we don't want icon read out by screen reader.

**Expected behavior**
For UI5 Icon, the default property decorative is true, so it will be skipped by screen reader.
https://sapui5.hana.ondemand.com/#/api/sap.ui.core.Icon
Please also implement this attribute for WC Icon.

**Context**
- UI5 Web Components version: 0.23.2
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by fifoosid** [comment] 2020-10-27 09:20
Hi @GongRichard 

Could you provide the specific use case that you have. Are you using the ```ui5-icon``` as a standalone component or do you use it inside other component(like button for example)?

**Comment by GongRichard** [comment] 2020-10-27 09:41
Hi @fifoosid 

I use the ui5-icon as a standalone component.

1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. select a new satus 'low'

![2020-10-27_17-40-37](https://user-images.githubusercontent.com/13098801/97284121-9c76af80-187b-11eb-9c28-6afdc5cba629.jpg)

**Comment by nnaydenow** [comment] 2021-01-12 14:28
Internal reference: 4989

**Comment by PetyaMarkovaBogdanova** [comment] 2021-01-25 13:08
Hi @GongRichard ,
the UI5-Icon component in the application is not interactive, in means that it is not focusable or tabbable by the screan reader.
I managed to reproduce the extra speech on it with Virtual PC Cursor mode "on", because of the **accessibleName**
property, which attaches the "aria-label" on the HTML element of the icon.
Do you use this property for a specific reason?

**Comment by GongRichard** [comment] 2021-02-05 08:34
Hi @PetyaMarkovaBogdanova ,

This accessibleName property should be wrong, I will remove it later.

Thanks,
Richard

**Comment by PetyaMarkovaBogdanova** [comment] 2021-02-09 08:54
Hi @GongRichard,
please let me know if you still experience some issue with an extra speech triggered by the ui5-icon.

Thank you!
Petya Bogdanova.
(UI5 Developer)

**Comment by ilhan007** [comment] 2021-02-17 07:51
Hi @GongRichard I am closing the issue as a solution has been proposed. 
If you still face the issue, just comment below and we will reopen the issue.

**Closed by ilhan007** 2021-02-17 07:51 UTC
Labels: High Prio, Planned, SF, TOPIC P, approved, author action, feature request
