### ISSUE TITLE
[SF] ColorPalettePopover - "More Colors" option dialog buttons design and focus border

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#4976] opened 2022-03-29 09:17 UTC
### **Bug Description**
1. "More Colors" option dialog buttons should follow a similar design as the other standard dialog components. There are two buttons in the footer of the dialog - "OK" and "Cancel". "OK" should have the primary button style.
2. The edges of the border of the focus for the "Default color" and "More Colors" are slightly broken when using SAP Horizon theme

<img width="315" alt="Screen Shot 2022-03-29 at 2 13 29 AM" src="https://user-images.githubusercontent.com/36656306/160578166-ed485fcb-cade-4dca-b88d-4d0d7c2dc0d5.png">
<img width="220" alt="Screen Shot 2022-03-29 at 2 13 12 AM" src="https://user-images.githubusercontent.com/36656306/160578175-4de000d6-cf3d-47de-855e-df43efaa2f2b.png">
<img width="211" alt="Screen Shot 2022-03-29 at 2 13 00 AM" src="https://user-images.githubusercontent.com/36656306/160578177-191f64b4-8645-48af-8aa7-f15cc9ca0adf.png">

### **Expected Behavior**
The "OK" should have the primary button style in the dialog footer.
The border of the focused buttons should be smooth

<img width="321" alt="Screen Shot 2022-03-29 at 2 13 47 AM" src="https://user-images.githubusercontent.com/36656306/160578238-d1593c89-ea94-4929-9914-56efebae4b62.png">

### **Context**
- UI5 Web Components version: {1.2.1}

**Comment by tsanislavgatev** [comment] 2022-03-29 10:13
Hello colleagues,

The issue is reproducible in our test pages on chrome. This might be fixed with the latest button horizon updates, but needs to be checked after implementation or fixed separately.

Best Regards,
Tsanislav

**Closed** 2022-05-05 14:16 UTC
Labels: bug, Medium Prio, TOPIC B, SF
