### ISSUE TITLE
[SF][ui5-textarea | horizon]: textarea component does not have bottom border when value-state is set as "None"

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#6746] opened 2023-03-21 03:46 UTC
### Bug Description

In horizon theme, when `ui5-textarea` has `value-state="None"` defined, the bottom-border is not shown as expected.

### Affected Component

ui5-textarea

### Expected Behaviour

The bottom border should be displayed when `value-state` is `None`

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-8j0woe

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/playground/components/TextArea/
2. Open developer tools and find any `ui5-textarea` component in sample page
3. Add `value-state="None"` in the `ui5-textarea` tag as attribute
4. Bottom border will disappear

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment] 2023-03-21 09:53
Hello @SAP/ui5-webcomponents-topic-rl,

In Horizon theme, the ui5-textarea does not render border correctly if value-state="None" is set. The issue is reproducible on the playground page https://sap.github.io/ui5-webcomponents/playground/components/TextArea/ as described above.
Could you please take a look at this?

Best regards,
Siyana

**Comment by niyap** [comment] 2023-03-28 04:36
Hello @zhangliangyi,

The issue is fixed with the following PR #6804

**Closed by niyap** 2023-03-28 04:36 UTC
Labels: bug, Medium Prio, TOPIC RL, SF
