### ISSUE TITLE
Input: onInput fires previous value for type number and causes form validation issues.

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5173] opened 2022-05-04 18:02 UTC
### **Bug Description**
If you use a input field with type="Number" and listen for onInput events, you will get the wrong (previous is fired) value, when you mark the numbers with double click and press delete on the keyboard.

### **Expected Behavior**
If I delete the value of an input via keyboard delete button, the onInput must give me an empty string or I´ll have several form validation errors.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/blissful-germain-m65r5j?file=/src/App.js
2. Type numbers in the input field
3. Mark the numbers with double mouse click
4. Press delete on the keyboard
5. Open the console and see, that the numbers you deleted are printed but thats not correct.

### **Isolated Example**
https://codesandbox.io/s/blissful-germain-m65r5j?file=/src/App.js

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/44802503/166752390-992eec4e-c15c-4b53-84c4-499655c59eb1.png)
![image](https://user-images.githubusercontent.com/44802503/166753080-e75c3794-aa32-426e-b854-7932160e5838.png)
![image](https://user-images.githubusercontent.com/44802503/166763138-7003b50d-2741-404e-8561-f74a223f8d69.png)
![image](https://user-images.githubusercontent.com/44802503/166754054-54babd9a-60cf-4a8c-9fc7-c04bce1a93a2.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by IlianaB** [comment] 2022-05-05 06:32
Hello @ui5-webcomponents-topic-rl I am forwarding this issue to you, because deleting the value of the Input with Delete keyboard button does not work as expected - instead of an empty string, it gives the old value.

Could you have a look?

Best regards,
Iliana

**Comment by ivoplashkov** [comment] 2022-05-25 11:48
Hello,

Thank you for reporting this issue!

This issue seems to be no longer reproducible. 
The console log is an empty string as expected after deleting the input value, therefore I am closing the issue.

Best regards,
Ivaylo

**Closed by ivoplashkov** 2022-05-25 11:48 UTC
Labels: bug, Medium Prio, TOPIC RL
