### ISSUE TITLE
[InvisibleMessage]: InvisibleMessage.announce does not work when a dialog is open

### ISSUE THREAD

**Issue by swendlandt** [SAP/ui5-webcomponents#9670] opened 2024-08-09 15:53 UTC
### Bug Description

The method `InvisibleMessage.announce` as described [here](https://sap.github.io/ui5-webcomponents/docs/advanced/accessibility/#invisible-messaging) does not work when a `ui5-dialog` is open.

Check the isolated example https://stackblitz.com/edit/js-pbklwm?file=index.js,index.html,package.json 
1. Click on the "Announce Text" button -> Text will be announced by the screenreader
2. Click on the "Open Dialog" button and then on the "Announce Text" button -> text will not be announced by the screenreader

Tested with Chrome on MacOS and VoiceOver

### Affected Component

InvisibleMessage

### Expected Behaviour

If I call `InvisibleMessage.announce` the text should be announced, regardless if a dialog is currently open or not

### Isolated Example

https://stackblitz.com/edit/js-pbklwm?file=index.js,index.html,package.json

### Steps to Reproduce

Check the isolated example https://stackblitz.com/edit/js-pbklwm?file=index.js,index.html,package.json 
1. Click on the "Announce Text" button -> Text will be announced by the screenreader
2. Click on the "Open Dialog" button and then on the "Announce Text" button -> text will not be announced by the screenreader

### Priority

Medium

### UI5 Web Components Version

2.1.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment] 2024-08-15 14:04
Hello @swendlandt ,

Thank you for reporting the issue. I  am the accessibility expert of the team owning the InvisibleMessaging service.
I did some analysis of the issue and I the results are that the issue is a VoiceOver related one, not a ui5 web component specific problem.

The issue is not reproducible with JAWS 2024 + Chrome latest and NVDA + Chrome latest, so this is rather a lack of screen reader support for Voice Over + Chrome and has nothing to do with an issue with the coding of the UI5 web components.

As suggested here our recommended testing environment is Chrome + JAWS 2024 as it shows the best support of ARIA and WCAG standards.
Please read more about testing components for accessibility here:
https://sap.github.io/ui5-webcomponents/nightly/docs/advanced/accessibility/

I would suggest that you could raise an issue to VoiceOver. As there is no bug in the web components project I am closing the issue.

Kind Regards,
Elena

**Closed by elenastoyanovaa** 2024-08-15 14:04 UTC
Labels: bug, ACC, Medium Prio, TOPIC RL
