### ISSUE TITLE
[component name | framework | build | icons | theming | localization | i18n | typescript]:List

### ISSUE THREAD

**Issue by Garima123639** [SAP/ui5-webcomponents#10232] opened 2024-11-21 15:34 UTC
### Bug Description

When loading is set to true for <List> component , it gives grey background with busy indicator in version 2.3.0 as compared to version 1 where the background color was not changing by giving the busy attribute in version 1.20.0

### Affected Component

List

### Expected Behaviour

Background should not change to grey color but should be same behaviour as that of previous version 1.20.0

### Steps to Reproduce

1. Use the List component with loading attribute set to true
2. Compare it with older version where busy attribute was used instead of loading
3.
...

### Priority

None

### UI5 Web Components Version

2.3.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment] 2024-11-22 09:28
Hello @Garima123639,

The behavior of the loading (or busy) state in version 2.3.0 is working as intended. The introduction of the grey background alongside the busy indicator is a design enhancement aimed at improving usability.

The behavior in version 1.20.0, where the background color remained unchanged, was a wrongfully used parameter which was fixed by the following change - https://github.com/SAP/ui5-webcomponents/pull/9233

Best regards,
Ivaylo

**Closed by ivoplashkov** 2024-11-22 09:28 UTC
Labels: bug
