### ISSUE TITLE
[SF][Dialog][A11y]: The content is announced twice by screen reader (0.31.x)

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3778] opened 2021-08-23 01:34 UTC
**Describe the bug**
When adding the aria-label for the message box, the aria-label is announced twice.

**Isolated Example**

**To Reproduce**

**Expected behavior**
The aria-label is only announced once by the screen reader.

**Screenshots**
![image](https://user-images.githubusercontent.com/1614528/130378204-f207cfb8-c03b-440a-9d85-d3f91c844942.png)
![image](https://user-images.githubusercontent.com/1614528/130378224-5fd5f5f7-188f-4064-9cac-7a7966659733.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.31.15
`@ui5/webcomponents-react` version: 0.131.15
Operating System: macOS BigSur
Browser: Version 92.0.4515.159 (Official Build) (x86_64)

**Additional context**

**Comment by sfsf-xweb-sh** [comment] 2021-09-06 06:54
Hi @Lukas742 
I am from SuccessFactors Web Experience Shanghai team.

Our team is only allowed to use the SF version of ui5-webcomponent.
We can not use rc version of ui5-webcomponent.

If this issue is fixed in 1.0.0-rc.15. Can you please downport this feature to 0.31.x ? ( The current version is 0.31.16, maybe you can release 0.31.17 )

**Comment by Lukas742** [comment] 2021-09-06 07:18
Hi @sfsf-xweb-sh 

I'm part of the UI5 Web Components for React team, so I'm not responsible for releasing versions of the UI5 Web Components. That's why I transferred this issue and added a comment explaining what probably the root cause is here.

**Comment by TeodorTaushanov** [comment] 2021-09-14 11:15
Hi @ericchan1983,

Can you provide us an example of your ui5-dialog, where the issue is reproducible?

You can edit:
https://codesandbox.io/s/ui5-webcomponents-forked-xtrox?file=/index.html:300-317

Best,
Teo

**Comment by ericchan1983** [comment] 2021-09-16 02:44
Hi @TeodorTaushanov,

https://codesandbox.io/s/ui5-webcomponents-forked-xtrox?file=/index.html:300-317
![image](https://user-images.githubusercontent.com/1614528/133540946-e6d22d10-19bb-4be5-a50b-3d96a25a8623.png)

In the example you provided, there are two aria-labels for the UI5-dialog.

Regards,
Eric Chen

**Comment by ericchan1983** [comment] 2021-09-23 05:27
Hi @TeodorTaushanov，

The PopOver has the same issue which screen reader announced the aira-label twice.
Could you also have a look at it, please?

Regards,
Eric Chen

**Comment by ilhan007** [comment] 2021-09-27 07:09
Hello @ericchan1983 
we have merged a fix for the Dialog, that will be released with the next patch - in few days.

Can you please open a separate issue for the Popover with reproducible example and details.

Thanks!

**Closed by ilhan007** 2021-09-27 07:09 UTC
Labels: bug, ACC, TOPIC RD, SF, author action, Very High Prio

**Comment by ilhan007** [comment] 2021-10-04 06:54
Resolved with 0.31.20
