### ISSUE TITLE
[MultiComboBox]: Token Deletion is not possible for  long text

### ISSUE THREAD

**Issue by niriksha02** [SAP/ui5-webcomponents#7393] opened 2023-08-01 05:00 UTC
### Bug Description

Steps:

1. Go to https://codesandbox.io/s/angry-golick-r6tmzq?file=/src/App.js
2. select first 2 options from dropdown menu
   
<img width="356" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/62610635/49124644-314f-4228-a0e1-9a24e2675bd1">

3. On clicking 'X' for deletion, its not getting deleted, rather its getting selected.

![image](https://github.com/SAP/ui5-webcomponents/assets/62610635/8e3fcb72-d08d-4c55-868f-9f1a7be938fc)

### Affected Component

MultiComboBox

### Expected Behaviour

The token to be deleted after clicking 'X'.

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment] 2023-08-01 08:21
Hello @niriksha02 

The issue is fixed in the latest version as shown in: https://codesandbox.io/s/loving-easley-7zsr65?file=/index.html

Best Regards,
Martin

**Closed by MapTo0** 2023-08-01 08:21 UTC
Labels: bug
