### ISSUE TITLE
[SF][Label] text is truncated with show-colon

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3980] opened 2021-09-23 08:28 UTC
### **Bug Description**
Label text is truncated if show colon is set true

### **Expected Behavior**
Label text should not be truncated if it is not exceeds the container

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-xt2px?file=/src/index.js
2. Check the label

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-xt2px?file=/src/index.js

### **Context**
- UI5 Web Components version: 0.31.18
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-label

### **Log Output / Stack Trace / Screenshots**
<img width="427" alt="Screen Shot 2021-09-23 at 4 26 56 PM" src="https://user-images.githubusercontent.com/1751846/134476314-dc9de5e7-4c1c-4868-ae42-e4bdc41dbbdf.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment] 2021-09-23 12:45
Hi colleagues from @SAP/ui5-webcomponents-topic-rd ,
can you, please, take a look at this issue?

Kind regards,
Petya Markova.
(UI5 Developer)

**Comment by ilhan007** [comment] 2021-09-23 12:51
Hi @SAP/ui5-webcomponents-topic-rd, keep in mind that this might be already fixed in the master, so this is the first thing to check - if the issue is reproducible in the master. If not - look for a fix that is already merged in the master,  but not downported to 0.31 (I remember that some fixes related to the Label text truncation  have been recently merged).
If this is the case, just contact me and i will downport the required change.

**Comment by ilhan007** [comment] 2021-09-24 09:19
Fixed in 0.31.19

**Closed by ilhan007** 2021-09-24 09:19 UTC
Labels: bug, TOPIC RD, SF, Very High Prio
