### ISSUE TITLE
[SF][IllustratedMessage]: NoEntries subtitle text missing single quote in British English

### ISSUE THREAD

**Issue by summer2200** [SAP/ui5-webcomponents#9082] opened 2024-05-29 09:06 UTC
### Describe the bug

After switching language to British English, NoEntries IllustratedMessage's subtitle missed one single quote.
<img width="1138" alt="Screenshot 2024-05-29 at 17 02 25" src="https://github.com/SAP/ui5-webcomponents-react/assets/18187036/26c82281-a3ba-4235-afd5-f4bb214340d8">

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-illustratedmessage--docs&globals=language:en_GB

### Reproduction steps

1. Open the link, set illustrated message name to "NoEntries"
2. Select "British English" in language picker
3. See the subtitle

### Expected Behaviour

Subtitle should be "..., you'll ..."

### UI5 Web Components for React Version

1.28.4

### UI5 Web Components Version

1.24.3

### Browser

Chrome

### Operating System

macOS Sonoma 14.3.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment] 2024-05-30 07:29
Hello @SAP/ui5-webcomponents-topic-p,

The problem is that in the **en_GB** translation file (probably in some others too), the single quote/apostrophe is not escaped as is in the original message bundle file.

The escape can be done by inserting another single quote next to it, or write down the unicode (\u2019) for the single quote instead of it.

My guess is that the issue should be forwarded to the translation team.

Could you please look into it?

Regards,
Plamen Ivanov

**Comment by plamenivanov91** [comment] 2024-06-06 14:25
Hello @summer2200 ,

There is an internal ticket DINC0147183 where the issue is being currently resolved.

Regards,
Plamen Ivanov

**Comment by ilhan007** [comment] 2024-07-26 12:16
Hello @summer2200 

the issue has been fixed for some time already in 2.0, we have down-ported it to 1.24, which our maintenance version (until the end of the year) and you can expect a new patch 1.24.8 coming by the end of next week

FYI
Every start of the month we release  minor versions for version 2 - 2.1.0, 2.2.0 and patches for version 1.24 - 1.24.8, 1.24.9 and so on.

I will close the issue once the patch is released.

Regards,
ilhan

**Closed** 2024-08-08 17:38 UTC
Labels: bug, Medium Prio, TOPIC P, SF_ACC
