### ISSUE TITLE
Listitem in emulator: TypeError: this._onmousedown is not a function

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5154] opened 2022-04-29 13:48 UTC
**Describe the bug**
In mobile view if you touch on a Listitem in a List, you get the following error:
![image](https://user-images.githubusercontent.com/44802503/165956832-1c305a2a-3dea-427c-9389-7257a92a15f9.png)

**Isolated Example**
https://codesandbox.io/s/btmlmv?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/btmlmv?file=/src/App.js
2. Open the browser in emulator mode with touchsupport.
3. Touchclick on the StandardlistItem
4. Open console
5. See error

**Expected behavior**
No error.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by niyap** [comment] 2022-05-02 07:24
Hello @SAP/ui5-webcomponents-topic-p,

Could you please look over the issue?
I managed to reproduced in in our sample page using iOS Simulator.

Kind Regards,
Niya

**Comment by nnaydenow** [comment] 2022-05-03 16:21
Hi @C3ntraX, 

Issue will be fixed with: #5153

Regards,
Nayden

**Comment by ilhan007** [comment] 2022-05-11 10:18
@nnaydenow https://github.com/SAP/ui5-webcomponents/pull/5153 is merged, check and close the issue if no longer exists.

**Comment by nnaydenow** [comment] 2022-05-11 10:33
Hi @C3ntraX,

The issue seems to be fixed with #5153.

Regards,
Nayden

**Closed by nnaydenow** 2022-05-11 10:33 UTC
Labels: bug, Medium Prio, TOPIC P
