### ISSUE TITLE
[Popover]: Popover example is not updated when properties are changed

### ISSUE THREAD

**Issue by swendlandt** [SAP/ui5-webcomponents#8041] opened 2023-12-28 17:03 UTC
### Bug Description

Under https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-popover--docs when you change any properties in the table the example is not updated, it just stays the same.

Compare with e.g. Button: https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-button--docs. When you change any property, e.g. the button text, the component gets rerendered immediately and the changes are reflected.

### Affected Component

Popover

### Expected Behaviour

When you change properties the changes should be reflected in the example like for other components.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-popover--docs

### Steps to Reproduce

1. Go https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-popover--docs
2. Change headerText property in the table.
3. Change is not visible in the UI.

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment] 2024-01-05 12:42
Hello colleagues,

The issue is reproducible as described by the author.
Could you please have a look?

Best regards,
Ivaylo

**Comment by s-todorova** [comment] 2024-01-17 14:13
Hi @swendlandt,

The issue is caused by the way Storybook handles the control updates when examples are rendered inside an iframe. It is a limitation we have no control over - refer to the [note](https://storybook.js.org/docs/api/doc-block-story#story) below `inline` property from the official Storybook documentation. 

As is mentioned there, this is a known limitation of the current implementation and will be addressed in a future release.
Therefore, I am closing the ticket as nothing can be done from our side until Storybook fixes the issue.

Best regards,
Siyana

**Closed by s-todorova** 2024-01-17 14:13 UTC
Labels: bug, documentation, TOPIC RD, Storybook
