### ISSUE TITLE
ui5-dialog: When dialogs are open, the background elements are visible through JAWS quick navigation keys

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2386] opened 2020-10-22 08:18 UTC
**Describe the bug**
When dialogs are open, the background elements are visible through JAWS quick navigation keys.

**To reproduce**

1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. With JAWS ON,  Press JAWS quick navigation keys such as INSERT+CNTl+B

**Actual Results**
Observe the buttons from the background is getting included in the quick navigation list. When background contents are available in navigation list screen reader users may assume the contents are from modal dialog window.

**Expected behavior**
 The background content should always be hidden from screen readers until the dialog is closed.

**Screenshots**
![Background contents in quick navigation list (1)](https://user-images.githubusercontent.com/13098801/96844232-d9a8ff00-1481-11eb-9f22-cd4b0af895c8.png)

**As there has ui5-static-area tag under body, is it possible to put dialog content there? Then it could fix this issue.**

**Context**
- UI5 Web Components version: 0.23.2
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by ilhan007** [comment] 2021-01-04 13:06
Hello @SAP/ui5-webcomponents-topic-rd could you look into the issue?

**Comment by GerganaKremenska** [comment] 2021-01-13 06:54
Hello @GongRichard,

This is not an issue with Dialogs, but with JAWS.
Our dialogs are implemented following aria-1.1  best practices.
The issue is found in in the [aria best practice](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) example.

NOTE: Buttons which are visible on the background, they are only visible they can not be accessed through the quick navigation list. [Issue](https://github.com/FreedomScientific/VFO-standards-support/issues/179) is reported to Freedom Scientific.

Best Regards,
Gergana

**Comment by ilhan007** [comment] 2021-01-20 08:02
Hello @SAP/ui5-webcomponents-topic-rd the author contacted us today. For some reason @GongRichard currently can't reopen and comment, so I am forwarding the reply by his A11Y team.

"When dialog box is open, screen reader user is able to access buttons and functionality. Please find the attached recording. Background page buttons are visible as well as accessible. Users should not be able to interact with content outside an active dialog window.

```html
<section role="dialog" class="ui5-popup-root" aria-modal="true" aria-labelledby="ui5-popup-header" dir="ltr" style=""><span class="first-fe" data-ui5-focus-trap="" tabindex="0">
```
Note: aria-modal=true is used to tell assistive technologies that the windows underneath the current dialog are not available for interaction. But this is not working so aria-hidden can be used."


https://user-images.githubusercontent.com/15702139/105144780-6bb6b700-5b06-11eb-8ffc-780c2383c1e8.mp4

**Comment by GerganaKremenska** [comment] 2021-01-26 14:09
Hello @GongRichard,

Which version of JAWS are you using and browser?

I am with latest chrome and JAWS 2019 and buttons which are visible on the background, they are only visible they can not be accessed through the quick navigation list. 

As i said the  [Issue](https://github.com/FreedomScientific/VFO-standards-support/issues/179) is reported to Freedom Scientific and we can not influence the vendor. This is not an issue with the ui5-dialog. 
I am closing the issue as we have no action.

Best Regards,
Gergana

**Closed by GerganaKremenska** 2021-01-26 14:09 UTC
Labels: ACC, High Prio, SF, TOPIC RD

**Comment by GongRichard** [comment] 2021-02-01 04:48
@GerganaKremenska  this was tested by SF A11Y quality team. What's your sap internal email address? I send email to you and our SF QA.

**Comment by GongRichard** [comment] 2021-02-25 09:53
@GerganaKremenska and @ilhan007  this was tested by SF A11Y quality team. What's your sap internal email address? I send email to you and our SF QA.

**Comment by ilhan007** [comment] 2021-02-25 10:00
Hi @GongRichard this turns out to be a[ Jaws issue](https://github.com/FreedomScientific/VFO-standards-support/issues/179), as explained above. Nevertheless, here is my email: ilhan.myumyun@sap.com
