### ISSUE TITLE
NotificationList: Focus does not move as expected when virtual cursor is on

### ISSUE THREAD

**Issue by alexandar-mitsev** [SAP/ui5-webcomponents#9554] opened 2024-07-25 11:39 UTC
### Bug Description

If the Jaws virtual cursor is ON (default) the focus in the notification list does not move as expected.
Pressing the arrow down key will not move the focus to the next item. It only moves the virtual cursor inside the notification list item.

### Affected Component

ui5-notification-list

### Expected Behaviour

Pressing arrow down should focus the next item. This is also how it works in ui5-list

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/components/fiori/NotificationList/

### Steps to Reproduce

1. Open Jaws with virtual cursor on (default)
2. Focus the first notification item
3. Press arrow down
4. Focus stays on place, only virtual cursor moves
...

### Priority

Medium

### UI5 Web Components Version

Nightly

### Browser

Chrome

### Operating System

Windows

### Organization

UI5

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment] 2024-08-20 07:30
Hello @alexandar-mitsev, 

The issue is not reproducable with latest version of JAWS 2024 (2406).
I am closing the issues.

Best Regards,
Gergana

**Closed by GerganaKremenska** 2024-08-20 07:29 UTC
Labels: bug, ACC, Medium Prio, TOPIC RD
