### ISSUE TITLE
[ResponsivePopover] Popover close event is called when menu inside the popover is closed

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#10041] opened 2024-10-16 20:58 UTC
### Bug Description

When you have a ResponsivePopover and a Menu component inside it, and you close the menu component, the "close" event of the ResponsivePopover is triggered.

Sandbox - 

[sandbox](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDMwMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuXG4gICAgPHVpNS1idXR0b24gaWQ9XCJidG5cIj5PcGVuIFJlc3BvbnNpdmVQb3BvdmVyPC91aTUtYnV0dG9uPlxuXG4gICAgPHVpNS1yZXNwb25zaXZlLXBvcG92ZXIgb3BlbmVyPVwiYnRuXCIgaGVhZGVyLXRleHQ9XCJOZXdzbGV0dGVyIHN1YnNjcmlwdGlvblwiPlxuIFxuICAgICAgICA8ZGl2IGNsYXNzPVwicG9wb3Zlci1jb250ZW50XCI-XG4gICAgICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImJ0bk9wZW5CYXNpY1wiIGVuZC1pY29uPVwic2xpbS1hcnJvdy1kb3duXCI-T3BlbiBNZW51PC91aTUtYnV0dG9uPiA8YnI-XG5cbiAgICA8dWk1LW1lbnUgaGVhZGVyLXRleHQ9XCJCYXNpYyBNZW51IHdpdGggSXRlbXNcIiBpZD1cIm1lbnVCYXNpY1wiIG9wZW5lcj1cImJ0bk9wZW5CYXNpY1wiPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiTmV3IEZpbGVcIiBpY29uPVwiYWRkLWRvY3VtZW50XCI-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiTmV3IEZvbGRlclwiIGljb249XCJhZGQtZm9sZGVyXCIgZGlzYWJsZWQ-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtc2VwYXJhdG9yPjwvdWk1LW1lbnUtc2VwYXJhdG9yPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiT3BlblwiIGljb249XCJvcGVuLWZvbGRlclwiPjwvdWk1LW1lbnUtaXRlbT5cbiAgICAgICAgPHVpNS1tZW51LWl0ZW0gdGV4dD1cIkNsb3NlXCI-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtc2VwYXJhdG9yPjwvdWk1LW1lbnUtc2VwYXJhdG9yPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiUHJlZmVyZW5jZXNcIiBpY29uPVwiYWN0aW9uLXNldHRpbmdzXCI-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiRXhpdFwiIGljb249XCJqb3VybmV5LWFycml2ZVwiPjwvdWk1LW1lbnUtaXRlbT5cbiAgICA8L3VpNS1tZW51PlxuICAgICAgICA8L2Rpdj5cblxuICAgICAgICA8ZGl2IHNsb3Q9XCJmb290ZXJcIiBjbGFzcz1cInBvcG92ZXItZm9vdGVyXCI-XG4gICAgICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImNsb3NlUG9wb3ZlckJ1dHRvblwiIGRlc2lnbj1cIkVtcGhhc2l6ZWRcIj5TdWJzY3JpYmU8L3VpNS1idXR0b24-XG4gICAgICAgIDwvZGl2PlxuXG4gICAgPC91aTUtcmVzcG9uc2l2ZS1wb3BvdmVyPlxuXG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9SZXNwb25zaXZlUG9wb3Zlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MYWJlbC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvSW5wdXQuanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTWVudS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTWVudUl0ZW0uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L01lbnVTZXBhcmF0b3IuanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvYWRkLWRvY3VtZW50LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hZGQtZm9sZGVyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9vcGVuLWZvbGRlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3Qvc2F2ZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvdXBsb2FkLXRvLWNsb3VkLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hY3Rpb24tc2V0dGluZ3MuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2pvdXJuZXktYXJyaXZlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9zbGltLWFycm93LWRvd24uanNcIjtcblxuY29uc3QgYnRuT3BlbkJhc2ljID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJidG5PcGVuQmFzaWNcIik7XG5jb25zdCBtZW51QmFzaWMgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcIm1lbnVCYXNpY1wiKTtcblxuYnRuT3BlbkJhc2ljLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCBmdW5jdGlvbihldmVudCkge1xuICAgIG1lbnVCYXNpYy5vcGVuID0gIW1lbnVCYXNpYy5vcGVuO1xufSk7XG5cbmNvbnN0IGJ0biA9IFsuLi5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZShcInVpNS1idXR0b25cIildWzBdO1xuY29uc3QgcmVzcFBvcG92ZXIgPSBbLi4uZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJ1aTUtcmVzcG9uc2l2ZS1wb3BvdmVyXCIpXVswXTtcblxuYnRuLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG5cdHJlc3BQb3BvdmVyLm9wZW4gPSAhcmVzcFBvcG92ZXIub3Blbjtcbn0pO1xuXG5yZXNwUG9wb3Zlci5hZGRFdmVudExpc3RlbmVyKFwiY2xvc2VcIiwgKCkgPT4ge1xuICByZXNwUG9wb3Zlci5vcGVuID0gZmFsc2U7XG59KTtcbiJ9fQ)

### Affected Component

ResponsivePopover

### Expected Behaviour

The close event should not be triggered

### Steps to Reproduce

1. Open the responsive popover
2. Open the menu inside it
3. Close the menu by either clicking a menu item or clicking outside the menu
...

### Priority

High

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment] 2024-10-17 06:56
Hi @Vir-Mittal ,
thank you for sharing your finding, and for the example that you have prepared.
It seems that the problem is this code 
`respPopover.addEventListener("close", () => {
  respPopover.open = false;
});`
Do you need to add it in this case?
Thank you!
Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by Vir-Mittal** [comment] 2024-10-29 18:14
Hi @PetyaMarkovaBogdanova @ilhan007 is there any update on this issue about when it is expected to be fixed? It is blocking us from upgrading to wc 2.0 and we will have to rollback to an old version if the fix will take time

**Comment by ilhan007** [comment] 2024-11-04 12:10
Will be soon resolved with this change
https://github.com/SAP/ui5-webcomponents/pull/10133

**Closed** 2024-11-06 08:21 UTC
Labels: bug, SAP SF
