### ISSUE TITLE
[icons]: update SAP-icons to v5.9 & v4.21

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#9549] opened 2024-07-24 06:26 UTC
### Feature Request Description

Adopt SAP icons (@ui5/webcomponents-icons) v5.9 & v4.21

### Proposed Solution

n/a

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment] 2024-07-25 05:33
There is problem with the naming of the icons in version 5.9 of sap icons font. The issue is reported to the designers and marking it as blocked until it is fixed.

**Comment by nnaydenow** [comment] 2024-07-30 12:53
Fixed with: https://github.com/SAP/ui5-webcomponents/pull/9563

**Closed by nnaydenow** 2024-07-30 12:53 UTC
Labels: enhancement, Blocked, TOPIC Core
