### ISSUE TITLE
[SF][UploadCollection]: No data description doesn't wrap in 0.31.18 

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3975] opened 2021-09-22 08:12 UTC
### **Bug Description**
The no data description is shown in one line rather than multiple lines as the screenshot shown.
Since the wrappingType="Normal" doesn't work on this version but the "wrap" works.

### **Expected Behavior**
A clear and concise description of what you expect to happen.

### **Steps to Reproduce**
2. ...
3. ...

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 0.31.18
- OS/Platform: macOs BigSur 11.6
- Browser: Google Chrome Version 93.0.4577.82 (Official Build) (x86_64)
- Affected component: ui5-upload-collection, UploadCollection

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/1614528/134306391-d6052cf3-5cb2-4629-bbf4-d008d1c211c8.png)
![image](https://user-images.githubusercontent.com/1614528/134306622-91237508-fb24-48db-9bdb-a030770bfdb0.png)

{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment] 2021-09-23 06:18
Hi colleagues from @SAP/ui5-webcomponents-topic-rd,
can you review if we can downport wrappingType functionality for label in 0.31 rather update the documentation
with clear information since which version the property can be used?
Thank you!
Kind regards,
Petya Markova.
(UI5 Developer)

**Comment by ilhan007** [comment] 2021-09-23 06:55
Hi @SAP/ui5-webcomponents-topic-rd colleagues, I will handle this issue.

**Comment by ilhan007** [comment] 2021-09-23 07:37
Hello @ericchan1983 
the issue is handled with the following [change](https://github.com/SAP/ui5-webcomponents/commit/289836e0d3070529957e44cef29d7a6ee4fb4ca7)

The issue will be resolved with the next patch.

**Closed by ilhan007** 2021-09-23 07:37 UTC
Labels: TOPIC RD, SF, Very High Prio
