### ISSUE TITLE
`dist/custom-elements.json` files do not exist

### ISSUE THREAD

**Issue by niklasvieth** [SAP/ui5-webcomponents#6348] opened 2023-01-24 10:14 UTC
### **Bug Description**
The `custom-elements.json` files are not included in the /dist folder but referenced in the `package.json` as `customElements": "./dist/custom-elements.json"`

Maybe see
https://github.com/SAP/ui5-webcomponents/blob/462542b91c76483f82a37af19ad069bb65a7c5bf/packages/tools/lib/generate-custom-elements-manifest/index.js#L367

### **Expected Behavior**
Both packages `@ui5/webcomponents` and `@ui5/webcomponents-fiori` should include a dist/custom-elements.json file.

### **Steps to Reproduce**
1. Go to https://www.npmjs.com/package/@ui5/webcomponents?activeTab=explore  -> `@ui5/webcomponents/dist` 
2. Go to https://www.npmjs.com/package/@ui5/webcomponents-fiori?activeTab=explore -> `@ui5/webcomponents-fiori/dist`

### **Context**
- UI5 Web Components version: `1.10.0` 
- OS/Platform: Mac OS
- Browser: Chrome
- Affected component: `@ui5/webcomponents` and `@ui5/webcomponents-fiori` 

### **Priority**
- [x] Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Consulting

**Comment by kskondov** [comment] 2023-01-24 10:59
Hello @SAP/ui5-webcomponents-topic-core,

Can you please take over and give you input if this is the desired behaviour?

Best Regards,
Konstantin

**Comment by nnaydenow** [comment] 2023-01-25 12:43
Hi,

The issue is fixed with #6352

**Closed by nnaydenow** 2023-01-25 12:43 UTC
Labels: bug, TOPIC Core
