### ISSUE TITLE
ui5-datePicker: Error message does not show up on focusing date picker

### ISSUE THREAD

**Issue by Ankitadoshi** [SAP/ui5-webcomponents#2781] opened 2021-02-04 13:24 UTC
**Describe the bug**
When we have a ui5-datePicker which has error value state, and we set the focus to it programmatically, the date picker is focused but the error message does not show up.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-hvewu
2. In the preview, in datePicker, enter some invalid value 'foo'
3. Focus out from it and observe that the date picker has error value state
4. click on the 'Focus DatePicker' button
5. Observe that the date picker is focused but does not show up the 'invalid entry' error message.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-hvewu

**Expected behavior**
The error message 'Invalid entry' should show up when we focus the date picker. 

**Affected components** *(if known)*
ui5-datepicker

**Organization:** *(if applicable)*
Successfactors

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*
The error message will not be visible to users even when the date picker is focused

**Comment by vladitasev** [comment] 2021-02-08 09:06
Please analyze the issue and tell whether this is an Input bug or a DatePicker bug.

**Comment by ilhan007** [comment] 2021-02-08 09:49
Hello @SAP/ui5-webcomponents-topic-rl could you investigate this issue. 

The behaviour is discovered for the DatePicker, but is reproducible with the Input.  If you programatically call focus() on the Input, the cursor moves to the input field, bot neither the focus outline shows, nor the value state message.

- Go to https://codesandbox.io/s/ui5-webcomponents-forked-w86jd?file=/index.html
(this a slightly changed example - I replaced the ui5-datepicker with ui5-input)
- Click on the 'Focus DatePicker' button
- Observe that the input is focused but does not show up the 'invalid entry' error message.

BR, ilhan

**Comment by vladitasev** [comment] 2021-02-08 09:51
@MapTo0 Should this be fixed on Input level, Marti? What do you think?

**Comment by tsanislavgatev** [comment] 2021-02-11 09:09
Changing the label to notify @SAP/ui5-webcomponents-topic-rl .

**Comment by Martotko** [comment] 2021-02-22 08:07
Hi, 

I'm changing the priority to medium because the issue is not a common use case and is not reproducible every time in a local environment.

Best regards,
Martin

**Comment by fifoosid** [comment] 2021-02-26 10:32
Hi everyone,

This issue is already resolved in master branch and it is released in RC12.

**Closed by fifoosid** 2021-02-26 10:32 UTC
Labels: Medium Prio, SF, TOPIC RL, bug
