### ISSUE TITLE
ShellBar: Tooltip for profile icon does not display the profile name

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5047] opened 2022-04-12 07:06 UTC
Bug: On hovering over the profile icon in shellbar react component, default text 'Profile' is displayed always. Ideally, the name/title of the profile should be shown.

The issue can be reproduced even for the sample given in react components wiki(https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-shellbar--default-story) . Hover over the profile icon and tooltip with 'Profile' text is shown.
![shellbar](https://user-images.githubusercontent.com/90389521/162896148-5faddf9b-bb33-4eaf-ab08-7852a43d8536.jpg)

This issue persist even if we set the 'accessibilityTexts' property of ShellBar (eg: accessibilityTexts={{ profileButtonTitle: 'abc' }}) 
or if we pass the name /title property in avatar component.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.15.2
Operating System:Windows
Browser: Chrome

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment] 2022-04-12 07:58
I just noticed that is actually already possible to set a custom title by using the `accessibilityTexts`. 

@PriyaPowar you can find an example how to do this with UI5 Web Components for React here:
https://codesandbox.io/s/wandering-https-eqglql?file=/src/App.js

**Comment by stbodurov** [comment] 2022-04-15 06:55
Hello @PriyaPowar,

Closing the issue as it's no longer reproducible since @ui5/webcomponents v1.1.0 and v0.21.0 of @ui5/webcomponents-react.

You can learn more about `accessibleTexts` and accessibility in UI5 Web Components here: https://sap.github.io/ui5-webcomponents/master/playground/advanced/accessibility/

Regards,
Stanislav

**Closed by stbodurov** 2022-04-15 06:55 UTC
