### ISSUE TITLE
DateTimePicker : In Horizon theme prefilled value is not opening to exact time instead opening to current time

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#5255] opened 2022-05-20 10:43 UTC
**DateTimePicker : In Horizon theme prefilled value is not opening to exact time instead opening to current time**
DateTimePicker : In Horizon theme prefilled value is not opening to exact time instead opening to current time, even if we fill in different time in sap_fiori_3 it updates automatically to the filled-in time but not the case with sap_horizon theme

![image](https://user-images.githubusercontent.com/89779778/169511724-ce798791-e0f6-44e0-8d92-97546b3935c7.png)

**Comment by terezamch** [comment] 2022-05-23 08:48
Hello @Arora05 ,

Unfortunately, I cannot reproduce the issue. For example, I tried reproducing in out playground https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/?sap-ui-theme=sap_horizon&isrtl=false 
Here everything looks fine.

Could you please add more steps for reproduction or create a minimum sample in jsbin or [codesandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html) for example? This would really help us and fasten the process of issue handling.

Thanks in advance,
Tereza

**Comment by Arora05** [comment] 2022-05-23 09:11
Hello @terezamch , 
If I'll update the time of Data-Time manually, and open the popover, the change in time  state is not reflecting when we reopen the popover,

![image](https://user-images.githubusercontent.com/89779778/169783361-e9ff7cd1-145f-4cad-8a1b-e5943f9cb0ec.png)

Then when you open Popover 
![image](https://user-images.githubusercontent.com/89779778/169785594-b7a794e8-5a5e-4e7b-a60c-4e81e9df61bb.png)

**Comment by terezamch** [comment] 2022-05-23 09:23
Hello @SAP/ui5-webcomponents-topic-b,

When the time part of a DTP gets changed, it is not applied in the picker sliders.
Steps for reproduction:
1. Open https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/?sap-ui-theme=sap_horizon&isrtl=false
2. Change the input value of the third DTP manually from 2020-04-13-04:16:16 am to 2020-04-13-12:16:16 am without focusing out.
3. Open the picker.
The new value is not passed to the sliders.

Best regards,
Tereza

**Comment by tsanislavgatev** [comment] 2023-04-07 10:48
Hello colleagues,

The issue was fixed in the latest versions, and it is available for test in playground.

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2023-04-07 10:48 UTC
Labels: bug, Medium Prio, TOPIC B
