### ISSUE TITLE
Set first date of the week in Date Picker web component

### ISSUE THREAD

**Issue by sbaltova** [SAP/ui5-webcomponents#626] opened 2019-07-04 14:19 UTC
We are working with date piker from ui5 webcomponents and we have a requirement to set first day of week in the date piker,

I couldn't find such property here: https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/

I also tried to run this: sap.ui.getCore().getConfiguration().getFormatSettings().setFirstDayOfWeek(2);

But it didn't change the date picker.

Contact Person: Naama Solomon [Fieldglass]

**Comment by MapTo0** [comment] 2019-08-06 14:03
Duplicate of https://github.com/SAP/ui5-webcomponents/issues/585

**Closed by MapTo0** 2019-08-06 14:03 UTC
Labels: enhancement, feature request
