### ISSUE TITLE
[DatePicker/DateTimePicker/DateRangePicker]: [a11y] Calendar Popover should have accessibleName

### ISSUE THREAD

**Issue by lormanlau1** [SAP/ui5-webcomponents#9280] opened 2024-06-20 20:48 UTC
### Describe the bug

The accessibleName is currently only applied to the input when using screen reader. Popover is reading the title of the page, needs a way to add accessible name to the calendar popover

### Isolated Example

https://stackblitz.com/edit/github-rpx2u9-p5fbvt?file=src%2FApp.tsx

### Reproduction steps

1. Open screenreader program (JAWS 2024)
2. Focus on the Input of the DatePickers
3. Hit F4 and observe that the screen reader is reading the title of the tab.

### Expected Behaviour

We want a way to be able to modify the popover accessible name with a different label than the input itself.
We expect it not to read the title of the tab.

### Screenshots or Videos

![Screenshot 2024-06-20 at 1 42 52 PM](https://github.com/SAP/ui5-webcomponents-react/assets/167583724/a542dbd2-74c4-4760-b807-eec3ba66cd5c)

### UI5 Web Components for React Version

1.29.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Additional Context

JAWS version 2024.2405.48

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment] 2024-06-21 06:59
Hello @lormanlau1,

We already had an report about this issue: https://github.com/SAP/ui5-webcomponents/issues/9189
and the issue is fixed via the following PR: https://github.com/SAP/ui5-webcomponents/pull/8693

Best regards,
Boyan

**Closed by unazko** 2024-06-21 06:59 UTC
Labels: bug, ACC, TOPIC B
