### ISSUE TITLE
Input Jaws issue

### ISSUE THREAD

**Issue by Shtilianova** [SAP/ui5-webcomponents#4694] opened 2022-02-03 14:18 UTC
Jaws 2021 announced three times the value state text in the [Input](https://sap.github.io/ui5-webcomponents/playground/components/Input/)

**Comment by niyap** [comment] 2022-02-14 15:45
Hello Colleagues,

The issue is an already reported JAWS issue. Here is a reference: https://github.com/FreedomScientific/VFO-standards-support/issues/597 It is not reproducible with the other screen readers as well as testing with JAWS in Edge.
As we could not influence over the issue, I am closing the incident.

Kind Regards,
Niya

**Closed by niyap** 2022-02-14 15:45 UTC
Labels: bug, Medium Prio, TOPIC RL
