### ISSUE TITLE
[Table]: Table is misaligned in latest 1.x version

### ISSUE THREAD

**Issue by shubhamnazare** [SAP/ui5-webcomponents#9994] opened 2024-10-09 09:04 UTC
### Bug Description

After upgrading UI5WC to 1.24.11 and UI5WC4R to 1.29.11, the table is aligned centered instead of top.

Before upgrade -
![Screenshot 2024-10-09 at 2 26 11 PM](https://github.com/user-attachments/assets/c7ff6341-7249-4f97-8aa1-83e7d5811771)

After upgrade -
![Screenshot 2024-10-09 at 2 26 22 PM](https://github.com/user-attachments/assets/eb001154-07be-438b-be20-f5897687edd3)

I did comparison between the DOM elements and their styles. I observed that `height: 100%` styles has been applied to `ui5-table-root` because of which I was seeing this issue. This change was added in this PR: https://github.com/SAP/ui5-webcomponents/pull/9768/files#diff-d338227a4cd8dc70f44df0ee56719f30ebb0020de18f7b8b83bedc90d0b0301d

If this is not an issue as per design, then please suggest any workaround.

### Expected Behaviour

Table should be aligned at the top instead of center.

### Isolated Example

Example with ui5wc 1.23.3: https://stackblitz.com/edit/vitejs-vite-gpadav?file=package.json,src%2FApp.jsx
Example with ui5wc 1.24.11: https://stackblitz.com/edit/vitejs-vite-kwe4f8?file=package.json,src%2FApp.jsx

As you can see in the above examples, the table is aligned at the top in `1.23.3` but in `1.24.11` it is aligned in the center.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.24.11

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment] 2024-10-10 09:02
Hi @shubhamnazare ,

Can you please provide live example that demonstrates the issue?

Best Regards,
Nikolay Hristov

**Comment by shubhamnazare** [comment] 2024-10-10 09:47
Hi @NHristov-sap

Here is the live example that demonstrates the issue -

Example with ui5wc 1.23.3: https://stackblitz.com/edit/vitejs-vite-gpadav?file=package.json,src%2FApp.jsx
Example with ui5wc 1.24.11: https://stackblitz.com/edit/vitejs-vite-kwe4f8?file=package.json,src%2FApp.jsx

As you can see in the above examples, the table is aligned at the top in 1.23.3 but in 1.24.11 it is aligned in the center.

**Comment by NHristov-sap** [comment] 2024-10-10 10:39
Hello @SAP/ui5-webcomponents-topic-tbl, 

the issue is reproducible, see the provided snippets above. 

Best Regards,
Nikolay Hristov

**Comment by DonkeyCo** [comment] 2024-10-15 12:10
Hi @SAP/ui5-webcomponents-core,

this issue is regarding the V1 table. Could you please have a look here?

Best regards,
Duc

**Comment by nnaydenow** [comment] 2024-11-18 13:13
Fixed in version 1.24 with: https://github.com/SAP/ui5-webcomponents/pull/10197
Fixed in version 2 with https://github.com/SAP/ui5-webcomponents/pull/10193

**Closed by nnaydenow** 2024-11-18 13:13 UTC
Labels: bug, Medium Prio, TOPIC Core, 1.24, Table_v1
