### ISSUE TITLE
[Carousel]: Number display of items in RTL mode is broken

### ISSUE THREAD

**Issue by MaksymPakhomov** [SAP/ui5-webcomponents#8473] opened 2024-03-19 11:12 UTC
### Bug Description

For the RTL mod, the location of the numbers looks incorrect

Actual:
![image](https://github.com/SAP/ui5-webcomponents/assets/149803486/aef11f95-6616-4541-93b9-f783d03cb8e7)
Expected:  `3 of 1`

Thanks a lot in advance!

### Affected Component

Carousel

### Priority

Medium

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment] 2024-03-19 12:48
Hello @SAP/ui5-webcomponents-topic-rd,

Please check the RTL mode. By the way, the same behavior is in SAPUI5.

Best regards,
Petya

**Comment by TeodorTaushanov** [comment] 2024-03-27 09:53
The issue is fixed in the main branch.

**Closed** 2024-03-27 09:52 UTC
Labels: bug, Medium Prio, TOPIC RD, SAP Brand
