### ISSUE TITLE
Ui5 Select 

### ISSUE THREAD

**Issue by camilo2312** [SAP/ui5-webcomponents#1517] opened 2020-04-23 13:12 UTC
Hello everyone

The use of inputs, text area, DatePicker works properly my Reactive Forms, but the ui-select and checbox do not, since I try to capture the valueChanges of my reactive forms and it does not work

The documentation tells me to import the following import '@ ui5 / webcomponents / dist / features / InputElementsFormSupport.js';
I do it but it still doesn't work

![image](https://user-images.githubusercontent.com/42982644/80103596-10857300-853a-11ea-941a-6930bea8ff30.png)

![image](https://user-images.githubusercontent.com/42982644/80103633-1f6c2580-853a-11ea-8b93-25ccd99f25f9.png)

I need to import something or I can't capture the values ​​of my select or checkbox that way

Thank you very much for the help

**Comment by fifoosid** [comment] 2020-04-24 07:47
The problem is that these two controls are not yet implemented to support two way data binding in Angular.

PS: In order to use any UI5 Web Component with reactive forms, you don't need to import ```@ui5/webcomponents/dist/features/InputElementsFormSupport.js;```. This module is used only for native HTML forms.

**Comment by camilo2312** [comment] 2020-04-24 12:29
Ok, thanks a lot for the help

**Comment by fifoosid** [comment] 2020-04-24 13:02
Will implement them as soon as possible

**Comment by fifoosid** [comment] 2020-05-08 13:48
Hi @camilo2312,

As you can see the two way data binding for the select is implemented.

Moreover, a quick update with regards to the checkbox: the component currently supports two way data binding with one bug: if the initial state of the checkbox is checked, it won't be applied. In the latest PR I have proposed a solution, but we are going to discus it internally before we merge it.

**Comment by fifoosid** [comment] 2020-05-12 08:53
Now after both PR are merged I am closing the issue

**Closed by fifoosid** 2020-05-12 08:53 UTC
Labels: RC8, feature request
