### ISSUE TITLE
DateTimeFormat: The range of hours in Chinese is not right

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#2766] opened 2021-02-02 06:55 UTC
**Describe the bug**
When the language is Chinese, and the formatPattern of DateTimeFormat is set to "YYYY'年'MMMdd'日' a h':'mm", it should be a 12-hour clock system. However, the range of hours is 24-hour.
![image](https://user-images.githubusercontent.com/4338219/106563072-3b3f3600-6566-11eb-9fd1-c597d6b685f0.png)

You can also reproduce this issue in the storybook website.
![image](https://user-images.githubusercontent.com/4338219/106563364-9f61fa00-6566-11eb-876c-c17e1e05e70c.png)

**Expected behavior**
when the time is 12-hour system, the hour can only be selected from 0 to 12.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11

**Comment by SunnyWind** [comment] 2021-02-02 07:34
Thanks for your quick reply.

Our project stays on the old version since some function dependencies for UI5 are broken in the higher version, and we don't have time to handle that for now.

However, the newer version should also have this issue since I can reproduce the issue in your storybook website.

**Comment by unazko** [comment] 2021-02-05 10:00
Hello @SunnyWind,

Thank you for sharing this finding.
The issue is also reproducible with the latest release as well, but it is fixed in the current master branch.

The fix will be available with the next release @1.0.0-rc.12 around February 11th.

Best Regards,
Boyan

**Comment by unazko** [comment] 2021-02-22 11:08
Hello @SunnyWind,

The issue is fixed with v1.0.0-rc.12 and ready for consumption.
You could test with the latest release and get back to us if further assistance is needed.

Best Regards,
Boyan

**Comment by ilhan007** [comment] 2021-03-26 09:31
RC.12 is released @SunnyWind did you try it. If you face the issue, please comment below and we will reopen the issue.

**Closed by ilhan007** 2021-03-26 09:31 UTC
Labels: Medium Prio, TOPIC B, author action, bug
