### ISSUE TITLE
[SF][Label]: Extra space before colon when the colon is shown

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3828] opened 2021-09-03 06:45 UTC
### **Bug Description**
There is an extra space between the componente text and colon. And in RTL mode, it doesn't have the space.
![image](https://user-images.githubusercontent.com/1614528/131962007-08b57a36-b669-4c5b-a59b-ad17a243a39e.png)

### **Expected Behavior**
A clear and concise description of what you expect to happen.
![image](https://user-images.githubusercontent.com/1614528/131962135-158bd30f-6ed6-4891-b8ec-cf4d04821d14.png)

### **Steps to Reproduce**
2. ...
3. ...

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).
https://sap.github.io/ui5-webcomponents/playground/components/Label/

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by gmkv** [comment] 2021-09-03 11:59
Hi,

This issue is a duplicate of #3531.
You can follow the status of the bug there.

Regards,
Georgi

**Closed by gmkv** 2021-09-03 11:59 UTC
Labels: Medium Prio, TOPIC RD
