### ISSUE TITLE
SideNavigation: unnecessary overflow item displayed  

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8256] opened 2024-02-07 10:15 UTC
### Bug Description

The `SideNavigation` shows the overflow item in collapsed state even though there is enough space to display all items.

### Affected Component

SideNavigation

### Isolated Example

https://stackblitz.com/edit/js-9cvsrq?file=index.js,index.html

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/js-9cvsrq?file=index.js,index.html)
2. See that in both examples the overflow item is displayed, even though there would be enough space to show all items

### Log Output, Stack Trace or Screenshots

<img width="657" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/a4055eea-73a1-4904-86a6-43db405ffbf8">

### Priority

None

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Organization

MXP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment] 2024-02-07 11:14
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please have a look at this issue about the overflow functionality of the `ui5-side-navigation` component.
It appears that the overflow button is shown, even when there is enough space to show all items.
Could be reproduced in the following example:
https://stackblitz.com/edit/js-9cvsrq?file=index.js,index.html

Thanks and Regards,
Yana

**Comment by TeodorTaushanov** [comment] 2024-04-08 07:07
Hi,

The issue is fixed with version 1.24

https://stackblitz.com/edit/js-ml7bkz?file=index.js,package.json

Best,
Teo

**Closed by TeodorTaushanov** 2024-04-08 07:07 UTC
Labels: bug, Medium Prio, TOPIC RD
