### ISSUE TITLE
ui5-shellbar: shellbar items overflow menu does not close on Enter

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4556] opened 2022-01-10 21:34 UTC
### **Bug Description**
Shellbar items overflow menu does not close when pressing Enter to select a Shellbar item, it does close when pressing Space or Clicking.
If I breakpoint in `Shellbar._actionList.itemPress`, Enter works, so it seems that there is some timing issue somewhere.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. Shrink window width to render overflow ("...") Shellbar item
3. Click on overflow ("...") Shellbar item
4. Press "Enter" to activate the first item in the overflow popover
Observe: Shellbar item was handled (eg. search opens), but overflow popover was not closed.

### **Context**
- UI5 Web Components version: 1.0.1
- OS/Platform: macOSX 12.0.1
- Browser: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
- Affected component: ui5-shellbar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by nnaydenow** [comment] 2022-01-12 08:18
Hello colleagues,

The issue is reproducible as described above.

Regards,
Nayden

**Comment by ilhan007** [comment] 2022-01-17 07:15
Hello @JarrettChan the issue is resolved with https://github.com/SAP/ui5-webcomponents/pull/4577 and will be released with 1.1.0 by 21 Jan

**Closed** 2022-01-17 07:14 UTC
Labels: bug, Medium Prio, TOPIC P
