### ISSUE TITLE
MultiComboBox: N-More shows all items

### ISSUE THREAD

**Issue by d3xter666** [SAP/ui5-webcomponents#3671] opened 2021-08-16 09:01 UTC
### **Bug Description**
When there are multiple tokens in the MultiComboBox and there's not enough space to fit them all, there's a text "N more".
Clicking on this text does not differ from clicking on the arrow to show all the items.

### **Expected Behavior**
In UI5 clicking on the "N more" text shows a list with the tokenized items only.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/
2. Choose a MultiComboBox with many items and select as many as possible, but not all, so the "N more" text to appear
3. If necessary, shrink the screen

**Comment by niyap** [comment] 2021-09-07 20:20
The issue is reproducible in iOS as well

**Comment by MapTo0** [comment] 2021-09-28 13:16
fixed with https://github.com/SAP/ui5-webcomponents/pull/3931

**Closed by MapTo0** 2021-09-28 13:16 UTC
Labels: Low Prio, TOPIC RL, 1.0 Release Testing
