### ISSUE TITLE
ViewSettingsDialog's sort by option is not working 

### ISSUE THREAD

**Issue by hkshetry** [SAP/ui5-webcomponents#3687] opened 2021-08-18 13:39 UTC
### **Bug Description**

when sort by radio option is clicked, throwing  errors in console then dialog is not working

### **Expected Behavior**

Sort by radio option should work  without errors

### **Steps to Reproduce**

1. use following code
 ```
<ui5-view-settings-dialog id="ViewSettingsDialog">
	<ui5-li slot="sortItems" >Name</ui5-li>
	<ui5-li slot="sortItems">Position</ui5-li>
	<ui5-li slot="sortItems">Company</ui5-li>
	<ui5-li slot="sortItems">Department</ui5-li>
</ui5-view-settings-dialog>
```
then open dialog with following way
`document.getElementById("ViewSettingsDialog").open();`
2. dialog opens up correctly without any errors and click Name option
3. following errors is in console which thrown by _disableResetButton
```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLElement'
    |     property '__reactFiber$oha7dq8d33o' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at HTMLElement.get _disableResetButton [as _disableResetButton] (ViewSettingsDialog.js:240)
    at block0 (ViewSettingsDialogTemplate.lit.js:5)
    at main (ViewSettingsDialogTemplate.lit.js:11)
    at executeTemplate (executeTemplate.js:14)
    at updateShadowRoot (updateShadowRoot.js:15)
    at HTMLElement._render (UI5Element.js:580)
    at renderImmediately (Render.js:40)
    at RenderQueue.process (RenderQueue.js:59)
    at Render.js:63
get _disableResetButton @ ViewSettingsDialog.js:240
block0 @ ViewSettingsDialogTemplate.lit.js:5
main @ ViewSettingsDialogTemplate.lit.js:11
executeTemplate @ executeTemplate.js:14
updateShadowRoot @ updateShadowRoot.js:15
_render @ UI5Element.js:580
renderImmediately @ Render.js:40
process @ RenderQueue.js:59
(anonymous) @ Render.js:63
requestAnimationFrame (async)
(anonymous) @ Render.js:59
scheduleRenderTask @ Render.js:58
renderDeferred @ Render.js:29
_invalidate @ UI5Element.js:44
set @ UI5Element.js:869
ListItem.deactivate @ ListItem.js:142
_onmouseup @ ListItem.js:204
handleEvent @ parts.ts:532
EventPart.__boundHandleEvent @ parts.ts:490

```

### **Context**
- UI5 Web Components version: 0.31.15
- OS/Platform: mac
- Browser: crome
- Affected component: ViewSettingsDialog

### **Log Output / Stack Trace / Screenshots**
```
https://codesandbox.io/s/ui5-webcomponents-forked-7vi2l?file=/src/index.js
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactor
- Bussiness impact:  This sorting dialog is need to sort cards

**Comment by ilhan007** [comment] 2021-08-18 21:02
Hello @hkshetry we could not reproduce the issue, please provide a reproducible example.

You can use this one https://codesandbox.io/s/ui5-webcomponents-forked-iehji?file=/src/index.js
to show the issue - It already uses 0.31.15


https://user-images.githubusercontent.com/15702139/129971310-245a6fa2-8655-43fa-9d6b-f2cd978294ff.mov

**Comment by hkshetry** [comment] 2021-08-19 13:23
Hi @ilhan007,

Thank you for the response. you are correct if It is working on the link that you mentioned above. unfortunately, there is issue if we wrap the code in component. please refer my link to replicate issue https://codesandbox.io/s/ui5-webcomponents-forked-7vi2l?file=/src/index.js

**Comment by unazko** [comment] 2021-08-19 19:43
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible via the provided by the author snipped and steps.

Best Regards,
Boyan

**Comment by hkshetry** [comment] 2021-08-23 12:08
@unazko  Thank you for fixing the issue. is any update for release the fix?

**Comment by ilhan007** [comment] 2021-08-23 12:41
Hi @hkshetry it's under code review, it's not yet merged.

**Closed** 2021-09-10 14:02 UTC
Labels: High Prio, TOPIC B, SF

**Comment by fifoosid** [comment] 2021-09-10 14:10
This fix will be available in our next stable version as well as in the next 0.31 release.
