### ISSUE TITLE
Input: type "Number" doesn't allow decimal values on Firefox

### ISSUE THREAD

**Issue by nicolas-kennemann-fioneer** [SAP/ui5-webcomponents#7497] opened 2023-08-25 13:48 UTC
### Describe the bug

When I try to enter a decimal value (e. g. `1.5`) into the Input with type "Number", it clears the input field as soon as I type the `.`.
I even tried typing a `,`, but this doesn't work either.

As a comparison, on Chrome I can enter `1.5`. If I try entering `1,5`, the comma is ignored and not appended to the input's `value`, which leaves me with `1`

These tests were performed on the [storybook page](https://sap.github.io/ui5-webcomponents-react/?path=%2Fdocs%2Finputs-input--docs).

### Reproduction steps

see description

### Expected Behaviour

Firefox behaves the same way as Chrome

### UI5 Web Components for React Version

the one in storybook, as of 2023-08-25

### UI5 Web Components Version

the one instorybook, as of 2023-08-25

### Browser

Firefox

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment] 2023-08-29 11:38
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-rl,

The `ui5-input` doesn't work as expected in Firefox - whenever ',' or '.' is typed the input gets cleared.

Kind Regards,
Nikolay

**Comment by ivoplashkov** [comment] 2023-09-08 08:47
Hello,

This seems to be a bug by the browser itself and it's already fixed with the latest version. You can see https://connect.mozilla.org/t5/ideas/bring-back-the-ability-to-enter-decimal-points-in-numeric-fields/idi-p/32249 for refference. I have tested the issue on the master branch with the latest version of FF and it's no longer reproducible, therefore I am closing this issue.

Best regards,
Ivaylo

**Closed by ivoplashkov** 2023-09-08 08:47 UTC
Labels: bug, Medium Prio, TOPIC RL
