### ISSUE TITLE
Click file name of Upload Collection will wrongly trigger click event twice

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#5743] opened 2022-08-29 18:22 UTC
### **Bug Description**
Mouse click file name in ui5-upload-collection will wrongly trigger click event twice.

### **Expected Behavior**
Use mouse click file name should only trigger click event once just like use keyboard  Enter/Space key.

### **Steps to Reproduce**
1. Go to https://snippix.only.sap/#571022 which has create a simple ui5-upload-collection with one item inside it which has clickable file name.
2. Click that file name
3. Page and console log will show click count information. Count will be increase twice
4. Try use enter key to trigger link and will see only increase one for count.

### **Isolated Example**
ui5-upload-collection

### **Context**
- UI5 Web Components version: 1.6.0
- Affected component:  ui5-upload-collection and ui5-upload-collection-item

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
There are workarounds like use timestamp to defect very close events to avoid duplicated event handling.

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: Successfactors
- Business impact: Impact b2211 release.

**Comment by nnaydenow** [comment] 2022-08-31 10:54
Hello @mydavidzhang,

The issue is fixed with #5642 and it will be available with the next version.

Regards,
Nayden

**Closed by nnaydenow** 2022-08-31 10:54 UTC
