### ISSUE TITLE
[ui5-table]: Busy indicator misplaced, when not on full screen

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3818] opened 2021-09-02 12:05 UTC
### **Bug Description**
The busy indicator in the More button sample of the ui5-table is misplaced, when the browser screen is with a reduced width (for example shrink the width to 50%)

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/Table/
2. Scroll to More button sample
3. Shrink the screen a bit and press the button. The busy indicator should be shown in the center, but it is misplaced depending on the screen size

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment] 2022-06-15 12:03
Hello Colleagues,

The issue is not reproducible anymore, so I am closing the incident!

Kind Regards,
Niya

**Closed by niyap** 2022-06-15 12:03 UTC
Labels: Low Prio, TOPIC RL, 1.0 Release Testing
