### ISSUE TITLE
[MultiInput]: it shows "x more" instead of "x items" whenever the first label is greater than the input

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents#7250] opened 2023-06-23 05:15 UTC
### Bug Description

Since on fiori guidelines, https://experience.sap.com/fiori-design-web/multiinput/#reviewing-tokens, it has stated that it should show the "items" label whenever the first label is greater than the input. So, the "more", should only be shown when you can see some of the items already.
Please refer to https://codesandbox.io/s/magical-carson-c04jdd?file=/src/App.js

### Steps to Reproduce

1. go to https://codesandbox.io/s/magical-carson-c04jdd?file=/src/App.js
2. see that "5 more" is shown instead of "5 items"
<img width="546" alt="Screenshot 2023-06-23 at 10 43 52 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/3ce6f09b-b439-4d3f-b4fd-3766d48b1b3b">

### Priority

Medium

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment] 2023-06-23 08:55
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible via the following snippet:
https://codesandbox.io/s/wizardly-knuth-msmnpy?file=/src/App.js

Actual:
- The "8 More" text is filled in the input.

Expected
- The "8 Items" text should be filled in the input


The same issue isn't reproducible in openui5.

Best regards.
Boyan

**Comment by hristop** [comment] 2023-06-23 09:56
Hi, 

This feature request was already denied. Please check for further details and discussions 7083. 

Best Regards,
Hristo

**Comment by hristop** [comment] 2023-07-13 12:07
Hi,

We have misunderstood the requirement and have a fix for it almost ready with: BGSOFUIRILA-3653

I am moving this tho the planning board as it was actually a feature request. 

Best Regards,
Hristo

**Closed** 2023-07-23 20:25 UTC
Labels: bug, Medium Prio, TOPIC RL
