### ISSUE TITLE
ui5-combo-box: unstable test

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#7820] opened 2023-11-08 11:27 UTC
### Bug Description

Build fails with the following error:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/a7a6e3f4-f41a-431b-9783-1f3a2c5f2489)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/a66c3cd5-73cc-4b42-a75f-17ad31a0c7e6)

pull request link: https://github.com/SAP/ui5-webcomponents/pull/7818

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment] 2023-11-08 12:15
Hello colleagues,

Can you take a look at this failing test?

Best Regards,
Tsanislav

**Comment by niyap** [comment] 2023-11-13 07:12
The issue is fixed with #7834

**Closed by niyap** 2023-11-13 07:12 UTC
Labels: bug, TOPIC RL, Quality
