### ISSUE TITLE
MultiInput: Token Deletion is not working when readonly property is set to true for multiInput

### ISSUE THREAD

**Issue by nidhi0104** [SAP/ui5-webcomponents#5935] opened 2022-10-13 09:29 UTC
The function onTokenDelete is not getting triggered when the property 'readOnly' is set to true. If we keep 'readonly' as falsest is working but then user can create any token, but in our case we are using value help and getting tokens from there, so we don't want user can type any token apart from this. 

https://codesandbox.io/s/multiinput-token-delete-2nfh2o?file=/src/Filter.js

**To Reproduce**
1. Go to MultiInput
2. Click on cross button
3. Token will not get deleted

**Expected behavior**
Token should get Deleted.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.8.0",
`@ui5/webcomponents-react` version:"1.0.1"
Operating System:
Browser:Chrome

**Comment by kineticjs** [comment] 2022-10-20 13:20
Hi @nidhi0104,

This looks like a feature request to me. Yes, I can confirm that currently the "token-delete" event is not fired on readonly multiinputs because they are not editable.

Would you please give us more background of the use-case: why you need this event on non-editable input to give us a better understanding of this feature request.

Thanks,
Diana

**Comment by MapTo0** [comment] 2022-10-24 13:45
I can confirm that this is an issue and you can follow #4522 

Duplicate of: https://github.com/SAP/ui5-webcomponents/issues/4522

**Closed** 2022-10-24 13:45 UTC
Labels: information required, author action
