### ISSUE TITLE
MultiComboBox Popover has unnecessary padding

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2404] opened 2020-10-27 11:27 UTC
You can notice the blank space before the first item. It is caused by the following css rule:

In PopupsCommon.css, line 31
```css
.ui5-popup-root .ui5-popup-header-root {
    box-shadow: var(--sapContent_Shadow0);
    margin-bottom: 0.125rem;
}
```

![image](https://user-images.githubusercontent.com/16850339/97295137-97a00480-1857-11eb-82c3-c871c849ae67.png)

**Comment by niyap** [comment] 2021-03-04 08:56
I am not able to reproduce the issue anymore, so I am closing the incident.

**Closed by niyap** 2021-03-04 08:56 UTC
Labels: Low Prio, TOPIC RL
