### ISSUE TITLE
[SF] ui5-timeline – line broken

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#3826] opened 2021-09-03 00:42 UTC
### **Bug Description**
We are having an issue with the [Timeline horizontal component](https://sap.github.io/ui5-webcomponents/playground/components/Timeline/) on our testing environment, in which the horizontal line goes further than it should be. See the screenshot attached. It’s only encountered on qacand, but not local environment.

We have tried the following to fix it with no success.

- checking whether an ancestor CSS class is creating this issue through overwriting or specificity
- changed from having no icon to having icon in the Timeline component
- removing qacand’s navbar/header

### **Expected Behavior**
Timeline horizontal line to have spaces around dot's icon

### **Steps to Reproduce**
Environment: https://qacand.hcm.ondemand.com/
Login: **STEAmeAirH / adminb1 / Welcome@11**

1. Proxy as 'cgrant'
2. Access Capability Portfolio (_/sf/capabilityportfolio_)
3. Click on any capability card
4. Scroll down and expand Proficiency Level History
5. See Timeline line broken

### **Context**
- UI5 Web Components version: @ui5/webcomponents: 0.31.14
- OS/Platform: macOS
- Browser: Chrome
- Affected component: Timeline

### **Log Output / Stack Trace / Screenshots**
<img width="1582" alt="timeline-broken" src="https://user-images.githubusercontent.com/11576789/131933120-7f55ee27-7bba-4851-afef-e89a1e7d43e1.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - Medium
- Accessibility issue - Low
- Functional issue - Low
- Visual issue - High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Bussiness impact: Visual impact on Timeline component

**Comment by Shtilianova** [comment] 2021-09-03 13:31
Hello @rchrdchn,
When I try to reach some of the capabilities I have console errors. Do you observe the same behavior? Also what you mean with "Proxy as 'grant'"?
Regards,
Diana

**Comment by rchrdchn** [comment] 2021-09-03 17:07
Hey @Shtilianova - see below screenshots. There is an option to "proxy" as other users 🙂

**Proxy option from Profile dropdown**
![Screen Shot 2021-09-03 at 10 03 13](https://user-images.githubusercontent.com/11576789/132042426-c6f7ec39-8ac6-4d74-bc9c-43a3d28ec0df.png)

**Proxy as "cgrant" - click OK**
![Screen Shot 2021-09-03 at 10 03 43](https://user-images.githubusercontent.com/11576789/132042430-c52aa14d-b977-45ca-9fd7-bb885f9e02c0.png)

**Go to Capability Portfolio through either Module Picker (Home dropdown) or link _/sf/capabilityportfolio_**
![Screen Shot 2021-09-03 at 10 04 34](https://user-images.githubusercontent.com/11576789/132042432-2cd0e8fa-b7b4-407b-831a-088cf1ddebc1.png)

**Capability card details**
![Screen Shot 2021-09-03 at 10 04 47](https://user-images.githubusercontent.com/11576789/132042433-445d8cdf-4f84-488f-963a-9a68e6bb7a48.png)

**Comment by fifoosid** [comment] 2021-09-07 10:16
Hi @rchrdchn 

After executing your steps, I get the following screen(after proxying as cgrant):
![image](https://user-images.githubusercontent.com/16850339/132328040-2360abc0-50a9-4064-8a51-c760f54a696d.png)

I think that it would be easier if you create an isolated example via [CodeSandBox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=/index.html&file=/index.html:0-33)

**Comment by rchrdchn** [comment] 2021-09-08 00:24
Hey @fifoosid - that's strange. Did you login with the company ID, username, and password below, then proxied as "cgrant"?

Login: **STEAmeAirH / adminb1 / Welcome@11**

This is a case that seems to only happen on this instance and the reason we are requesting your help with the provided qacand instance. We have not been able to reproduce it anywhere else.

**Comment by fifoosid** [comment] 2021-09-08 08:50
Hi @rchrdchn

Yes, I used the provided login params and then proxied as cgrant. I just did it again and the result was the same

If you can't reproduce it anywhere else, this means that it is related to your instance and not to the webcomponent itself.

**Comment by BennyHuang** [comment] 2021-09-23 05:50
@fifoosid I can reproduce it with sapUiSizeCompact in the container even in the playground page. Would you please take a look again? Thanks
![image](https://user-images.githubusercontent.com/1995447/134459975-616a9148-cac0-49e9-96af-66cbe07ba810.png)

**Comment by ilhan007** [comment] 2021-09-23 06:23
Hi Everybody

the issue is reproducible in RC.15
https://sap.github.io/ui5-webcomponents/playground/components/Timeline/?sap-ui-theme=sap_fiori_3&isrtl=false

and fixed in the latest master:
https://sap.github.io/ui5-webcomponents/master/playground/components/Timeline/?sap-ui-theme=sap_fiori_3&isrtl=false

So, we need to find the specific fix that should be downported. We will do that.

**Comment by ilhan007** [comment] 2021-09-23 06:25
Hello @Todor-ads @fifoosid could you confirm that this is the fix for the issue in compact mode:
https://github.com/SAP/ui5-webcomponents/pull/3902

<img width="496" alt="Screenshot 2021-09-23 at 09 25 38" src="https://user-images.githubusercontent.com/15702139/134462819-73a5116d-d985-44da-a80d-c24a7c46885b.png">
.

**Comment by Todor-ads** [comment] 2021-09-23 06:40
Hello @ilhan007,
Yes, I confirm that this is the solution to the problem in compact mode

Best Regards,
Todor

**Comment by ilhan007** [comment] 2021-09-23 07:42
Hello @rchrdchn
the following change #3902 fixes the issue you experience with the Timeline's last line in compact mode, it does not go over the last item's icon any more. This has been already fixed in the master, but now also downported to 0.31 and will be released with the next patch.

**Closed by ilhan007** 2021-09-23 07:42 UTC
Labels: TOPIC B, SF, Very High Prio

**Comment by rchrdchn** [comment] 2021-09-24 20:50
Thanks @ilhan007 - when do you guys usually release patches?

**Comment by ilhan007** [comment] 2021-09-25 05:02
The fix is already released - 0.31.19. Usually every two week.
But because of your 2111 milestone, this week we released twice.
