### ISSUE TITLE
ComboBox, MultiComboBox: No tooltip to read complete cropped additional text

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5683] opened 2022-08-17 15:17 UTC
Hi Colleagues,

We have a usecase in the application where in we provide a combobox and multicombobox for user to select data from. In both these cases, we show text and additional text. However, we see that these get cropped if space is not sufficient. There is also no option to provide a title or tooltip property which would provide the user with complete info on hover over.

The issue is pointed out by multiple customers and bugs are raised. Request you to please consider and fix the issue as soon as possible. Need a reply regarding the same as it is to be provided to the customers.

**Comment by unazko** [comment] 2022-08-19 13:14
Hello @SAP/ui5-webcomponents-topic-rl,

As @PriyaPowar explained there is no way to provide a tooltip for the ui5-cb-items. There is <code>title</code> property in for the ui5-li items, which is documented as private. This <code> title property could be reused internally by the ui5-combobox control if there is similar API for the ui5-cb-items. By accessibility standard there should be an option to reach the full text in this case.

Best Regards,
Boyan

**Comment by nikolay-kolarov** [comment] 2022-08-25 11:22
Hi @PriyaPowar ,

This is the same implementation, as it is also in UI5.
The designers are working on a concept how this can wrap, but it is currently in progress.
Once this is done, then we can see what needs to be implemented and in which components.
I cannot give a timeline, as I cannot predict what will be the outcome of the design.

Best Regards,
Nikolay

**Comment by hristop** [comment] 2023-01-19 09:54
relates with #5323

**Comment by tunahan** [comment] 2023-05-31 09:21
Any news or development ? @Lukas742 Would it be possible to see this feature in near future?

**Comment by tunahan** [comment] 2023-05-31 09:34
Hi, @hristop It is seen that it is blocked according to planning board. Any info on timing? 
Thanx

**Comment by hristop** [comment] 2023-06-01 08:34
Hi @tunahan ,

The issue is not blocked anymore and we will try to add it in some of our next sprints depending on capacity and priorities. 
Unfortunately I can't give you more precise estimate. Once it is planned the issue #5323 will be updated. 

I am closing this one as it is a duplicate. 

Best Regards,
Hristo

**Closed by hristop** 2023-06-01 08:34 UTC
Labels: feature request, ACC, Medium Prio, TOPIC RL, Blocked
