### ISSUE TITLE
Cannot unselect MultiComboBoxItem with long text

### ISSUE THREAD

**Issue by f16r** [SAP/ui5-webcomponents#6193] opened 2022-12-15 13:15 UTC
### **Bug Description**
ui5-mcb-item with long text can't be removed by clicking x 
![2022-12-15_13-56-29](https://user-images.githubusercontent.com/37051913/207867293-8e264365-68ac-4c38-88d6-c3a901ba7798.gif)

### **Expected Behavior**
Clicking x unselects ui5-mcb-item

### **Steps to Reproduce**
1. Create a ui5-multi-combobox
2. Add a ui5-mcb-item with long text
3. Select the ui5-mcb-item with the long text
4. Try to remove it by clicking x 

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-1ct6mx?file=/index.html

### **Context**
- UI5 Web Components version: 1.8.0
- Browser: Chrome 107.0.5304.107
- Affected component: ui5-mcb-item & ui5-multi-combobox

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by plamenivanov91** [comment] 2022-12-15 15:04
Hello @SAP/ui5-webcomponents-topic-rl,

Multicombobox item with long text can't be removed by clicking on the 'x' icon.

Follow the reporter's code snippet and steps in the initial description to reproduce the issue.

Can you take over?

Regards,
Plamen Ivanov

**Comment by MapTo0** [comment] 2022-12-21 15:39
Duplicate of https://github.com/SAP/ui5-webcomponents/issues/6092

Should be already fixed in the master.

**Closed by MapTo0** 2022-12-21 15:39 UTC
Labels: bug, High Prio, TOPIC RL
