### ISSUE TITLE
Panel: Table onRowClick prop blocked when adding internal Panel component on some web browsers 

### ISSUE THREAD

**Issue by stefanomantova** [SAP/ui5-webcomponents#5680] opened 2022-08-16 19:54 UTC
**Describe the bug**
When including a `Panel` component inside a `TableRow`, is not possible to trigger onRowClick on `Firefox` and `Safari`.

**Isolated Example**
Access the below Sandbox in Chrome, Firefox and Safari:
https://codesandbox.io/s/1bfibd?file=/src/App.js:461-471

**To Reproduce**
1. Go to https://codesandbox.io/s/1bfibd?file=/src/App.js:461-471 using `Google Chrome` browser.
2. Click on "Content 1" text. A Toast Message should be triggered indicating the onRowClick.
3. Perform the same steps in `Firefox` and `Safari`. The Toast message should not be triggered.

**Expected behavior**
The onRowClick should be triggered in any of the above web browsers with the same behavior, displaying the message toast. Looks like there is an issue in any of the FlexBox sizing during the use of `Panel` component which blocks the clickable area on `Firefox` and `Safari`.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: Both macOS Monterey 12.5 and Windows 10
Browser: Mozilla Firefox 101.0 (64-bit) and Safari Version 15.6 (17613.3.9.1.5).

**Additional context**
This is a request for our internal SAP project.

**Comment by Lukas742** [comment] 2022-08-17 07:57
I already investigated the issue a bit, maybe these findings help:

@stefanomantova 

- `TableCell`s should be used as `children` of the `TableRow` ([see docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-table--default-story) - properties table -> TableCell)
- `className` only accepts a `string`, so this won't work:
```jsx
className={{
  border: "none",

  "&::part(content)": {
    padding: 0
  },
  "&::part(header)": {
    border: "none"
  }
}}
```
- The behavior is reproducible without a Flexbox, so probably only the Panel is responsible for it ([example](https://codesandbox.io/s/bold-shaw-j2w7b0?file=/src/App.js))
- As a workaround you can set `onClick` on the FlexBox or the Panel

@colleagues 

The `row-click` event is only fired in these cases:

- All browsers: when clicking on the padding area of the TableCell
- Only in Chrome: when clicking on the title of the Panel header
https://codesandbox.io/s/bold-shaw-j2w7b0?file=/src/App.js

**Comment by stefanomantova** [comment] 2022-08-17 13:03
Hi @Lukas742, thank you for your fast answer. For now, we are using the following onClick workaround inside the panel header.
```
onClick={
        (event): void => {
          if ((event.target).tagName !== "UI5-PANEL") {
            toBeCalledOnClick();
          }
        }
      }
```
This approach has been adopted since the regular `onClick` is triggered even in case you click on the `Panel` arrow to dropdown it. But as per your answer I understand that the `row-click `should be fired with the same behavior in all browsers whe you click in any area of the table cell?

**Comment by Lukas742** [comment] 2022-08-17 15:02
Hi @stefanomantova 

sorry for the confusion, I'm not in the UI5 Web Components team but in the UI5 Web Components for React team and I just shared my findings as I was investigating the issue already before Marcus transferred it. 
So, we'll have to wait for one of the UI5 Web Components members to clarify what the intended behavior here is.

**Comment by ndeshev** [comment] 2022-08-31 15:33
Hello @stefanomantova,

Using a panel inside of a table is a bad practice. Per design and specifications the Panel component is "a container for controls." and you should avoid nesting it in such way or you may find strange behaviors like this or others. 

In that case you can't handle the row click as the click is captured at panel's level by its header and we handle that click internally for the toggling functionality of the panel.

**Closed by ndeshev** 2022-08-31 15:33 UTC
Labels: bug
