### ISSUE TITLE
[SF] [Check Box]: The performance is bad while rendering too many checkboxes on the same page. 

### ISSUE THREAD

**Issue by ChristyFei** [SAP/ui5-webcomponents#4241] opened 2021-11-02 09:36 UTC
**Describe the bug**
The performance is bad while rendering too many checkboxes on the same page. 

**To Reproduce**

In our scenario, the customer can view and check multiple checkboxes on the same page. The number of checkboxes is 390 in my test case. It takes 270ms to render the checkbox. According to the performance screenshot, the updateShadowRoot method takes too much time. 

![Screen Shot 2021-11-02 at 5 12 15 PM](https://user-images.githubusercontent.com/16127196/139821271-6508bbe3-cb84-4d5d-8092-9977621440f0.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.15
`@ui5/webcomponents-react` version: 0.131.16
Operating System:
Browser: Chrome

**Comment by dimovpetar** [comment] 2021-11-03 09:43
Hello @ChristyFei ,

Thank you for reporting this. It looks like the problem is caused by a Forced reflow caused by `getComputedStyle` call in `getEffectiveDir`. This problem is already reported in issue #3614. We would therefore close this issue and continue with this inquiry under the number of the existing message. Please follow the progress there.

Best regards,
Petar

**Closed by dimovpetar** 2021-11-03 09:43 UTC
