### ISSUE TITLE
[ui5-date-picker]: misaligned

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#7021] opened 2023-05-11 15:09 UTC
### Bug Description

The Date Picker component is misaligned.

### Expected Behaviour

The height of the host element `ui5-date-picker` is 2.25rem, but the offsetHeight taken by the `ui5-input` inside the shadow root is more than that.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/?sap-ui-theme=sap_fiori_3&isrtl=false

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/22086365/114f8878-2384-4f55-a414-ca81d0706155)

![image](https://github.com/SAP/ui5-webcomponents/assets/22086365/e75579e7-890d-447d-8431-0b9c08caba19)

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment] 2023-05-11 15:09
Hi @SAP/ui5-webcomponents-topic-b 
Would you have a look at this misalignment issue?

**Comment by hinzzx** [comment] 2023-05-17 06:46
Hi @gmkv,

Thank you for reporting !
The issue is being addressed and fixed within this [Pull Request](https://github.com/SAP/ui5-webcomponents/pull/6886). Once merged I will close the issue.

Best Regards,
Stoyan

**Closed** 2023-05-29 13:41 UTC
Labels: bug, Medium Prio, TOPIC B
