### ISSUE TITLE
StepInput: onChange event is not triggered in some circumstances.

### ISSUE THREAD

**Issue by tunahan** [SAP/ui5-webcomponents#5490] opened 2022-07-11 06:36 UTC
**Describe the bug**
After value property of StepInput gets changed programmatically(with usage of react states), changing that StepInputs value to back what it was by typing does not triggers the onChange event. Especially it happens after page gets loaded initially. After doing some poke-around, the behavior gets back to the normal. But it takes some time.

**Isolated Example**
*[codesandbox](https://codesandbox.io/s/gifted-wescoff-j4j5px?file=/src/App.js).*

**To Reproduce**
1. Set first StepInput to 1001. So this move sets second StepInput to 2000 programmatically. 
2. Set second SptepInput to 1000 back by typing. (not using + , - buttons)
3. Since second StepInputs change event alerts its new value, you should have seen javascript alert. But alert is not shown because change event does not get triggered. This is the bug. You can set both StepInputs to another arbitrary values. You'll see the alert
**4. But whenever the user sets second StepInput to previous value, the change event is not triggered.**

**Expected behavior**
Every time the user changes the value of second StepInputs value, he/she has to see the new value via alert message.

**Screenshots**

https://user-images.githubusercontent.com/2466336/178202208-ba0f2d3d-ab34-40ac-969c-2645a0ffa400.mov

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.1
Operating System: Windows, Macos
Browser: Edge, Chrome

**Comment by gmkv** [comment] 2022-07-12 10:54
Hi @SAP/ui5-webcomponents-topic-rl,
There's an issue with the StepInput not firing change events consistently.
Would you have a look?

Same sample from above, but in plain js: https://codesandbox.io/s/ui5-webcomponents-forked-1lbo69?file=/index.html
To reproduce:
1. Set first StepInput to 1001. This will set the second StepInput to 2000 in the event handler.
2. Set second StepInput to 1000 back by typing. (not using + , - buttons)
3. Second StepInput does not fire its change event.


If you are having issues loading codesandboxes, please message me.

**Comment by gmkv** [comment] 2022-07-12 11:38
FYI @SAP/ui5-webcomponents-topic-b

**Comment by zinserjan** [comment] 2022-07-14 21:33
This affects all components based on the Input component. The fix in #5296 by @ivoplashkov improved the change event reporting but this works only if the change was triggered by an input event. If you change the value programmatically the reporting doesn't work the next time when you restore the previous value.

There is a pretty easy workaround for this issue. Just set the internal property `_changeFiredValue`  to `null` on the input field if you change the value programmatically. 

In the meantime we use the following workaround in react:


```tsx
import { Input, InputDomRef, InputPropTypes } from "@ui5/webcomponents-react";
import { FC, MutableRefObject, useRef } from "react";

export interface TextInputProps extends InputPropTypes {}

export const TextInput: FC<InputPropTypes> = (
  { value, ...props },
  forwardedRef
) => {
  const inputRef = useRef<InputDomRef>() as MutableRefObject<InputDomRef>;
  useOnChangeWorkaround(inputRef, value);

  return <Input {...props} ref={inputRef} value={value} />;
};
```

```tsx
import { InputDomRef } from "@ui5/webcomponents-react";
import { RefObject, useEffect } from "react";

// react hook to set workaround
export const useOnChangeWorkaround = (
  inputRef: RefObject<InputDomRef>,
  value: string | undefined
) => {
  useEffect(() => {
    if (inputRef.current == null) {
      return;
    }

    // workaround: change event is not triggered in the following case
    //  1. user sets value to "1234"
    //  2. input gets updated after onChange via render prop to "1"
    //  3. user sets value to "1234"
    // => no change will be triggered
    // @ts-ignore
    if (inputRef.current._changeFiredValue !== value) {
      // @ts-ignore
      inputRef.current._changeFiredValue = null;
    }
  }, [value, inputRef]);
};

```

**Comment by majidzadeh** [comment] 2022-07-19 12:25
Hello ui5-webcomponents team, 

Would it be possible to have this bug fixed for the next release of ui-webcomponents? If you could please share the timelines for the next release? This is causing a major bug in our application which needs to addressed before an upcoming release we have in a few days. 

Thanks

**Comment by apoorvsemwal** [comment] 2022-07-19 12:35
Hello ui5-webcomponents team,

We have been facing a similar issue with trigger for onChange event after the onClear from a UI5 filterbar component. We are using the latest set of ui5 dependencies.
**Steps to reproduce:
-> Type "Test" in Filter Input
-> Click on Clear Button
-> Check console - First onChange gets triggered and then onClear of the filterbar and input is cleared
-> Type the same text "Test" again and click on Clear Button
-> Check Console - Only the onClear event is triggered - There is no onChange**

Since the input text "Test" stays the same as across the 2 change events, component does not detect a change thereby the onChange event does not get triggered the second time.
It does not take into consideration the step in between where we clicked on Clear and using the input ref we had cleared the input. 
**We had tried doing the same without refs and simply using a state attached to the input but the behavior stays the same.** 

Here is a sample codesandbox to play around with
https://codesandbox.io/s/test-clear--filters-xdd2ij?file=/src/App.js

It would really help us if some timelines could be shared around a fix for this.

Thanks

**Closed** 2023-02-20 09:23 UTC
Labels: bug, Medium Prio, TOPIC B
