### ISSUE TITLE
ui5-table: cannot select text from table cell

### ISSUE THREAD

**Issue by tamiarah** [SAP/ui5-webcomponents#1163] opened 2020-01-29 10:28 UTC
**Describe the bug**
It is not possible to select the content of a table cell in case you want to copy the text from this cell. It is only working for the column headers but not in the rows. It is working in your example here: https://sap.github.io/ui5-webcomponents/playground/components/Table/ 
However, it is not working now, when implementing a table and then trying to copy the cell content.

**To reproduce**
1. See attached link and try to copy "test" from the table row.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-0kt3c?fontsize=14&hidenavigation=1&theme=dark 

**Expected behavior**
It should be possible to select the content, that you can copy it. 

**Context**
- UI5 Web Components version: 1.0.0-rc.5
- OS/Platform: Mac OS

**Affected components** 
ui5-table (ui5-table-cell, ui5-table-row)

Thanks!
Christina

**Comment by ilhan007** [comment] 2020-01-29 13:01
Hello @tamiarah 

Thanks for reporting.

If you wrap the text nodes  in spans - the text would be selectable.
We still don't know why it's not working your way.

```html
 <ui5-table-cell><span>test</span></ui5-table-cell>
```

**Comment by tamiarah** [comment] 2020-01-29 14:09
Hi @ilhan007 

Thanks for your fast response and the workaround with the span!

**Comment by ilhan007** [comment] 2020-02-26 08:49
Unfortunately, 
I could not find the root cause, but as there is fine workaround I will close the issue

I hope it is fine for you.

Best,
ilhan

**Closed by ilhan007** 2020-02-26 08:49 UTC
