### ISSUE TITLE
Incorrect focus behaviour on the <ui5-input/> example page

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#28] opened 2019-02-12 20:57 UTC
**Describe the bug**
accessibility issue on this page — https://sap.github.io/ui5-webcomponents/playground.html#/components/Input

Under the title "Input with Label": when clicking on the label "Secret Code" the focus appears on the "Name" field. So, both labels reference to the same field:

![screencast 2019-02-12 21-52-31](https://user-images.githubusercontent.com/748043/52667431-184a9000-2f11-11e9-898c-4d9d594726a8.gif)

**Expected behavior**
the focus should appear in "Secret Code" field, not in the neighbour field.

**Comment by ilhan007** [comment] 2019-02-13 06:32
@pavelkornev, thanks for reporting.

The issue is addressed with the following change:
https://github.com/SAP/ui5-webcomponents/pull/31

Until the fix is merged, we will keep the issue opened. Once resolved, we will close the issue.

**Closed** 2019-02-13 06:43 UTC
Labels: approved, bug, good first issue
