### ISSUE TITLE
[SF][a11y][popup-utils]: press ESC key will close multiple popups when the popups are created from different UI5 context

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#6705] opened 2023-03-14 08:00 UTC
### Bug Description

We have developed some widgets. The widgets have their separated bundle which contains `ui5-webcomponents` and `react` libraries. In some cases we need to reuse these widgets in different pages.

Let's imagine the following case:
We open a `ui5-dialog` called `DialogA` in a page, and in the opened DialogA we need to import a widget described above. After the widget bundle loaded, we will have two UI5 contexts which are not accessible to each other.

Then when we open another `ui5-dialog` called `DialogB` from widget bundle and press ESC key, the keypress action will close both DialogA and DialogB.

The main reason of this behavior may be the popup registry is not shared across different UI5 context which is not like the processing of `z-index`.

And as a result of this, the event listener would be added to document for multiple times.
https://github.com/SAP/ui5-webcomponents/blob/d37b319eb6f9b6ca27bd08a8a389595424f69f6e/packages/main/src/popup-utils/OpenedPopupsRegistry.ts#L22

### Affected Component

ui5-dialog, ui5-popover

### Expected Behaviour

The popup registry should be shared across multiple UI5 and OpenUI5 context, then the unexpected closure can be avoided.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.10.4

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment] 2023-03-17 08:32
Hello @zhangliangyi ,

Can you please provide a test system, where we could test or an isolated sample in order to debug the issue?

Thanks in advance!

Kind Regards,
Elena

**Comment by zhangliangyi** [comment] 2023-03-21 01:42
I will prepare some testable example for this issue.

**Comment by nnaydenow** [comment] 2023-04-11 10:35
Hi @zhangliangyi,

I'm closing the incident since it seems to be the same with: #6884. Also there is reproducible example so no need to prepare one.

Regards,
Nayden

**Closed by nnaydenow** 2023-04-11 10:35 UTC
Labels: bug, author action

**Comment by zhangliangyi** [comment] 2023-04-11 12:36
That's great. Thanks @nnaydenow .
