### ISSUE TITLE
[ui5-date-picker] showing vertical scrollbar in responsive popover

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4860] opened 2022-03-04 20:49 UTC
### **Bug Description**
When trying to upgrade to 1.2.x I am seeing a vertical scrollbar on the datepicker calendar responsive popover. When I revert down to 1.1.2, there is no vertical scrollbar. I have tracked it down to this change and this line of code: [pull/4672 line 22](https://github.com/SAP/ui5-webcomponents/pull/4672/files#diff-08dff9311ad1ccb61df449578ae4ff16a263079440459fcb16ced134f8c8173cR22) . This is quite strange because I cannot reproduce it in code sandbox. However it is reproducible sometimes with the dual calendar example in the playground. But for me, it is reproducible every time in my test page

### **Expected Behavior**
There should be no vertical scrollbar.

### **Context**
- UI5 Web Components version: 1.2.1
- Affected component: ui5 date-picker, ui5-calendar

### ** Screenshots**
1.2.1
![image](https://user-images.githubusercontent.com/38701667/156839446-b9d2c046-1b82-40b1-ab45-4994ca094c2e.png)

1.1.2:
![image](https://user-images.githubusercontent.com/38701667/156839403-e34a8947-af94-4de9-b138-a3547d415610.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium (Workaround to use 1.1.2

**Comment by PetyaMarkovaBogdanova** [comment] 2022-03-07 08:14
Hi colleagues,
can you, please, take a look at this issue, showing up in last version of UI5 Web Components?
I was able to reproduce it with last sample in the [playgound](https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/) "DatePicker with primary and secondary calendar type" .

Best regards,
Petya Markova.
UI5 Dispatcher

**Comment by unazko** [comment] 2022-03-14 12:47
Hello @allen138,

Thank you for sharing this finding.
The issue is coming from the pointed pull request and it will be fixed via the following PR:
https://github.com/SAP/ui5-webcomponents/pull/4795 as already linked in the issue.

Best Regards,
Boyan Rakilovski

**Closed** 2022-03-15 11:38 UTC
Labels: bug, Medium Prio, TOPIC B, SF
