### ISSUE TITLE
ui5-link is not underlined in hcb/hcw modes.

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#3932] opened 2021-09-15 20:49 UTC
### **Bug Description**
In high contrast themes, the links are missing underlines in the default state.
### **Expected Behavior**
In high contrast themes, since the link colors are almost the same as their surrounding text, low vision users need to be able to distinguish links from normal text. Hence they need to have underlines in the default state. Please refer to the screenshots from UI5 link samples in the default state in high contrast themes.

![hwb_links_underline_default](https://user-images.githubusercontent.com/38701667/133503980-c3e4e554-5019-4c8a-b4d9-0609daacccfe.jpg)
![hbw_links_underline_default](https://user-images.githubusercontent.com/38701667/133503998-00d65f9f-bf09-476e-b7ef-9bc9a822487f.jpg)

### **Context**
- UI5 Web Components version: 0.31.x
- OS/Platform: All
- Browser: All
- Affected component: ui5-link
- 
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

- Organization: SF
- Bussiness impact: Medium

**Comment by terezamch** [comment] 2021-09-16 09:00
Hello colleagues @SAP/ui5-webcomponents-topic-b,

When hovered the ui5-link component still has its underline in Quartz HCB and Quartz HCW themes.
https://sap.github.io/ui5-webcomponents/master/playground/components/Link/?sap-ui-theme=sap_fiori_3_hcb&isrtl=false

Note: the issue is reproducible in the master and in 0.31.x

Best regards,
Tereza

**Comment by ilhan007** [comment] 2021-09-17 09:59
The priority is not related to the severity this time, but to the upcoming deadline  (31.09) for resolving the issue.

**Comment by Todor-ads** [comment] 2021-09-20 14:11
Hello @allen138 ,

Can you provide a link to an application or an isolated scenario where this problem is reproduced? 
This is currently an issue in the  playground in the belize  HCB / HCW theme (fiori 3 is ok) - https://sap.github.io/ui5-webcomponents/playground/components/Link/ . If this is the problem you have, it has already been fixed. In case of a different scenario, please provide more information.

Best regards,
Todor

**Closed** 2021-09-21 07:05 UTC
Labels: bug, TOPIC B, SF, author action, Very High Prio
