### ISSUE TITLE
[SF][A11y][Table]Row count mismatch in JAWS VPC/forms mode for growing Table 

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#5721] opened 2022-08-25 09:48 UTC
### **Bug Description**
1) When the total number of growing table rowdata exceeds the default displayed number of data rows, the total row count indicated in the `aria-label` of table row, is different with the actual total row count.

2) In JAWS VPC mode, the growing table's row count is one more than the displayed row count.

### **Expected Behavior**
for issue 1:
This discrepancy is confusing to screen reader users.
Screen reader user doesn't know this is a growing table. Would be good if the "growing" info can be conveyed so there is no confusion regarding the mismatch.

for issue 2:
A growing Table with 2 row data, should announce 3 row(with the header row), but now annouced with 4 row, extra one row count is not expected.

### **Steps to Reproduce**
issue 1:
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Table/
2. Scroll down to section "Growing Table with "More" button"
3. Tab to the first row in the growing table
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/27538066/186628356-b5ddb257-31fa-4dc8-8d73-9bc772ea34eb.png">
4: See the row count announcement didn't convey that there are more rows to be load.

issue 2:
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Table/
2. Scroll down to section "Growing Table with "More" button"
3. Use JAWS VPC mode, and navigate to the first row of the table
4. See the table row count announced an extra one
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/27538066/186632465-e6e68768-1e6a-4e6d-af73-10155f44af26.png">

### **Context**
- UI5 Web Components version:1.6.0
- OS/Platform: Windows
- Browser: Chrome
- Affected component: ui5-table, growing mode

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: {...}

**Comment by ndeshev** [comment] 2022-08-30 17:12
Hello @SAP/ui5-webcomponents-topic-rl could you please take a look at this issue. When the table is set to `growing` the screen reader doesn't convey that to the user. 

I suppose that there is no way for the table to know how much more rows it will be loaded with, but the announcement that the table could be extended with more data is the thing that should be discussed.

The second issue I was not able to reproduce on the provided in the author's post sample page. For me the rows were announced as 4 as they are.

**Comment by ndeshev** [comment] 2022-08-31 12:44
Hello @ksblklu, 

The "growing" property of the table is also not announced in the speech output of the table control in UI5 Classic :
https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.TableStrictLayout 

As we aim for consistency I will close this issue for now. 

I believe the second reported issue is the same as this one: #5755  you can track the progress of it there.

Best Regards,

Nikolay

**Closed by ndeshev** 2022-08-31 12:44 UTC
Labels: enhancement, ACC, Medium Prio, SF, SF_ACC

**Comment by ksblklu** [comment] 2022-09-05 10:42
Hi @ndeshev 
For the second issue, I think it is not the same as  https://github.com/SAP/ui5-webcomponents/issues/5755, you can verify it [here](https://codesandbox.io/s/agitated-mahavira-bmqr6m?file=/src/App.js).
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/27538066/188430809-8e7ae0f7-eeea-4ffe-b02f-52b3862c1e48.png">
