### ISSUE TITLE
Search Results not inheriting properties

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#1919] opened 2020-07-08 01:17 UTC
**Describe the bug**
When using the ui5-input as a search input and using standard list item for the results, if I add properties such as 
`separators="None"`, `type="Inactive"`, or `class="customClass"` the ui5-li that is rendered in the responsive popover will not inherit these properties. 
**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-8dth3?file=/src/index.js
2. Search "admin"
3. Note in src/index.js the li properties and see how the suggestion items being rendered do not inherit the properties. As the items are clickable and have a separator line

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-8dth3?file=/src/index.js

**Expected behavior**
ui5-li components rendered in the responsive popover should inherit the properties from the standard list item. 

**Screenshots**
![ui5-input bug example](https://user-images.githubusercontent.com/38701667/86862431-06c1d500-c07e-11ea-88a8-f108529637bc.PNG)

**Context**
- UI5 Web Components version: 0.21.6
- OS/Platform: Windows 10
- Browser *(if relevant)*: All, but tested on Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by ilhan007** [comment] 2020-07-08 04:50
**Regarding the separators:**
Now I see why the separators thing is not working, the item (ui5-li) does not have a property "separators". The List (ui5-list) has such a property. However, the List is internally used to show the suggestions and there is no way to control it with the current API.

**Comment by ilhan007** [comment] 2020-07-08 05:29
**Regarding the type:** https://github.com/SAP/ui5-webcomponents/pull/1921

Now the Input suggestions can be from type="Inactive".

Note: the inactive items can't be selected neither with the mouse, nor with the keyboard.
Note: the inactive items produces empty string in the input field, when previewed with the UP/DOWN arrow keys, the same way as the group header item, as both are not selectable

Is it what you expect?

**Comment by ilhan007** [comment] 2020-07-08 06:27
It turns out that by design the the suggestion list should be separators="None" as you want to set, not "Inner" as it is currently. Would it be fine to set it to "None" internally or you still need the ability to change it to "Inner" and "All".

**Comment by ilhan007** [comment] 2020-07-08 06:52
Regarding the separators:  https://github.com/SAP/ui5-webcomponents/pull/1922
The change includes:
- adding suggestionSeparators getter that can overwritten in order to have different separators type
- changing the default separators type of the suggestion list to "None" as in classic UI5

So, now the default separators type are "None", to have different type you can inherit the Input and overwrite just one getter as shown:

```js

import Input from "@ui5/webcomponents/dist/Input.js";

const metadata = {
	tag: "ui5-custom-input",
};

class CustomInput extends Input {
	static get metadata() {
		return metadata;
	}

	/**
	 * Returns the separators type of the suggestion list
	 * @overridden
	 */
	get suggestionSeparators() {
		return "All"; // "All", "Inner", "None" (by default)
	}
}

CustomInput.define();

export default CustomInput;

**Comment by ilhan007** [comment] 2020-07-08 12:59
**Regarding setting  "class" on the suggestion item**

Indeed, the class attribute is not forwarded inside the Shadow DOM to the internal list items. But even forwarded, the styles this class normally would apply won't work, because in order to work they need to be inserted into the Shadow DOM.

So, to allow full control on the list and list items appearance, to add styles and make customizations, we have merged the following change: https://github.com/SAP/ui5-webcomponents/pull/1928

The change provides a HBS partial within the InputPopoverTemplate, this is the template representing the list with the suggestion items inside the popover that opens under the input field.

Here are the two steps needed:

(1) You can reuse the InputPopoverTemplate.hbs and overwrite the partial in your  CustomInputPopoverTemplate.hbs, to completely replace the list with your own, or to add classes and styles to the items:

```js
// CustomInputPopoverTemplate.hbs
{{>include "InputPopoverTemplate"}}

{{#*inline "suggestionsList"}}
	<ui5-my-list>
	</ui5-my-list>
{{/inline}}

```

(2) And this is the way to register your CustomInputPopoverTemplate.hbs

```js

import Input from "@ui5/webcomponents/dist/Input.js";
import  CustomInputPopoverTemplate from "./generated/templates/ CustomInputPopoverTemplate.lit.js";

const metadata = {
	tag: "ui5-custom-input",
};

class CustomInput extends Input {
	static get metadata() {
		return metadata;
	}

	static get staticAreaTemplate() {
		return  CustomInputPopoverTemplate;
	}
}

CustomInput.define();

export default CustomInput;
```

**Closed by ilhan007** 2020-07-08 12:59 UTC

**Comment by allen138** [comment] 2020-07-08 17:21
> Note: the inactive items can't be selected neither with the mouse, nor with the keyboard.
> Note: the inactive items produces empty string in the input field, when previewed with the UP/DOWN arrow keys, the same way as the group header item, as both are not selectable

> Is it what you expect?

Yes, If the search query returns nothing, then we display a "There were no results" message as a suggested item, but this item should not be selectable. Also, if the query returned an error, we display that as well as a suggested item, but that should also not be selectable.

**Comment by allen138** [comment] 2020-07-08 17:31
Thanks @ilhan007 for the quick response. The details here and the fixes will be a great help!
