### ISSUE TITLE
[ui5-wizard][ui5-textarea]: ui5-content-native-scrollbars not take effect for ui5-wizard and ui5-textarea

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#9695] opened 2024-08-15 08:36 UTC
### Bug Description

ui5-content-native-scrollbars not take effect for ui5-wizard and ui5-textarea

### Affected Component

ui5-wizard, ui5-textarea

### Expected Behaviour

when set ui5-content-native-scrollbars, should use browser native scrollbar

### Steps to Reproduce

open wizard sample https://stackblitz.com/edit/github-nnzvzv?file=src%2FApp.tsx,src%2Findex.css
you will see three components not to use native scrollbar

### Log Output, Stack Trace or Screenshots

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/0dd48053-b1d9-4324-b4ec-f8b1ff641dc5">
<img width="1357" alt="image" src="https://github.com/user-attachments/assets/1d3e7ddc-2f69-4777-861d-5937a85f44e1">

### Priority

None

### UI5 Web Components Version

1.24.x

### Browser

Chrome

### Operating System

MAC OS

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment] 2024-08-20 08:21
Hello @GongRichard,

Could you please create a separate issue for the ui5-list component? This component is managed by a different team.
Thanks in advance!

Kind regards,
Yana

**Comment by GongRichard** [comment] 2024-08-21 14:08
Hi @yanaminkova ,
separate issue for the ui5-list has been created.
https://github.com/SAP/ui5-webcomponents/issues/9720
Thanks,
Richard

**Comment by yanaminkova** [comment] 2024-08-21 17:18
Hello @SAP/ui5-webcomponents-topic-rl ,

Could you please review the issue with the `ui5-content-native-scrollbars` not applying correctly to the `ui5-wizard` and `ui5-textarea` components?

Thanks and Best regards,
Yana

**Comment by ivoplashkov** [comment] 2024-09-24 16:27
Hello @GongRichard ,

The issue is fixed with the changes mentioned above.

Regards,
Ivaylo Plashkov

**Closed by ivoplashkov** 2024-09-24 16:27 UTC
Labels: bug, Medium Prio, TOPIC RL, SAP SF
