### ISSUE TITLE
[sap.ui.webc.main.ComboBox]: Popover doesn't close

### ISSUE THREAD

**Issue by AnitaDixit** [SAP/ui5-webcomponents#7430] opened 2023-08-10 08:43 UTC
### Bug Description

**Actual Behaviour** : The combo box doesn't close up when you click outside the dropdown list.

This issue occurs in SAPUI5 version 117 and it works fine for other versions. 
The same behaviour is seen in MultiComboBox , Time Picker for now.

### Expected Behaviour

**Expected Behaviour** : The combo box closes up

### Steps to Reproduce

**URL  -** https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.ui.webc.main.ComboBox/sample/sap.ui.webc.main.sample.ComboBox

**Steps to reproduce :**

1. Launch the above URL

2. Select one from the combobox 

3. Click outside the list 

### Priority

None

### UI5 Web Components Version

117 onwards

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment] 2023-08-10 10:09
Hello @SAP/ui5-webcomponents-topic-rl ,

Please have a look.
The issue is reproducible for the nighty build, but it is not reproducible when sapui5 version is changed to lower (1.114 for example).
Also I can't reproduce it in the Story book samples: https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/main-combobox--basic

Maybe the issue is already fixed?

Best Regards,
Lidiya

**Comment by vladitasev** [comment] 2023-08-10 12:49
This will be fixed with an upcoming PR. Not related to the webcomponents themselves, but is a bug with the retrofit (cyclic dependencies).

**Closed** 2023-09-11 06:57 UTC
Labels: bug, Medium Prio, TOPIC RL, Retrofit
