### ISSUE TITLE
[IllustratedMessage]: Old Illustration Image is showing after version upgrade

### ISSUE THREAD

**Issue by vdhyutidhara** [SAP/ui5-webcomponents#9071] opened 2024-05-27 12:45 UTC
### Describe the bug

Hi,
When I am importing any specific illustration like
import "@ui5/webcomponents-fiori/dist/illustrations/tnt/SessionExpiring.js";
old version of Illustration is rendering 
![001](https://github.com/SAP/ui5-webcomponents-react/assets/62155169/406f91b2-ca4b-4aec-ba26-bbf6d8c01eb9)

But when I used in my React Components
import "@ui5/webcomponents-fiori/dist/illustrations/AllIllustrations.js";
proper illustration is rendering
![Screenshot 2024-05-27 181322](https://github.com/SAP/ui5-webcomponents-react/assets/62155169/6c438120-0fd9-4c18-ae33-a7d87681b210)

Currently, I am using the latest version of UI5 webcomponents
    "@ui5/webcomponents": "1.24.3",
    "@ui5/webcomponents-fiori": "1.24.3",
    "@ui5/webcomponents-react": "1.28.4"

### Isolated Example

https://codesandbox.io/p/sandbox/test-ui5-lw7dvv?file=%2Fpackage.json%3A13%2C1-15%2C41

### UI5 Web Components for React Version

1.28.4

### UI5 Web Components Version

1.24.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment] 2024-05-28 07:40
Hello @vdhyutidhara ,

While we work on resolving this issue, I recommend using the `AllIllustrations` import. Please note that using this import won't have significant impact on performance, as the module ensures that only the used illustrations are fetched.
 
import "@ui5/webcomponents-fiori/dist/illustrations/AllIllustrations.js"

I hope this is sufficient for you.

Regards,
Plamen Ivanov

**Comment by plamenivanov91** [comment] 2024-05-28 08:19
Closing this issue is as duplicate of this one:
https://github.com/SAP/ui5-webcomponents/issues/8145

Regards,
Plamen Ivanov

**Closed by plamenivanov91** 2024-05-28 08:19 UTC
Labels: bug, duplicate
