### ISSUE TITLE
SegmentedButton onSelectionChange listener not firing when selected tab gets not changed by click

### ISSUE THREAD

**Issue by codingfabi** [SAP/ui5-webcomponents#4969] opened 2022-03-25 15:54 UTC
### **Bug Description**
I'm rendering a SegmentedButton with several toggle buttons as children working as tabs. We have linked text on our application that changes the selected button on click. If we fire this event and a certain tab gets selected, we can not reselect the tab that was selected before. Instead, we need to select a different tab to be able to navigate to the first one. This is because the tab selection by the link click does not trigger the selectionChange listener of the SegmentedButton since it only listens to onClick. So when we reselect the first tab, the SegmentedButton does not register a selectionChange.

### **Expected Behavior**
I would expect the selectionChange of the SegmentedButton to observe on childrenMutation, not on click only. So maybe change it to a mutationObserver.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Priority**
- [ ] Low
- [x] Medium (functional issue)
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {UI5-webcomponents-for-react}

**Comment by gmkv** [comment] 2022-03-25 16:04
Hi @SAP/ui5-webcomponents-topic-b 
Codingfabi is using the SegmentedButton component and programatically changing whether one of the SegmentedButtonItems is selected or not. Changing the state programatically does not cause the selectionChange event to fire.

Usually events should fire based on the user's actions - keypresses, taps, clicks, etc.
Would you have a look?

Regards,
Georgi

**Comment by codingfabi** [comment] 2022-03-25 16:12
I created a sandbox that reproduces the issue in an abstracted form: https://codesandbox.io/s/ui5-webcomponents-forked-4futgz?file=/src/index.js

Click on the link selects the third SegmentedButtonItem. Reselecting "Map" afterwards results in both Items to be selected. Hope this adds a bit of clearity.

**Comment by gmkv** [comment] 2022-03-25 16:30
The issue is actually that the SegmentedButton could fall in a state where it can have more than one button selected at a time, which seems like a valid bug.

**Comment by NHristov-sap** [comment] 2023-02-15 11:57
Hi @codingfabi ,
In general, the events are fired only after user interactions (as click/tap/etc). So you can't expect that if you change something programatically, the event will be fired after that. In situations that you change some state programatically, it is assumed that you know what you do, and you have information about the state of the component.
That's why this complaint is not valid.
On the other hand, there is a bug in the segmented button that messes up the pressed state of the button items, and it is addressed and will be fixed soon with this pull request (#6502). 

Best Regards,
Nikolay Hristov

**Closed** 2023-02-16 12:13 UTC
Labels: bug, Medium Prio, TOPIC B
