### ISSUE TITLE
ui5-link lost it's focus when user clicks the ui5-link and opens another tab, then click the originating tab

### ISSUE THREAD

**Issue by boyetp123** [SAP/ui5-webcomponents#3478] opened 2021-06-29 00:13 UTC
when a ui5-link is click by the user and opens another browser's tab (target="_blank")  
Expected:
when the user clicks the originating tab, the last  clicked link should be on focus

Observe:
when the user clicks the originating tab, the last clicked link is not on focus, this is an acessibility issue

**Comment by plamenivanov91** [comment] 2021-06-29 09:10
Hello @boyetp123 ,

I tried to reproduce the issue but I couldn't.

Here is what I tried and it works as expected:

1. Visit https://sap.github.io/ui5-webcomponents/playground/components/Link/
2. Click the **Standard Link** link (first link on the Link sample subview)
3. A new page is open ( https://www.sap.com/index.html )
4. Go back to the original tab
5. **Standard Link** is focused

The link DOM element has its **target** attribute set to **_blank** as described in your use case.

Could you verify that everything is working as expected?

Regards,
Plamen Ivanov

**Comment by boyetp123** [comment] 2021-06-29 09:49
Hi there, the issue is very reproduceable.

Just like a regular anchor tag with a target of _blank this will open a mew tab. Then go back to he previious tab. And check the link that you just click.

Is it in focus?

**Comment by plamenivanov91** [comment] 2021-06-29 09:52
Hello @boyetp123 

Yes it is.

Did you tried to reproduce it with my described steps ?

Regards,
Plamen Ivanov

**Comment by boyetp123** [comment] 2021-06-29 10:43
Hi Plamen,

The link works just fine except for the link does not get the focus when the user goes back ro the original tab

**Comment by plamenivanov91** [comment] 2021-06-29 12:02
Hello @boyetp123 ,

I created a video which proves my point from my first comment.

https://user-images.githubusercontent.com/13866865/123793118-0b644680-d8ea-11eb-8663-7565ba263f10.mp4

Here is my work environment:
"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

I also contacted one of my colleagues which uses MacOS and he doesn't experience any issues.

If you are using phone, it's not expected to see focus.

If you want us to proceed investigating the issue, please provide a working code snippet in here https://codesandbox.io/.
You can also provide your exact work environment information as I did above.

I am afraid I'll have to close this issue if you don't do so.

Regards,
Plamen Ivanov

**Comment by ilhan007** [comment] 2021-07-23 10:22
Closing the issue due to inactivity. Feel free to comment with more details and we will re-open the issue.

**Closed by ilhan007** 2021-07-23 10:22 UTC
Labels: author action
