### ISSUE TITLE
TextArea: max length text is cut short when using rows=1

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#4623] opened 2022-01-24 17:26 UTC
Related to https://github.com/SAP/ui5-webcomponents/issues/4142

**Describe the bug**
TextArea's max length text is cut short when using rows=1

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--default-story

**To Reproduce**
1. Go to `ui5-webcomponents-react` [TextArea playground](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--default-story)
2. Change the following properties: `rows='1'` and `maxlength='100'`
3. See how `100 characters remaining` text is cut short

**Expected behavior**
Max length to be fully displayed height-wise

**Screenshots**
<img width="714" alt="Screen Shot 2022-01-21 at 10 33 56" src="https://user-images.githubusercontent.com/11576789/150833228-ce5388fc-d0d0-4263-8f1e-0c9616b4f573.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: @ui5/webcomponents-react - v0.20.2

**Comment by LidiyaGeorgieva** [comment] 2022-01-25 12:45
Hello colleagues,

Please have a look at this issue. 
Here is isolated sample of it: https://codesandbox.io/s/ui5-webcomponents-forked-79cj6?file=/index.html

Best Regards,
Lidiya

**Comment by niyap** [comment] 2022-01-25 14:52
Hello @rchrdchn,

As you know, the issue was already fixed with the following change: https://github.com/SAP/ui5-webcomponents/pull/4152/
I checked the sample provided by Lidiya, changing the web components version to 1.1.0: https://codesandbox.io/s/ui5-webcomponents-forked-kozkd and the issue is not reproducible anymore.
I checked here as well: https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--default-story adding "show-exceeded-text", rows = "1" and maxlength=100 as mentioned by you and the issue is not reproducible as well. I am attaching a screenshot.
<img width="1103" alt="Screenshot 2022-01-25 at 16 06 07" src="https://user-images.githubusercontent.com/38278268/150999583-b7a63617-37de-4763-a2e3-c8737d82dfba.png">

Could you please provide me a reference to the dialog from your screenshot if you are able to reproduce it there? Also, please check the version used and whether the fix is available there.

Thank you in advance!

Kind Regards,
Niya

**Comment by MapTo0** [comment] 2022-02-01 13:46
Since this is fixed, I am closing the issue.

**Closed by MapTo0** 2022-02-01 13:46 UTC
Labels: bug, Medium Prio, TOPIC RL, author action
