### ISSUE TITLE
[dialog/popover/etc]: async actions are blocking tests

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#7068] opened 2023-05-22 11:03 UTC
### Bug Description

When using dialog/popover/etc. in tests, it's causing failing of tests that follow

![image](https://github.com/SAP/ui5-webcomponents/assets/32869456/b73db60d-0a50-4f7c-aaad-78d57ae37b89)

### Affected Component

popovers/dialog/modal

### Expected Behaviour

Tests should not fail

### Steps to Reproduce

1. Write a test in jest/cypress using dialog/popover
2. open the component in the test
3. write more tests
4. some of the following tests could fails as async actions are finished

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Additional Context

- using ui5-react as wrapper
- could be fixed by using optional chaining? `?`

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment] 2023-05-22 13:07
Hello @rvsia 
Thank you for reporting this.


It's really strange issue that occurs in Cypress tests:
` this.getRootNode(...).getElementById is not a function`

Because according to MDN the this.getRootNode(...) should return the Document or the ShadowRoot in which the element (this) is in, getElementById are present on both.
[ this.getRootNode(...).getElementById is not a function](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode)


In 1.13 we have merged this change that seems we can relate to the issue:
https://github.com/SAP/ui5-webcomponents/pull/6912. It adds async tasks, that could conflict with the Cypress test execution and getRootNode is something completely wrong even by the MDN spec, because of 
Cypress specifics.

So, @rvsia could you at least provide the minimum setup if possible as you described 
- Write a test in jest/cypress using dialog/popover
- open the component in the test
- write more tests
- some of the following tests could fails as async actions are finished
Because it could be that something in the test setup should be changed (I am just thinking out loud)?.


Meanwhile, I will forward the issue to the responsible team to reconsider this change or at maybe call getElementById conditionally (but this is already strange as by design getElementById should be always available)

**Comment by ilhan007** [comment] 2023-05-22 13:08
Hello @SAP/ui5-webcomponents-topic-rd could you take a look at this issue.
I briefed @gmkv already about the context and asked the author for a little more input.

**Comment by rvsia** [comment] 2023-05-23 06:49
@ilhan007 Thank you for the response.

Here is a repo that reproduces the error. Please check readme.md:

https://github.com/rvsia/ui5cypresstest

Note: it doesn't fail all the time and so it is required to run it multiple times

<img width="497" alt="Snímek obrazovky 2023-05-23 v 8 49 07" src="https://github.com/SAP/ui5-webcomponents/assets/32869456/ae7631f0-d3f5-4356-8798-7210d75db209">

**Comment by ilhan007** [comment] 2023-05-23 07:13
Hello @rvsia

I wanted to also ask you if you considered using the https://docs.cypress.io/api/utilities/promise

something like:
```js
function openDialog() {
  return new Cypress.Promise((resolve, reject) => {
    // do something custom here
        await dialog.show();
        resolve()
  })
}
```

and do the asserts after the promise is resolved
```js
 openPopover().then(() => {
      expect...
})
```
maybe then the tests won't fail as awaiting the dialog to complete all async tasks, including the initial focus apply (that the failing `this.getRootNode(...).getElementById` is used for)

**Comment by rvsia** [comment] 2023-05-23 07:19
@ilhan007 Yeah, we got recommended by the React team to use `cy.wait(...)` but I would rather to just use the component without any workarounds. I think it's sensible to add a simple check there.

**Closed** 2023-05-26 06:29 UTC
Labels: bug, TOPIC RD, Signavio

**Comment by ilhan007** [comment] 2023-05-26 10:08
Hello @rvsia the next minor release is planned for the end of next week. 
Would that timeline work for you?

**Comment by rvsia** [comment] 2023-05-26 10:10
@ilhan007 Hello,

yes, of course, thank you so much! 😊
