### ISSUE TITLE
List: Opening a Popover with "Space" fires the `item-click` event of the `List`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#3601] opened 2021-08-05 10:52 UTC
### **Bug Description**
When using an interactive `List` inside a `Popover` and opening the popover with the "Space" key, the `item-click` event is called. This does not happen when opening the popover with different keys or a click.

### **Expected Behavior**
It should be possible to open a popover with any key without firing the `item-click` event of the list.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/great-butterfly-603sb?file=/src/App.js)
2. Press "Tab" to focus the div
3. Press "Enter" to open the popover
4. See that everything works as expected
5. Close the popover and focus the div again
6. Press "Space"
7. See that the `item-click` event is called, closing the popover immediately 

### **Isolated Example**
https://codesandbox.io/s/great-butterfly-603sb?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.0.0-rc.15

**Comment by elenastoyanovaa** [comment] 2021-08-05 11:41
Hello @SAP/ui5-webcomponents-topic-p ,

I think that the issue is related to the List/ListItem press handling. When a button is activated via space/enter it is marked. Even though there are some checks if an event is already marked in some places in the ListItem.js, for _onkeyup there is no such check and therefore item-click is pressed in List.js and the popover closes.

Could you please have a look?

Kind Regards,
Elena

**Comment by nnaydenow** [comment] 2021-08-06 13:07
Hi @Lukas742,

Handling the Space action on keydown is not correct. By standards the actions should be handled in following way:

- Enter => onkeydown
- Space => onkeyup

In the provided snippix both keys are handled on keydown. 
I edited the provided snippix and seems to work correctly:
https://codesandbox.io/s/long-sunset-vnxeo

I'm closing the incident. Please reopen if needed.

Regards,
Nayden

**Comment by Lukas742** [comment] 2021-08-06 13:33
Hi @nnaydenow 

thanks for the quick response, this indeed solves my problem. 

Just out of curiosity, could you point me to an article or post where these standards are defined? I get that it's better in some cases like with inputs to use `onkeyup` because then the value is updated before the event fires, but I don't see that this is the case here.

**Comment by nnaydenow** [comment] 2021-08-06 13:47
Hi @Lukas742 ,

You can check the statements here: https://sapui5.hana.ondemand.com/sdk/#/topic/6b741a6133284bd78e897cef8b75f6d9

Best regards,
Nayden

**Closed by nnaydenow** 2021-08-06 13:47 UTC
Labels: bug, Medium Prio, TOPIC P
