### ISSUE TITLE
ui5-avatar-group: can't show correct focus border when clicking avatar

### ISSUE THREAD

**Issue by JosephineSu** [SAP/ui5-webcomponents#2906] opened 2021-03-04 08:41 UTC
**Describe the bug**

When click avatar in AvatarGroup, the border of avatar show incorrectly.
**To reproduce**
1. Go to url: https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11001
2. click the avatar in the lower-right corner （if not found, click the up-left "2020 Goal Plan", and change another goal）

**Isolated example**
![image](https://user-images.githubusercontent.com/38159212/109935293-67d2a300-7d08-11eb-83ea-43bbe6a99850.png)

**Expected behavior**

**Screenshots**

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by fifoosid** [comment] 2021-03-04 12:55
Hi @JosephineSu 

This issue is caused by the positioning in the wrapper div, not by the ```avatar-group``` itself. This issue should be fixed on application level with the necessary CSS:

![image](https://user-images.githubusercontent.com/16850339/109967015-94cb8980-7cf9-11eb-83b3-b74c627991b8.png)

**Closed by fifoosid** 2021-03-04 12:55 UTC
Labels: SF

**Comment by JosephineSu** [comment] 2021-03-17 02:24
OK, Thanks for your reminder.
