### ISSUE TITLE
[ui5-shellbar-item | vue]: ui5-shellbar-item ref value is not usable

### ISSUE THREAD

**Issue by ehni** [SAP/ui5-webcomponents#10261] opened 2024-11-27 09:45 UTC
### Bug Description

Example use case: automatically / programatically open a popover in the shellbar, to e.g. notify users about something.

Problem: the ui5-shellbar-item can not be used as an opener value for the popover as the ui5-shellbar-item is not the actual rendered dom element which is visible in the shellbar. Instead it gets automagically mapped to a ui5-button element in the shadow dom which is not accessible.

I have prepared an example repository which demonstrates my described issue, as it might not be easy to understand my problem.

Here you can find the repository: https://github.com/ehni/vue-ui5-webcomponents-playground

### Affected Component

ui5-shellbar-item

### Expected Behaviour

ui5-shellbar-item should be the item which is rendered in the dom so that it can be used programatically.

### Isolated Example

https://github.com/ehni/vue-ui5-webcomponents-playground

### Steps to Reproduce

1. `checkout repo && nom i && npm run dev`
2. Open page in your browser
3. Try to open the second popover by any kind of javascript code without any user interaction.
...

### Priority

High

### UI5 Web Components Version

2.2.0

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment] 2024-11-28 15:18
Hi @SAP/ui5-webcomponents-topic-p,

The issue is reproducible on the demo app provided above - ui5-shellbar-item indeed cannot be used as a popover opener, whereas for items slotted into the shellbar there is no issue.

Could you please take a look at this?

Best regards,
Siyana

**Comment by NakataCode** [comment] 2024-11-29 11:37
Hello @ehni,

The ui5-shellbar-item cannot be directly used as an opener for the ui5-popover because it is not the actual rendered DOM element. Instead, the ui5-shellbar maps the ui5-shellbar-item to a ui5-button internally, which resides in the shadow DOM. This ui5-button is the visible, interactable element in the UI.

Since the ui5-popover requires a visible DOM element as its opener, and the ui5-shellbar-item is only a logical abstraction, it cannot be directly used programmatically.

### Solution
To resolve this issue, you can use the getDomRef() method of the ui5-shellbar-item to retrieve the actual ui5-button created in the shadow DOM. This button can then be passed as the opener for the ui5-popover.

Here’s the adjusted function:
```js
function openPopover2() {
  if (popover2.value) {
    popover2.value.opener = button2.value.getDomRef();
    popover2.value.open = true;
  }
}
```

Best regards,
Nikola

**Comment by pskelin** [comment] 2024-12-02 18:09
@ehni unfortunately we don't have documentation for the `@ui5/webcomponents-base` package, especially the `UI5Element` base class which all components extend. Best you can try is to look at github, this method is public and has a JSDoc.
https://github.com/SAP/ui5-webcomponents/blob/9114a82ecc14ae3dbf118bd8ad835a6a16949298/packages/base/src/UI5Element.ts#L902-L907

There is however a change, which makes the popover internally calls this method (or rather `getFocusDomRef`), so you won't have to know about it.
https://github.com/SAP/ui5-webcomponents/pull/10140

It will be part of 2.5.0 which will be released later this week, you can also try it by installing `@2.5.0-rc.2` or `@next`. 

It still has a bug though - it only works if opener is a string reference to an element with such id. Should be a bit easier even. Just add id
```vue
    <ui5-shellbar-item
      id="button2"
      ref="button2"
```

and use it
```vue
function openPopover2() {
  if (popover2.value) {
    console.log("button2.value is: ", button2.value);
    popover2.value.opener = "button2"; // <-- id
    popover2.value.open = true;
  }
}
```

@ilhan007 the `Popover.getOpenerHTMLElement` method returns the actual opener if it is an HTMLElement
```ts
	getOpenerHTMLElement(opener: HTMLElement | string | undefined): HTMLElement | null | undefined {
		if (opener === undefined || opener instanceof HTMLElement) {
			return opener;
		}
```
It should check if it is a UI5Element and call the `getFocusDomRef` as in the id case. What do you think?

**Comment by NakataCode** [comment] 2024-12-18 10:12
Hello,

I am closing this issue for now. If you have further questions or concerns, feel free to reopen it, and they will be addressed promptly.

**Closed by NakataCode** 2024-12-18 10:12 UTC
Labels: bug, Medium Prio, TOPIC P
