### ISSUE TITLE
List: NoDataText attribute doesn't show text on screen

### ISSUE THREAD

**Issue by gibiovana** [SAP/ui5-webcomponents#2468] opened 2020-10-19 13:54 UTC
**Describe the bug**
Using a List, the NoDataText attribute should show a message on the screen when the list is empty. The current behaviour does not show anything. 

**Isolated Example**
In the UI, we are showing a list of Cards. But when there is nothing to show and the list is empty, there is no message on the screen.

**To Reproduce**
1. Create a List
2. Add 'noDataText' with any String
3. There should be no text in the UI

**Expected behavior**
When I have an empty list, there should be a message, using NoDataText

**Screenshots**
UI:
![Screen Shot 2020-10-19 at 10 39 46](https://user-images.githubusercontent.com/42900300/96459482-8c662c80-11f8-11eb-9fae-aa23b0d4beaa.png)

The List using NoDataText:
<img width="506" alt="Screen Shot 2020-10-19 at 10 50 40" src="https://user-images.githubusercontent.com/42900300/96459862-faaaef00-11f8-11eb-81ce-3cb0da0d5ca0.png">

The empty list without the text:
![Screen Shot 2020-10-19 at 10 40 58](https://user-images.githubusercontent.com/42900300/96460052-33e35f00-11f9-11eb-9490-c40899b20d74.png)
![Screen Shot 2020-10-19 at 10 53 13](https://user-images.githubusercontent.com/42900300/96460261-68571b00-11f9-11eb-8801-39494b15a2fb.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.0.0-rc.8
`@ui5/webcomponents-react` version:^0.10.9
Operating System: MAC OS 
Browser: Chrome

**Comment by nazarkulyk** [comment] 2020-11-12 11:52
@MarcusNotheis here an angular example for that:

[https://codesandbox.io/s/crazy-frog-07cqk]

to reproduce.

**Comment by fifoosid** [comment] 2020-11-12 15:35
Hi everyone,

1. When it comes to Angular, I found two things. First of all the syntax in the provided codesandbox is not correct. When you are binding a property, you don't need the square brackets around the variable name. Those are only needed when it comes to interpolation.  Secondly, when you need to bind a kebab-case property, you need to convert it to camelCase. In our case, this means that the code for the ```ui5-list``` would look like this:

```html
<ui5-list
    class="full-width"
    header-text="Products"
    [noDataText]="noDataText"
    separators="None"
  ></ui5-list>
```

The same logic should apply if we want to bind the ```header-text``` property of the list.

2. When it comes to pure React + UI5 Web Components, looks like everything is working as expected. The following code snippet works:

```html
 <ui5-list
          class="full-width"
          header-text="Products"
          no-data-text={noDataText}
          separators="None"
        ></ui5-list>
```

Moreover, the exact snippet from the initial issue works on my side as well on the current master version of UI5 Web Components:

```html
 <ui5-list
          class="full-width"
          header-text="Products"
          no-data-text={'Some Cool Text here'}
          separators="None"
        ></ui5-list>
```

3. When it comes to pure React + UI5 Web Components for React, everything seems to work as expected as well:
https://codesandbox.io/s/wandering-grass-ve3y1?file=/src/App.js

I am closing the issue as everything seems to work as expected. If you think that I am missing something, please reopen the issue.

**Closed by fifoosid** 2020-11-12 15:35 UTC
