### ISSUE TITLE
Weird "deletion" of values in input field

### ISSUE THREAD

**Issue by Flora-manda** [SAP/ui5-webcomponents#4410] opened 2021-12-01 17:10 UTC
### **Bug Description**
When values are typed in an input field (multi-input in this case) and the cursor is placed in the middle, clicking on the delete button on the keyboard deletes one or two values then after the cursor jumps forward to end of the text value.

### **Expected Behavior**
Should delete only previous values behind cursor and not jump forward.

### **Steps to Reproduce**
1. Go to sandbox: https://codesandbox.io/s/bitter-brook-4c9hw?file=/src/App.js
2. Enter values say "123456789101112..."
3. Place cursor in the middle and hit the "del" button on your keyboard
4. It starts to delete the previous value or values and then abruptly jumps forward to the end of the line
5. Issue is only present in Safari, Chrome works fine (not sure about Mozilla)

### **Log Output / Stack Trace / Screenshots**
https://user-images.githubusercontent.com/37485131/144280614-01c19730-f034-439a-83ee-1dbf004d1332.mov

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP

**Comment by gmkv** [comment] 2021-12-02 08:50
Hi @SAP/ui5-webcomponents-topic-rl 
In Safari, there is a bug with the input components where editing the middle of a value will cause the cursor to be placed at the end.
Issue is reproducible when either deleting or typing characters from anywhere but the end of the string.

The video that Flora attached shows this.
Can be reproduced [here](https://codesandbox.io/s/ui5-webcomponents-forked-61lc5?file=/index.html).

Regards,
Georgi

**Comment by MapTo0** [comment] 2021-12-07 21:37
Looks like this is a browser issue ... I will report to vendor and try to provide a fix https://jsbin.com/duyowebohi/1/edit?html,output

**Comment by MapTo0** [comment] 2021-12-08 15:10
I tested the issue using Safari Technology Preview and the issue looks like fixed from Apple. @Flora-manda could you please confirm?

**Comment by MapTo0** [comment] 2021-12-13 12:57
The problem has been fixed by Apple (tested in Safari Technology Preview),  I am closing the issue.

**Closed by MapTo0** 2021-12-13 12:57 UTC
Labels: bug, Medium Prio, TOPIC RL

**Comment by Flora-manda** [comment] 2021-12-15 13:47
Yes all good on my end too with Safari :)

Thank you !
