### ISSUE TITLE
Improve two way data binding support in Angular

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#526] opened 2019-06-10 08:11 UTC
**To reproduce**
Use input controls with two way data binding.

**Expected behavior**
Two way data binding works out of the box for all controls.

**Comment by MapTo0** [comment] 2019-08-07 12:53
Duplicate of https://github.com/SAP/ui5-webcomponents/issues/651

**Closed by MapTo0** 2019-08-07 12:53 UTC
Labels: duplicate
