### ISSUE TITLE
ui5-date-picker: calendar date announcement is not right

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2344] opened 2020-10-12 09:52 UTC
**Describe the bug**
Calendar date announcement of ui5-date-picker is not right.

**To reproduce**

1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. select a new satus 'low'
6. open date picker for 'Achieved On'
7. With JAWS ON, verify the calendar date announcement

Actual Results:
1. when calendar modal is opened, JAWS does not announce the title for modal window
2. Day is not announced for the date selected.
3. Current date is visually seen highlighted with pink color border but same is not announced to screen reader users.
![date picker issue](https://user-images.githubusercontent.com/13098801/95732684-a90fdb00-0cb3-11eb-9d4f-46f994adf4e6.png)

**Expected behavior**
1. When calendar modal window is opened it should be announced as Modal dialog calendar.
2. Relevant day of the week should be announced. For example Tuesday September 22,2020
3. Current date should be announced as today. For example Today September 21,2020
![sapui5 date picker](https://user-images.githubusercontent.com/13098801/95732647-9b5a5580-0cb3-11eb-998c-cc50942408e9.png)

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {IE}
- Other information: {JAWS}

**Comment by ilhan007** [comment] 2020-10-28 09:02
Hello @GongRichard it turns out the issues you have are fixed in the master with this PR
https://github.com/SAP/ui5-webcomponents/pull/2224 
so we have to provide the fix in the SF branch and make a new release

**Comment by ilhan007** [comment] 2020-11-02 13:36
Hello @GongRichard the PR #2224 has been released with 0.23.6, it improves the DatePicker's accessibility and the responsible team  @SAP/ui5-webcomponents-topic-b confirmed that the PR address all the acc related issues in the current issue.

**Closed by ilhan007** 2020-11-02 13:36 UTC
Labels: ACC, High Prio, SF, TOPIC B
