### ISSUE TITLE
[UI5-Dialog][Bug][SF][Urgent] The focus should always be inside the ui5-dialog

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3152] opened 2021-04-15 05:30 UTC
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Bug Description**
Version: 0.29.13
When we open the dialog ( ui5-wizard inside ), if we press the TAB key continuously, the focus should always inside the ui5-dialog. But  in fact, the focus will go outside of ui5-dialog

**Expected behavior**
When we open the dialog ( ui5-wizard inside ), if we press the TAB key continuously, the focus should always inside the ui5-dialog. 

**Reproduce step:**
1. go to website: https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click "skip tour button" to close the first time guidance dialog
3. click "Cascade Goal" button to open cascading dialog
4. press the TAB key continuously, the focus should always inside the ui5-dialog. 

You can see the below GIF
![weqweqweqwe](https://user-images.githubusercontent.com/78520316/114818601-a02ccd00-9dee-11eb-8404-f7955113ce94.gif)

**Comment by alexandar-mitsev** [comment] 2021-04-19 10:29
Hello @sfsf-xweb-sh ,

Similarly to issue #3151 , could you please add source maps to the application or modify this isolated sample in [JSBIN](https://jsbin.com/sewiputoga/1/edit?html,output) to reproduce the issue. Having a wizard in a dialog does not reproduce the issue on its own.

This way we will be able to process the issue further and to debug what is the root cause for the behaviour.

Thanks and Regards,
Alexandar

**Comment by sfsf-xweb-sh** [comment] 2021-04-21 01:53
> Hello @sfsf-xweb-sh ,
> 
> Similarly to issue #3151 , could you please add source maps to the application or modify this isolated sample in [JSBIN](https://jsbin.com/sewiputoga/1/edit?html,output) to reproduce the issue. Having a wizard in a dialog does not reproduce the issue on its own.
> 
> This way we will be able to process the issue further and to debug what is the root cause for the behaviour.
> 
> Thanks and Regards,
> Alexandar

I will send email to you and give you the repo

**Comment by alexandar-mitsev** [comment] 2021-04-23 07:16
Hi,

Since the wizard is wrapped in a busy indicator, maybe the bug is the same as #3181.
Still it is important to have the source maps.

Regards,
Alexandar Mitsev

**Comment by sfsf-xweb-sh** [comment] 2021-04-23 09:19
Hi @alexandar-mitsev 

It Is hard to give the source map in public GitHub page.
Can you access our project's repo ?

**Comment by sfsf-xweb-sh** [comment] 2021-04-26 08:07
Hi @alexandar-mitsev  @ilhan007  @fifoosid 

You can see this demo link:https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
I have submitted the source-map to it

**Comment by fifoosid** [comment] 2021-05-07 10:47
The issue is resolved with #3189, which is downported in 0.29.x & 0.31.x branches

**Closed by fifoosid** 2021-05-07 10:47 UTC
Labels: SF, bug

**Comment by ilhan007** [comment] 2021-05-10 07:04
Hello @sfsf-xweb-sh  fixed with 0.29.15 and 0.31.7
