### ISSUE TITLE
[BUG][SF][ui5-wizard]1. Incorrect calculation of current step position  2. Unexpected navigating to the wrong location automatically.

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#2883] opened 2021-03-01 05:59 UTC
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team. My name is Hubery Shen and this account is our team account.

**Bug Description**
Version: 0.29.9

1.  Incorrect calculation of current step position 
2. Unexpected navigating to the wrong location automatically.

**Reproduce step:**
1. go to website: [https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list](https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list)
2. click "skip tour button" to close the first time guidance dialog
3. click "Cascade Goal" button to open cascading dialog
4. select some goals in select goal list, and then click the next button to enter into step two
5. scroll up a little bit of the cascading goal dialog, and you can see the fact that although the most of dialog is step two, but the wizard will highlight the step one button. this is an issue, because the current step is still step two
6. When I click the **by search** button, the wizard will navigate to step one automatically unexpectedly. It should still focus in step two and do not change the scroll height of wizard

**Expected behavior**
1. Calculate the step correctly. If I scroll up a little bit of step two ( the most of the screen is step two ), highlight the correct step icon.
2. Do not automatically navigate the page to the wrong step when some event be triggered or some button in wizard be clicked.

![wizard-calc](https://user-images.githubusercontent.com/78520316/109457672-45395380-7a96-11eb-871c-974e9488da55.gif)

**Comment by ilhan007** [comment] 2021-03-01 08:40
Helllo @sfsf-xweb-sh 


"5.scroll up a little bit of the cascading goal dialog, and you can see the fact that although the most of dialog is step two, but the wizard will highlight the step one button. this is an issue, because the current step is still step two"

When you scroll a little up, you are going back to step 1, because the bottom of step 1 is now in the viewport. The selection of step 1 is expected.

**Comment by ilhan007** [comment] 2021-03-01 15:11
I am processing the issue but FYI @SAP/ui5-webcomponents-topic-rl

**Comment by ilhan007** [comment] 2021-03-27 09:14
The unexpected scrolling to the top is caused by the application code:
 
 ```js
// line:37 SelectGoal.js (goalmanagementx/src/widgets/cascading-goal/components/select-goals/)
useEffect(() => {
    if (steps[currentStepIdx].stepName === StepNames.SelectGoalsStepName && selectAllCheckboxRef.current) {
                 selectAllCheckboxRef.current.focus();  // this causes the scrolling
    }
}, [currentStepIdx, steps]);
 ```
 
Whenever the state changes, f.e. the step changes (from step 2 to step 1) due to user scrolling,
this application code runs. It focuses an element (“select All” checkbox) and the browser automatically scrolls to the element. This is how the browsers works. This scrolling has nothining to do with the Wizard's code.
When the focus method is invoked on an element that is outside of the viewport, browsers automatically scroll that element into view, either to the center (Chrome, Safari) or to the near edge (Firefox, Edge) of the viewport.
To prevent scrolling on focus, the web suggests the preventScroll option – did not try it.
 
As this is not caused by our code, I am closing the issue.

**Closed by ilhan007** 2021-03-27 09:14 UTC
Labels: High Prio, SF, TOPIC RL
