### ISSUE TITLE
[SF_ACC] Carousel Accessibility - Navigating the carousel using the arrow keys does not indicate which slide of the carousel is being navigated to on the screenreader

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#6026] opened 2022-11-08 23:48 UTC
### **Bug Description**
Using NVDA, when the arrow keys are used to navigate to another slide in the carousel, there is no indication in the screen reader about which slide is being navigated to.

### **Expected Behavior**
The screenreader should indicate which slide is being navigated to.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-carousel--default-story
2. Use NVDA
3. Navigate on the carousel using the arrow keys

![Screen Shot 2022-11-08 at 3 45 50 PM](https://user-images.githubusercontent.com/36656306/200700549-05f076e0-c5f6-4813-aa2f-9bfd21d41604.png)

**Comment by unazko** [comment] 2022-11-09 15:46
Hello @SAP/ui5-webcomponents-topic-rd,

The issue is reproducible in the playground as well: https://sap.github.io/ui5-webcomponents/playground/components/Carousel/
There is no speech output when a user changes the slides via the left/right arrow keys.
For comparison we do have those announcements in for the carousel control in openui5.

Best Regards,
Boyan

**Comment by TeodorTaushanov** [comment] 2022-12-12 07:42
Hi,

The issue is fixed in the main branch.

Best,
Teo

**Closed** 2022-12-12 07:42 UTC
Labels: bug, ACC, Medium Prio, TOPIC RD
