### ISSUE TITLE
Combobox: cannot be accessed with keyboard and when using narrow key the component will crashed

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#3758] opened 2021-08-30 11:15 UTC
**Describe the bug**

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Go to https://codesandbox.io/s/jolly-cache-m1qdc?file=/package.json
2. Press Fn+F4
3. Dropdown list shown up
4. Narrow up and down key pressed, then the component crashed.

**Expected behavior**
Should be accessible with keyboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/131330077-730aec99-00db-43a7-b78e-47f51672a76a.png)
**UI5 Web Components for React Information**

`@ui5/webcomponents` version: 0.31.16
`@ui5/webcomponents-react` version: 0.131.16
Operating System: MacOS
Browser:  Chrome

**Additional context**
From SuccessFactors

**Comment by sleric1024** [comment] 2021-08-30 11:37
Hi @Lukas742, this also occurred in my local environment.
![image](https://user-images.githubusercontent.com/5724592/131333342-2e5a4694-8562-4003-9590-c66fbbe51a0a.png)

**Comment by Lukas742** [comment] 2021-08-30 12:36
I just realised that I didn't reinstall the node-modules when switching to the sf branch. Now after installing it's throwing the same error for me, so it seems like there's a bug in the `0.31.16` version.

**Comment by Shtilianova** [comment] 2021-09-02 10:30
Hello @SAP/ui5-webcomponents-topic-core colleagues,
The issue is not reproducible in the Playground (latest and master), only in the codesandbox. Could you please double check if could be something specific for 0.31.16.
Regards, Diana

**Comment by fifoosid** [comment] 2021-09-07 11:08
HI colleagues, in order to reproduce the issue locally, checkout the ```release-0.31``` branch and reinstall the node modules. Then you can test the issue locally.

**Comment by ilhan007** [comment] 2021-09-20 07:36
Hello @SAP/ui5-webcomponents-topic-rl I am raising the priority, not because of the severity of the issue, but because of  the deadline (approx. end of Sep) for resolving it.

Thank you for your cooperation.

**Comment by ilhan007** [comment] 2021-09-20 09:23
Hello @SAP/ui5-webcomponents-topic-rl I think I got the issue

the method "announceSelectedItem" is used within ComboBox and Input components, this parts of the code have beem probably downported along with other fixes, but the announceSelectedItem implementation has not been downported.

I will handle this issue

**Comment by ilhan007** [comment] 2021-09-20 09:33
Hello @sleric1024 the issue will be fixed with the next patch, thanks for reporting!

**Closed by ilhan007** 2021-09-20 09:33 UTC
Labels: bug, approved, TOPIC RL, SF, Very High Prio
