### ISSUE TITLE
[SF][ui5-multi-input] token-delete event returns wrong token

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#5829] opened 2022-09-19 16:34 UTC
### **Bug Description**
Even though this issue already exists: https://github.com/SAP/ui5-webcomponents/issues/5304, my issue is slightly different.
The other issue is related to selected tokens while in my case, tokens don't have to be selected, clicking on the "x" returns the wrong token as you can see in the following recording (except for the first time):
![Screen Recording 2022-09-16 at 6 29 48 PM](https://user-images.githubusercontent.com/7316793/191067182-740ea82e-e6bd-40e3-8f6c-e141c7df5291.gif)

### **Expected Behavior**
Pressing the "x" button should trigger the `token-delete` event and provide the correct token

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-yc1qbt?file=/src/index.js
2. Click on any "x" on multiple tokens
3. Notice in the message toast that the `token-delete` event returns the wrong token.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-yc1qbt?file=/src/index.js

### **Context**
- UI5 Web Components version: latest
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-multi-input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by plamenivanov91** [comment] 2022-09-20 11:12
Hello @SAP/ui5-webcomponents-topic-rl ,

Although similar issue as #5304, there is slight difference with the reproduction behavior.

If a single fix fixes both of the issues, please feel free to process this one as duplicate.

Regards,
Plamen Ivanov

**Comment by ivoplashkov** [comment] 2022-09-28 06:27
Hello,
 
Excuse us for the delay. The issue is now fixed with this pull request https://github.com/SAP/ui5-webcomponents/pull/5744

Best regards,
Ivaylo

**Closed by ivoplashkov** 2022-09-28 06:27 UTC
Labels: bug, Medium Prio, TOPIC RL, SF
