### ISSUE TITLE
ui5-shellbar: menuPopover is undefined

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4714] opened 2022-02-08 20:53 UTC
### **Bug Description**
If the `_handleResize` is never triggered, then `this.menuPopover` is never initialized, and when clicking an item in the menu it fails on `this.menuPopover.close()`.
The menuPopover does not close and the expected action is not triggered.
The overflowPopover is probably also affected, but not reproducible on the same page because it has a min-width.

This occurs most of the time on one of our pages.

### **Expected Behavior**
Consistent access to menuPopover and overflowPopover.

### **Steps to Reproduce**
1. SuccessFactors Compensation page in qa env
2. Open menuPopover
3. Click item
Observe: nothing happens

### **Context**
- UI5 Web Components version: 1.1.1
- OS/Platform: macOSX 12.1
- Browser: Chrome
- Affected component: ui5-shellbar

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by ilhan007** [comment] 2022-02-09 10:05
Hello @JarrettChan
please provide clear reproducible steps, ideally with pure ui5 web components, using the CodeSandbox https://codesandbox.io/s/71r1x5o51q or at least providing url to the page (if internal information is required - you can use the private Slack channel)

**Comment by JarrettChan** [comment] 2022-02-10 01:15
@ilhan007 I have added reproduction steps to the private Slack channel.

**Comment by MapTo0** [comment] 2022-10-28 08:52
Since the issue could not be reproduced anymore I am closing the issue.

Regards,
Martin

**Closed by MapTo0** 2022-10-28 08:52 UTC
Labels: author action
