### ISSUE TITLE
Avatar fallback is called when not needed

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents#6516] opened 2023-02-16 13:14 UTC
### **Bug Description**
UI5 avatar sets the default icon if the provided initials are invalid or when the initials element's width is bigger than the avatar's. But here's the problem, when that component is used with many others on the same page, in a split second DOM elements exist, but they are empty, width = 0, and the fallback icon gets triggered.

### **Expected Behavior**
It should show the initials but shows the default icon

Codesandbox is [here](https://codesandbox.io/s/adoring-joji-exvqwd?file=/src/app/app.component.html:13378-13381), Look at the line 373 in app.component

**Comment by s-todorova** [comment] 2023-02-16 14:19
Hello @SAP/ui5-webcomponents-topic-p,

Please check the attached Codesandbox. The avatar on line 373 used within a card does not visualise with initials, but with the default icon. On the test page, the issue is reproducible if you create the same structure, in which the avatar is inside a card.
Could you please take a look at this issue?

Kind regards,
Siyana

**Comment by ilhan007** [comment] 2023-02-16 15:19
I think Medium Prio is better as a functional issue, that does not break an app, but still unpleasant, as you expect initials but get icon.

**Comment by yanaminkova** [comment] 2023-03-09 15:18
Hello @g-cheishvili,

We are already working on similar case in the following issue: https://github.com/SAP/ui5-webcomponents/issues/6585

Thanks and Regards,
Yana

**Comment by dobrinyonkov** [comment] 2023-04-05 07:17
Closing this as duplicate of https://github.com/SAP/ui5-webcomponents/issues/6585

**Closed by dobrinyonkov** 2023-04-05 07:17 UTC
Labels: bug, Medium Prio, TOPIC P, Components
