### ISSUE TITLE
[ui5-popover / ui5-dialog]: can't be closed with escape key

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#8337] opened 2024-02-22 15:26 UTC
### Bug Description

`ui5-popover / ui5-dialog` can't be closed with `escape` key (it's only reproducible in storybook context and not in test pages)

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-popover--popover-overview

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment] 2024-03-20 08:49
@kskondov, the issue is not reproducible in the new documentation, so if it's only Storybook sample related, no need to fix it.

**Comment by GerganaKremenska** [comment] 2024-05-16 12:38
Hello @nnaydenow, 

The issue is not reproducible in https://sap.github.io/ui5-webcomponents/components/Popover/, so we are closing the ticket.

Best Regards,
Gergana

**Closed by GerganaKremenska** 2024-05-16 12:38 UTC
Labels: bug, Low Prio, TOPIC RD
