### ISSUE TITLE
DatePicker: Only outter HTML is rendered in Enzyme

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#2153] opened 2020-08-21 09:49 UTC
**Describe the problem**
When I run my UT, which contains the DatePicker in the Enzyme, the DatePicker cannot be well rendered. It only shows an outer tag `<ui5-datepicker>` that contains no children nodes.
![image](https://user-images.githubusercontent.com/4338219/90876780-b2787780-e3d5-11ea-81ea-f69b0c1def1c.png)

As the below picture shows, other components (ui5-checkbox) have shadow DOM while the date picker not.
![image](https://user-images.githubusercontent.com/4338219/90876960-eeabd800-e3d5-11ea-83e6-4167f4054202.png)

I'm not sure whether this is caused by my code or the component. Sorry that my description is a little ambiguous. Could you give me some ideas?

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11
Operating System: MacOS
Browser:Chrome

**Comment by vladitasev** [comment] 2020-08-31 06:01
Hello colleagues, 

it seems the custom element was not upgraded. The most common reason for that is that it was not imported. The second possibility is a JS error that took place and prevented the upgrade from happening. 

There's not much else that comes to mind without a reproducible page we can debug.

Regards,
Vladi

**Comment by SunnyWind** [comment] 2020-08-31 09:00
Hi @vladitasev ,
Thanks for your advice.
I see no JS error on the console, so it should not be the reason.
The element should be imported explicitly since there rendered a tag `<ui5-datepicker>`.

I noticed that the fake XHR from sinon.js can affect the issue. It's strange since the rendering of UI5 components should not include XHR requests, right?

**Comment by ilhan007** [comment] 2020-09-23 16:36
You will always see the <ui5-datepicker tag in Dev Tools (if you meant that) when you use it the html file, no matter you imported or did not the component.  But the presence or the lack of Shadow DOM is a key characteristic. In your case the DatePicker does not have Shadow DOM, which either means the import is missing, or something prevented the component from defining and initialization.

**Comment by ilhan007** [comment] 2021-01-13 05:53
Hello @SunnyWind we are closing the issue, because without a reproducible page we can not do much.

Best regards,
ilhan

**Closed by ilhan007** 2021-01-13 05:53 UTC
Labels: Topic Core, consulting
