### ISSUE TITLE
 [Performance] Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3874] opened 2021-09-09 05:49 UTC
### **Bug Description**

When we test our web page by google LightHouse, and there is an hight level diagnostic warning "Does not use passive listeners to improve scrolling performance" 

Here is link for why https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools

I found that the **ui5-webcomponent** is base on **lit-html**. And also this issue is comes from the **lit-html** below is the source code for it.

https://github.com/lit/lit/blob/e66eb66d9244d019a5d5b17a692a6269b806b552/src/lib/parts.ts#L523

```typescript
commit() {
    while (isDirective(this.__pendingValue)) {
      const directive = this.__pendingValue;
      this.__pendingValue = noChange as EventHandlerWithOptions;
      directive(this);
    }
    if (this.__pendingValue === noChange) {
      return;
    }

    const newListener = this.__pendingValue;
    const oldListener = this.value;
    const shouldRemoveListener = newListener == null ||
        oldListener != null &&
            (newListener.capture !== oldListener.capture ||
             newListener.once !== oldListener.once ||
             newListener.passive !== oldListener.passive);
    const shouldAddListener =
        newListener != null && (oldListener == null || shouldRemoveListener);

    if (shouldRemoveListener) {
      this.element.removeEventListener(
          this.eventName, this.__boundHandleEvent, this.__options);
    }
    if (shouldAddListener) {
      this.__options = getOptions(newListener);
      this.element.addEventListener(
          this.eventName, this.__boundHandleEvent, this.__options);
    }
    this.value = newListener;
    this.__pendingValue = noChange as EventHandlerWithOptions;
  }
```

Maybe in the @ui5/webcomponents to set the `passive` options to the `lit-html`

### **Expected Behavior**

after LightHouse scan, and there  should not  an hight level diagnostic warning "Does not use passive listeners to improve scrolling performance" 

### **Steps to Reproduce**
1.  open this link in chrome browser.     https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail
2.  open the chrome dev tool with tab of `Lighthouse`. 

![image](https://user-images.githubusercontent.com/78520316/132629473-f918f6f1-0b17-4bd7-8479-5779b63c88ba.png)

3. And finally we get the warning result of ` Does not use passive listeners to improve scrolling performance`

![image](https://user-images.githubusercontent.com/78520316/132630257-293a58c4-0712-4652-b6fc-eb15d7f478ab.png)

Here is also a link for installing chrome extension of `Lighthouse`  https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 0.31.12
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SFSF
- Bussiness impact: Performance

**Comment by gmkv** [comment] 2021-09-09 07:00
FYI @SAP/ui5-webcomponents-topic-core

**Comment by fifoosid** [comment] 2021-09-09 11:25
This is a duplicate of #2995

**Comment by sfsf-xweb-sh** [comment] 2021-10-13 02:05
hi, team

is there any updates for this issue?

**Comment by ilhan007** [comment] 2021-11-19 20:52
Hello @sfsf-xweb-sh backlog item created for this issue - can be tracked here: https://github.com/SAP/ui5-webcomponents/issues/2995

Closing this one.

**Closed by ilhan007** 2021-11-19 20:52 UTC
Labels: Medium Prio, SF, TOPIC Core
