### ISSUE TITLE
Input : Double focus is seen when user tries to focus on the icon present inside Input element

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents#8970] opened 2024-05-15 09:39 UTC
### Describe the bug

When I focus on the icon present inside the input field, then the blue outline for focus is seen for the icon as well as the input box. Ideally, the blue outline should be only shown on the icon and not on the input box. This issue has been raised as part of accessibility testing.

### Isolated Example

https://stackblitz.com/edit/github-pzlhay-kxhlew?file=src%2FApp.tsx

### Reproduction steps

1. go to https://stackblitz.com/edit/github-pzlhay-kxhlew?file=src%2FApp.tsx
2. click on the input box to focus on it. One can see the blue outline on the input box
3.click on the 'x' icon to put focus on it. One can see the blue outling on the icon as well as on the input box

### Expected Behaviour

blue outline on input box should not be seen on focus on icon

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/90389521/e43bcd3f-5a0d-42a5-9721-631cfe083f79)

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment] 2024-05-15 13:01
Hello @SAP/ui5-webcomponents-topic-rl , 

When an input is focused and interactive icon is sloted, double focus appears.
![Screenshot 2024-05-15 at 16 01 08](https://github.com/SAP/ui5-webcomponents/assets/22882174/19f3a67b-fa84-4420-aed2-dbbee6535d41)


The issue is reproducible this [isolated](https://stackblitz.com/edit/js-s5z2p9?file=index.html,package.json,index.js,tsconfig.json) example.

Not sure if this should be fixed in the icon or input. I am handing it over to the input owners as the double focus is visible there.

Best Regards,
Gergana

**Comment by ndeshev** [comment] 2024-06-11 11:34
Hello @pppwr7 the `interactive` property of the `ui5-icon` component defines if the icon should be focusable - https://sap.github.io/ui5-webcomponents/nightly/components/Icon/#interactive, and as you pointed out in the description of the issue - it should not be when it is used in а `ui5-input` slot. 

Is there a special reason why you add the 'interactive' property? 
We are planning to add a new slot 'actions' in which the user will be able to add styleable icons with states (hover, press, etc), would that solution suit your case?

**Comment by ndeshev** [comment] 2024-06-14 11:38
Hello, I the issue is no longer producible in the nightly version I will close the issue for now.

**Closed by ndeshev** 2024-06-14 11:38 UTC
Labels: bug, Medium Prio, TOPIC RL

**Comment by pppwr7** [comment] 2024-06-26 03:48
[ndeshev](https://github.com/ndeshev) please let me know the lib versions in the nightly version where the issue has been fixed. Also, we have to set the icon as interactive as we want to perform clear action on click of the icon in the input field
