### ISSUE TITLE
ui5-menu: unstable test

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#5909] opened 2022-10-10 12:39 UTC
Hello colleagues,

I noticed that `Sub-menu creation, opening, closing and destroying` regularly fails when PR is created even if the change is not related to the `ui5-menu` component.

![image](https://user-images.githubusercontent.com/31909318/194868046-0d75a6c5-c9c2-4007-b387-0ae92923e78c.png)

**Comment by hinzzx** [comment] 2023-06-02 09:26
Hi @nnaydenow ,

I tried to reproduce the issue locally without success. I also observed dozen of PRs and it seems the problem no longer persists. Therefore, given that the issue is not currently observable I am closing this issue.

Best Regards,
Stoyan

**Closed by hinzzx** 2023-06-02 09:26 UTC
Labels: bug, TOPIC B
