### ISSUE TITLE
No change event after clearing date-range-picker input field

### ISSUE THREAD

**Issue by cengler69** [SAP/ui5-webcomponents#5465] opened 2022-07-05 14:01 UTC
### **Bug Description**
Hi,

I'm using UI5 web components Date Range Picker in an angular app.
I don't receive the change event after the input field has been cleared a second time.

### **Expected Behavior**
Always receive a change event when the input event has finished

### **Steps to Reproduce**
1. Select a date range in the control ==> change event received
2. clear the input field ==> change event received
3. Select a date range in the control ==> change event received
4. clear the input field ==> **NO** change event received

### **Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker
https://codesandbox.io/s/immutable-moon-w7tsoh?file=/src/App.js (check the console log. After the 4th step the count of the setErrorState does not increase).

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Windows 10
- Browser: Chrome

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by cengler69** [comment] 2022-09-01 12:55
As there is no feedback after almost two month I'm raising the priority to high

**Comment by tsanislavgatev** [comment] 2022-09-19 08:47
Hello @cengler69,

The issue is fixed in the latest version.

Sorry for keeping you waiting.

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2022-09-19 08:47 UTC
Labels: bug, Medium Prio, TOPIC B

**Comment by cengler69** [comment] 2022-10-13 12:24
Hi Tsanislav,
thanks for the update.
To which version are you exactly referring?

The example https://codesandbox.io/s/immutable-moon-w7tsoh?file=/src/App.js using the "latest" webdriver version still shows the problem...

Thanks& Regards,
Christoph
