### ISSUE TITLE
ui5-input: onPaste event not fired in Firefox

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#2719] opened 2021-01-21 15:08 UTC
**Describe the bug**
The `ui5-input` does not fire the `onPaste` event in Firefox, but it does in Chrome and Safari.

**To reproduce**
1. Open https://codesandbox.io/s/immutable-cookies-7x57o?file=/src/App.js in Firefox
2. Paste a text into the UI5 Input
3. Notice the error: no onPaste event fired

**Isolated example**
https://codesandbox.io/s/immutable-cookies-7x57o?file=/src/App.js

**Expected behavior**
`onPaste` event should be fired

**Context**
- UI5 Web Components version: 1.0.0-rc.11
- OS/Platform: MacOS
- Browser *(if relevant)*: Firefox

**Affected components** *(if known)*
- ui5-input

**Comment by ilhan007** [comment] 2021-01-22 09:25
The issue is reproducible in FF only (as stated in the issue description).

Observation:  the inner "input" element, within the Shadow DOM of the Input,  is firing "paste", but the event does not get out of the Shadow DOM (while in Chrome and Safari does).

**Comment by Martotko** [comment] 2021-01-22 11:19
The issue is also reproducible with the TextArea.

**Comment by ilhan007** [comment] 2021-02-03 13:58
Hello @kurellys it turns out this is a browser issue and FF will fix the issue with version 87, that will be released at the end of march -[ 2021-03-22](https://wiki.mozilla.org/Release_Management/Calendar) that is why we decided not to perform any fixes on our side.

**Closed by ilhan007** 2021-02-03 13:58 UTC
Labels: Medium Prio, TOPIC RL, bug
