### ISSUE TITLE
DateTimePicker doesn't allow 12:xx:xx in 24-hour mode

### ISSUE THREAD

**Issue by phil-mitchell** [SAP/ui5-webcomponents#2757] opened 2021-01-30 01:56 UTC
**Describe the bug**
If you set format-pattern="yyyy-MM-dd HH:mm:ss" then it is impossible to enter the 12th (noon) hour in the DateTimePicker.

**To reproduce**
Create a date-time-picker with format-pattern="yyyy-MM-dd HH:mm:ss"
Use the popover to set the hour to 12 and click OK.
The value of the input shows the hour as 00

**Isolated example**
Just look in getTimePickerValues().  It is very obvious:

`const period = periodsSlider ? periodsSlider.value : this.periodsArray[0];`

in 24-hour mode, periodsSlider is null, so period becomes 'AM'

then:

`hours = hours === "12" ? 0 : hours;`

All hours *besides* 12, work properly.

**Expected behavior**
When periodsSlider is null, don't transform the hour at all.

**Context**
- UI5 Web Components version: 1.0.0-rc.11

**Priority:** *High*

DateTimePicker is completely unusable in 24-hour mode.

**Comment by ilhan007** [comment] 2021-02-01 11:38
Hello @phil-mitchell 

Is this your setup, I used your format pattern, but I am able to set 12:00:00 and have it displayed as 12:00:00 in the input field.

```html
<ui5-datetime-picker
   format-pattern="dd/MM/yyyy, HH:mm:ss"
   value="13/04/2020, 11:00:00"
></ui5-datetime-picker>
```
https://user-images.githubusercontent.com/15702139/106453769-75d79e80-6492-11eb-840b-89aba962fba0.mov

**Comment by ilhan007** [comment] 2021-02-01 14:01
Indeed, with RC.11 the issue is reproducible, I prepared a small example 
https://codesandbox.io/s/ui5-webcomponents-forked-kv9bi?file=/index.html:189-316
    
The video above was based on the master code base, so it has been fixed at later stage. The issue will be fixed with the upcoming RC.12 (11 Feb 2021)

**Closed** 2021-04-01 08:24 UTC
Labels: consulting
