### ISSUE TITLE
[Input] [SF] onChange is not fired when use keyboard's up/down to select item and then tab key to focus out the input

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3496] opened 2021-07-09 10:28 UTC
**Describe the bug**
onChange is not fired when use keyboard's up/down to select item and then tab key to focus out the input 

**Isolated Example**
https://codesandbox.io/s/mutable-platform-0mvqx?file=/src/App.js

**To Reproduce**
1. https://codesandbox.io/s/mutable-platform-0mvqx?file=/src/App.js
2. Focus the input and you'll see 2 suggestion items popup
3. Use `down` or `up` key to highlight item (you'll see the input box is filled with the highlighted item)
4. Press `tab` key to focus out the input (DO NOT press `enter` key)

**Expected behavior**
onChange should be fired since the input value is changed and confirmed (however it's not called)

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.12
`@ui5/webcomponents-react` version: 0.131.10
Operating System: macOS
Browser: Chrome

**Comment by gmkv** [comment] 2021-07-12 12:38
Hi @SAP/ui5-webcomponents-topic-rl 
This is an issue with the `ui5-input` not firing a change event when you are browsing the suggestions with arrow keys and then use Tab to focus out.

Isolated: https://codesandbox.io/s/ui5-webcomponents-forked-dob7s?file=/src/index.js

Would you take a look?

Kind regards,
Georgi

**Comment by ndeshev** [comment] 2021-07-29 12:23
Hello @2bno1 

The issue is fixed with #3514

Kind Regards,
Nikolay

**Closed by ndeshev** 2021-07-29 12:23 UTC
Labels: High Prio, SF, TOPIC RL, bug

**Comment by ilhan007** [comment] 2021-08-03 09:10
Hello @2bno1  the fix has been released with 0.31.14
