### ISSUE TITLE
Event bubbling through a shadow DOM boundary

### ISSUE THREAD

**Issue by maltenorstroem** [SAP/ui5-webcomponents#2329] opened 2020-10-08 13:23 UTC
For example, if you use the UI5 input component in a composition (higher level component), then it is not possible to listen to the events of the input component on the composition.
Most events successfully bubble through a shadow DOM boundary. There are few events that do not.
E.g input

When UI5 dispatches custom events, they should set both bubbles and composed properties to true for it to bubble up and out of the component.

As a workaround, all events would otherwise have to be caught in the composition and fired again.

**Comment by ilhan007** [comment] 2020-10-09 07:42
Hello @maltenorstroem could you please provide a small example to reproduce the mentioned bubbling issue.

**Comment by maltenorstroem** [comment] 2020-10-09 08:57
**Example "Why bubbling through a shadow DOM boundary would be nice.**

_Description:_ The furo-ui5-data-text-input-labeled is a composition to easily use a complete input field with label according to the design specification of SAP Fiori Design System.

If you have something like in this code snippet, the events of furo-ui5-data-text-input (extension of ui5-input) are not transported across the border. 
I.e. 
`furo-ui5-data-text-input-labeled.addEventlistener('change', (e)=>{...})` 
will not work.
 ([link to the LitElement component](https://github.com/theNorstroem/FuroBaseComponents/blob/master/packages/furo-ui5/src/furo-ui5-data-text-input-labeled.js))

`<furo-ui5-form-field-container>
        <ui5-label label slot="label" for="Input" show-colon>${this.label}</ui5-label>
        <furo-ui5-data-text-input
          content
          id="Input"
          ƒ-bind-data="--data"
        ></furo-ui5-data-text-input>
      </furo-ui5-form-field-container>`

**Comment by vladitasev** [comment] 2021-10-04 11:20
Duplicate of: https://github.com/SAP/ui5-webcomponents/issues/4037

**Closed by vladitasev** 2021-10-04 11:20 UTC
Labels: TOPIC Core
