### ISSUE TITLE
value and datevalue of DateTimePicker and DatePicker is not consistent

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#5382] opened 2022-06-20 08:12 UTC
### **Bug Description**

The issue can be reproduced in:
https://codesandbox.io/s/ui5-webcomponents-data-picker-bug-report-2-dv1d6w?file=/src/index.js 

When I change date from Jun 8 to Jun 17, the dateValue is still June 8:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/6975707/174555578-9f3f01a4-5570-4a5f-bd2b-711ca13caeb3.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/6975707/174555750-15cd2310-728d-4508-874e-12767b8c7047.png">

### **Expected Behavior**

Expect dateValue and value are both June 17 after change.

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {MacOS}
- Browser: {Chrome}
- Affected component: {DateTimePicker}

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP JAM}
- Business impact: https://jira.tools.sap/browse/DWS-1634 https://jira.tools.sap/browse/DWS-1134

**Comment by tsanislavgatev** [comment] 2022-06-20 12:15
Hello colleagues,

The issue is reproducible after second pick of the date.
The issue might be caused because the date is set after the event is fired, that's why the value is not updated on the time the method is called. This issue is fixed in the date picker, the same pattern can be used.

Best. Regards

**Comment by TinaC** [comment] 2022-06-21 01:34
The second pick of date picker is not what I expected either, `value` is not updated:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/6975707/174697897-cfbd647b-4dc0-4b1d-9e47-392bf5479c67.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/6975707/174697916-2799a96a-273b-48ec-998d-fab66d41ebae.png">

**Comment by TinaC** [comment] 2022-06-21 08:07
I have raised the priority to high as there are customer tickets in our project:
https://jira.tools.sap/browse/DWS-1634

**Comment by tsanislavgatev** [comment] 2022-06-28 12:01
Hello @TinaC ,

The issue about the dateValue of DateTimePicker seems to be fixed in the latest version.
The case with the 'value' of DatePicker and DateTimePicker is expected. As the events are preventable, only the dateValue is updated at the time of the firing of the event, but not the value itself. If you need the value as string, you can take it from the event itself with 'event.detail.value'. 
The dp.dateValue will contain the same value as event.detail.value, but not the same as dp.value, because dp.value is update after the event is fired.

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2022-06-28 12:01 UTC
Labels: bug, Medium Prio, TOPIC B

**Comment by TinaC** [comment] 2022-07-06 07:18
But in date time picker, `value` is updated, `dateValue` is not updated.
In date picker, `dataValue` is updated, but the `value` is not updated, how can this be the expected behavior?
