### ISSUE TITLE
React app breaks when using Screen Reader accessibility extension

### ISSUE THREAD

**Issue by Yoav-Fried** [SAP/ui5-webcomponents#6029] opened 2022-11-09 12:40 UTC
**Describe the bug**
We are required to make our site accessible by making it compatible with the Screen Reader extension. Unfortunately, when the extension is toggled on the DOM is completely broken.

**Isolated Example**
An isolated example [codesandbox](https://codesandbox.io/s/cool-http-2emgkk?file=/src/App.js).
Please download the code, and the [Screen Reader extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) and see how the extension manipulates the DOM.

**To Reproduce**
1. Download the code from [codesandbox](https://codesandbox.io/s/cool-http-2emgkk?file=/src/App.js).
2. Download the code from [Screen Reader extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en).
3. Refresh the app

**Screenshots**
Before toggling accessibility extension - 
![image](https://user-images.githubusercontent.com/47736688/200832316-884db510-064e-4298-bf6a-4c74389cb190.png)

After toggling accessibility extension -
![image](https://user-images.githubusercontent.com/47736688/200832159-593fc012-56c7-471e-82f1-1fa1fa18b400.png)

**UI5 Web Components for React Information**
Operating System: Mac OS
Browser: Chrome

**Comment by unazko** [comment] 2022-11-09 15:53
Hello @SAP/ui5-webcomponents-team,

The issue is easily reproducible via the described steps.
There are errors thrown in the console in the framework CSS styles aren't applied.

Best Regards,
Boyan

**Comment by nnaydenow** [comment] 2024-07-10 07:00
Hi,

When the Screen Reader extension is enabled, adopted style sheets don't work properly, making websites look broken. 

You can reproduce the problem with native web components using adopted style sheets in this example:
https://jsbin.com/wuzegaxozi/1/edit?html,output

It seems to be an issue with the extension since there's an error in the console related to the adopted style sheets.

I'm closing this issue because we can't fix the extension. Please report this problem to the extension owners.

Regards,
Nayden

**Closed by nnaydenow** 2024-07-10 07:00 UTC
Labels: bug, Medium Prio, TOPIC Core
