### ISSUE TITLE
[ui5-datepicker] Calendar days are misaligned when hiding the week numbers.

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4260] opened 2021-11-03 18:27 UTC
### **Bug Description**
Hi team,

The ui5-datepicker supports hiding the week numbers via property 'hide-week-numbers'. When setting this property to 'true', the calendar does hide the week numbers, but the alignment of the days from their respective columns is misaligned. 

### **Expected Behavior**
The days of the week should align correctly when the week numbers are either shown or hidden.

### **Steps to Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-qeksf?file=/index.html).

### **Context**
- UI5 Web Components version: 0.31.20
- OS/Platform: N/A
- Browser: N/A
- Affected component: ui5-datepicker, ui5-calendar

### **Screenshots**
With week days:
![image (9)](https://user-images.githubusercontent.com/38701667/140170386-641dae4e-237d-48df-a54f-f8babcfa3944.png)
Without week days
![image (8)](https://user-images.githubusercontent.com/38701667/140170509-4b45b8ef-f394-4461-9047-613af985c116.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Bussiness impact: Medium

**Comment by LidiyaGeorgieva** [comment] 2021-11-04 08:09
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible, please have a look.

Best Regards,
Lidiya

**Comment by tsanislavgatev** [comment] 2021-11-05 12:45
Hello,

The issue is not reproducible in latest versions.
Example: https://codesandbox.io/s/ui5-webcomponents-forked-obwrq

Can you please check if you are able to update the version?

Best Regards,
Tsanislav

**Comment by ilhan007** [comment] 2021-11-05 13:07
@tsanislavgatev  the author is not on the latest version, he is from SFSF and he is using 0.31.X

In this case we downport the fix in 0.31. Can you point me to the fix?

**Comment by allen138** [comment] 2021-11-05 16:27
Hi team,

I had one more related issue. The date-pickers/calendars support dual calendars now. When I do my testing with a dual calendar, the week days are not showing up. This might be expected, is that true? But as a result, there is an alignment issue with the dual calendars as well. 

Dual calendar with Buddhist
![dual calendar with Buddhist](https://user-images.githubusercontent.com/38701667/140544379-492eca39-21a8-45a2-9b46-5d4b761332e3.png)

Dual calendar with Islamic
![Dual calendar with Islamic](https://user-images.githubusercontent.com/38701667/140544798-207d31d1-c45f-41a4-a49f-92a71452cb84.png)

**Comment by ilhan007** [comment] 2021-11-18 08:03
Fix has been merged in the remote release-0.31 branch. Changing the status to Pending Release.

**Closed** 2022-02-02 16:18 UTC
Labels: bug, Medium Prio, TOPIC B, SF
