### ISSUE TITLE
DateRangePicker: Clear doesn't work after an invalid value is entered

### ISSUE THREAD

**Issue by I506645** [SAP/ui5-webcomponents#6231] opened 2022-12-30 12:18 UTC
Resetting the value of DateRangePicker to default value (empty strings) doesn't work after an invalid value is entered by the user manually. It works when the selected value is valid from the date range picker popup or manually entering a valid value. 

The date input shows valueState error and valueStateText (as Invalid Entry) when invalid value is entered by the user even though we've not specified the "valueState" and "valueStateMessage" property for the DateRangePicker component. I guess the valueState is displayed because we've specified the "formatPattern" property (correct if I'm wrong). In the FilterBar, we've added a clear button and onclick of it, we reset the value of the dateRange to empty strings and update the state as well. But it still shows the user entered invalid value and the valueStateMessage.

Github repo: https://github.tools.sap/crp/market-unit-ui

Expected behavior is to clear the user input after resetting the invalid value to valid empty strings on click of clear button.

@ui5/webcomponents version: 1.6.0
@ui5/webcomponents-react version: 0.27.5
Operating System: Windows
Browser: Edge and Chrome

Please reach out to me if you need further information.

Best Regards,
Raghav

**Comment by kskondov** [comment] 2022-12-30 13:47
Hello @SAP/ui5-webcomponents-topic-b , can you please take a look at this issue with reseting the value of the DateRangePicker?
Best Regards,
Konstantin

**Comment by I506645** [comment] 2023-01-02 09:08
One update:
In our app, we're setting the value of the date range as empty string when there is an invalid value entered and as well as on click of clear button. Here, since there is no change in state, the component is not re-rendered and whatever user had entered, that invalid value is still displayed on click of clear.

But in codesandbox, we tried setting the state to invalid value whenever user enters invalid value and on click of clear, we set it to empty strings. In this case, on click of clear, the entered invalid value is removed but the DateRangeComponent's valueState still shows "Error" which should not be the expected behavior.

You can use the below sandbox example to check the issue.
[https://codesandbox.io/s/modest-chihiro-t4b135?file=/src/App.js](https://codesandbox.io/s/modest-chihiro-t4b135?file=/src/App.js)

P.s: Add a breakpoint in the function "getValue" to proceed further on click of clear. Else, the component's code throws an error and blocks the user.

**Comment by I506645** [comment] 2023-01-10 09:34
Hello Colleagues,
Any updates on this?

**Comment by I506645** [comment] 2023-05-31 08:05
Hello Colleagues,

It's been a while now. Any updates on this issue? Is it considered in your future scope?

Best Regards,
Raghav

**Comment by hinzzx** [comment] 2023-06-01 11:49
Hi @I506645 ,

Could you please test, if the latest version works for you ?

BR,
Stoyan

**Comment by hinzzx** [comment] 2023-06-02 07:50
Hi @I506645 

I observed the behavior from the snippet you provided and to me it looks like the component works as expected.
The `valueState` of the component shows without you specified it, because it is a build-in feature.

We can see that you try to clear the value of the component programatically. However, if we try and to manually type invalid string into the input, and then just simply delete it without focus-out of the input, the `valueState` stays. The validation of the component is executed on the component being focused out.

Since we provide API for setting up the `valueState` I would suggest to you to try setting up the `valueState` to "None" programatically.

For example -> when the user clicks on the Clear button, also set the `valueState` value to "None".

Please let me know if that solves your issue!

Best Regards,
Stoyan

**Comment by hinzzx** [comment] 2023-06-07 06:31
Hi there @I506645,

just wanted to follow up and see if the solution I proposed worked up for you ! Thanks !

Kind regards,
Stoyan

**Comment by hinzzx** [comment] 2023-06-09 06:58
Hi @I506645,

I am closing this issue. If in the future you still experience problems with the `valueState`, please feel free to re-open the issue.

Best Regards,
Stoyan

**Comment by I506645** [comment] 2023-06-09 07:18
Hi @hinzzx 

Sorry for the delayed response as we were occupied with some critical deliverables and this issue was of low prio. I can try to check if the solution you provided would work or not but the code snippet which I provided in the codesandbox is not rendering the DateRangePicker component now. When I had raised the issue, the codesandbox was rendering the DateRangePicker component but not sure why its not rendering now. Can you please let me know if you're able to see the component or check what's wrong?

Best Regards,
Raghav

**Comment by hinzzx** [comment] 2023-06-09 07:21
> Hi @hinzzx
> 
> Sorry for the delayed response as we were occupied with some critical deliverables and this issue was of low prio. I can try to check if the solution you provided would work or not but the code snippet which I provided in the codesandbox is not rendering the DateRangePicker component now. When I had raised the issue, the codesandbox was rendering the DateRangePicker component but not sure why its not rendering now. Can you please let me know if you're able to see the component or check what's wrong?
> 
> Best Regards, Raghav

Hello, 

Could you try if setting up the version of the Web Components to "latest", would do it ?

BR,
Stoyan

**Comment by hinzzx** [comment] 2023-06-14 10:58
Hello @I506645, 

Is there any update regarding the issue ?

**Comment by I506645** [comment] 2023-06-15 04:11
Hi @hinzzx 

I'm still not able to run the codesandbox sample with the latest ui5 web components version. I keep getting some unexpected import errors for each of the component. Could you please check what's wrong in the code or help me run the codesandbox code https://codesandbox.io/s/naughty-bird-y83dl8?file=/src/App.js?

Best Regards,
Raghav

**Comment by Lukas742** [comment] 2023-06-15 07:12
Hi @I506645 

since you're using the React codeSandbox I can help you with that issue. 
The error states what went wrong:
>Could not find dependency: '@ui5/webcomponents-fiori' relative to '/node_modules/@ui5/webcomponents-react/dist/enums/BarDesign.js'

So, you're missing a peerDependency of `@ui5/webcomponents-react` which is `@ui5/webcomponents-fiori`. (`npm` installs peerDependencies when running `install`, `yarn` does not and afaik codeSandbox is using yarn). You can just click the big blue button with the label `Suggested solutions:`, or add the dependency to your `package.json` yourself.

Also not related to this issue, but could lead to problems in the future:
You're not using the `ThemeProvider` component which could lead to unexpected behavior with themes, i18n, etc.

**Comment by I506645** [comment] 2023-06-16 12:08
Thanks @Lukas742 for the help. It did resolve the issue.

Hi @hinzzx ,
I tried to set the valueState to "None" on click of clear button but still the issue exists (updated the same codesandbox sample). Can you please check again or help me if I missed something?
You can use the above codesandbox example to reproduce the issue.

Best Regards,
Raghav

**Closed** 2023-06-19 09:34 UTC
Labels: bug, Medium Prio, TOPIC B, author action
