### ISSUE TITLE
IllustratedMessage: Named imports of illustrations

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#8070] opened 2024-01-09 15:04 UTC
### Is your feature request related to a problem?

Hi there and happy new year,

We have an `IllustratedMessage` with different illustrations for different cases. Let's say our code looks like this:
```jsx
import { IllustratedMessage, IllustrationMessageType } from '@ui5/webcomponents-react';
import '@ui5/webcomponents-fiori/dist/illustrations/BeforeSearch';

const App = () => (
  <IllustratedMessage
      name={IllustrationMessageType.BeforeSearch}
  />
);
```
For each illustration we use, we need to add a corresponding `@ui5/webcomponents-fiori/dist/illustrations/*` import. I'm aware that an `AllIllustrations.js` import exists, but in our organization, we are discouraged from using it as it increases the build chunk size.
Having this implicit dependency between the illustration and its import is a potential point of failure, as not every contributor is aware of this and might update or add an illustration without adding or modifying the corresponding import.

### Describe the solution you'd like

When using icons, we don't have this problem:
```jsx
import { Button } from '@ui5/webcomponents-react';
import editIcon from '@ui5/webcomponents-icons/dist/edit';

const App = () => (
  <Button
      icon={editIcon}
  />
);
```
With a named import like this, we never run the risk of diverging between an icon and its corresponding import.

So my question is: Is using named imports like this currently possible with the `IllustratedMessage` component? And if not, would it be possible to add this functionality? `IllustrationMessageType` could then be deprecated (or not, as you please).

Thank you very much in advance!

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment] 2024-01-09 17:03
Love this idea! 
Just adding my 2 cents: I think this might be a duplicate of #6735, but with a way better description :)

**Closed** 2024-01-15 09:09 UTC
