### ISSUE TITLE
ui5-shellbar: menus maintain focused element after closed 

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#5994] opened 2022-11-02 00:11 UTC
### **Bug Description**
The shellbar menu and the items overflow menu maintain the keyboard-focused item index when closed.

### **Expected Behavior**
Menus should focus the first item when opened.
https://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. Small viewport width
3. Open modules menu (or overflow menu)
4. Arrow-key down
5. Close menu
6. Re-open modules menu
Previously focused item is still focused

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: MacOS 12.6
- Browser: Chrome 107.0.5304.62 (Official Build) (x86_64) 
- Affected component: ui5-shellbar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: unexpected keyboard behavior

**Comment by TeodorTaushanov** [comment] 2022-11-02 07:17
Hi @SAP/ui5-webcomponents-topic-p, can you check this issue?

**Comment by PetyaMarkovaBogdanova** [comment] 2022-11-10 14:18
Hi colleagues from "@SAP/ui5-webcomponents-topic-rd",
ca you, please, take a look at this issue from ui5-Popover perspective. I noticed it is mostly reproducible if there is a ui5-list inside the Popover. I do not think we should control the focused element on closing the Popover, form the ui5-shellbar.

Kind regards,
Petya Markova.
(UI5 Web Components Developer)

**Comment by gmkv** [comment] 2022-11-10 14:33
Hi @PetyaMarkovaBogdanova 
The List will remember the last focused element. I guess this is by design.
It doesn't have anything special to do with the Popover.
I can share however, how its done in the TabContainer - where there is also a List inside a Popover.
When opening the Popover, we always focus the first element. You can see how this is done here:
https://github.com/SAP/ui5-webcomponents/blob/f1999bd231d97c65b87f0c4998a09f4a44685fe5/packages/main/src/TabContainer.js#L562

**Closed** 2022-12-02 14:08 UTC
Labels: bug, approved, Medium Prio, TOPIC P
