### ISSUE TITLE
[Combo Box]: Items list is not refreshing if the popover is opened

### ISSUE THREAD

**Issue by sebkaim** [SAP/ui5-webcomponents#7957] opened 2023-12-05 16:38 UTC
### Bug Description

If the children of ComboBox (ComboBoxItem) are rendered after the popover is already opened, the popover list will not be updated, will still show the old items (it's correct on MultiComboBox)

### Affected Component

Combo Box

### Expected Behaviour

The combo box is expected to always show the latest items

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Operating System

Mac

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment] 2023-12-05 17:15
Hello @sebkaim, thank you for reporting, this is known issue

Duplicate of: https://github.com/SAP/ui5-webcomponents/issues/7011
Fix in review: https://github.com/SAP/ui5-webcomponents/pull/7937

**Closed by ilhan007** 2023-12-05 17:15 UTC
Labels: bug
