### ISSUE TITLE
Popup Axe Issue: Popups that are not Dialog have no accessible name

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3956] opened 2021-09-17 17:47 UTC
### **Bug Description**
This is a break out issue from the following:
https://github.com/SAP/ui5-webcomponents/issues/3933

#### 6. ARIA dialog and alertdialog nodes should have an accessible name

_output with custom Popup element has `aria-labelledby="ui5-popup-header"` but no such element exists._

Try this yourself on the shellbar playground and click the account menu for "An Kimura" -- inside the `<ui5-popover>` shadowRoot you'll find the following: `<section role="dialog" style="" class="ui5-popup-root" aria-modal="true" aria-labelledby="ui5-popup-header" tabindex="-1">`

This is part of the Popover.hbs but the definition of "ui5-popup-header" is part of the Dialog.hbs which means if this is a Popup but not a Dialog the aria-labeledby attribute will be dangling.

### **Expected Behavior**
Popups should always have accessible names.

### **Steps to Reproduce**
See https://github.com/SAP/ui5-webcomponents/issues/3933 for the Axe setup

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment] 2021-09-20 13:38
Hi @codefactor,
ui5-popover component does have **accessibleName** property, which should either be used as accessible name,
or headerText should be provided in case there is a header designed for the particular popover.
In Popover sample in the playground the issue is not fired by AXE tool, because the headerText is provided and 
'ui5-popup-header" is assigned as an aria-labelledby value.
In this case I don`t think we have an issue in the component, we will update the ShellBar playground sample shortly.

Kind regards,
Petya Markova.

**Comment by ilhan007** [comment] 2021-09-21 06:53
Hi @PetyaMarkovaBogdanova 

Actually accessibleName property is a property released in RC.15, but not available in the 0.31, the version that our colleagues from SF is using.

And, regarding "In Popover sample in the playground the issue is not fired by AXE tool, because the headerText is provided and 'ui5-popup-header' is assigned as an aria-labelledby value.", 
you will have to check out the 0.31 remote branch and re-test, there might be later development and fixes that need to be downported in 0.31 in order to fix the issue, that is not present in the latest version.

**Comment by PetyaMarkovaBogdanova** [comment] 2021-09-21 11:05
Hi @codefactor , @ilhan007 ,
after retesting I found out that in version 0.31 the accessible name can be given to the Popover component via **ariaLabel** property.
I consider it not an issue that requires downporting.

Kind regards,
Petya Markova.
(UI5 developer)

**Comment by ilhan007** [comment] 2021-09-21 11:48
Unfortunately, ariaLabel will work if the ui5-webcomponents are directly used:
```html
<ui5-popover aria-label=""
<ui5-dialog aria-label=""
```

But I guess @codefactor is using the React wrappers, @codefactor is that the case?
Because "ariaLabel" is not a public property, it's a private one, and private properties are not supported by the React wrappers and setting ariaLabel will take no effect, won't be forwarded to internally to the web component.
Otherwise, in case the web components are directly used, "ariaLabel" can be used as shown above.

**Comment by codefactor** [comment] 2022-01-11 17:55
@ilhan007 ,
Can you please give an update on this ticket?

It's not clear to me what the final result is, since there are comments about 0.31 vs. RC.15, but it's not clear -- is this issue already resolved in the 1.x version but then you're considering the fix on 0.31 branch or something like this?

We would like to come to a conclusion on this open ticket.

**Comment by ilhan007** [comment] 2022-05-26 07:32
Hello @SAP/ui5-webcomponents-topic-rd could you check the following issue

"6. ARIA dialog and alertdialog nodes should have an accessible name
output with custom Popup element has aria-labelledby="ui5-popup-header" but no such element exists.

Try this yourself on the shellbar playground and click the account menu for "An Kimura" -- inside the <ui5-popover> shadowRoot you'll find the following: <section role="dialog" style="" class="ui5-popup-root" aria-modal="true" aria-labelledby="ui5-popup-header" tabindex="-1">

This is part of the Popover.hbs but the definition of "ui5-popup-header" is part of the Dialog.hbs which means if this is a Popup but not a Dialog the aria-labeledby attribute will be dangling."


The author is using the  [ShellBar playground sample](https://sap.github.io/ui5-webcomponents/master/playground/components/ShellBar/) - the first instance has a profile image, that opens a popover. When you inspect the popover, you will find a DOM element with `aria-labelledby="ui5-popup-header"`, pointing to an element that does not exist.

<img width="909" alt="Screenshot 2022-05-26 at 10 28 14" src="https://user-images.githubusercontent.com/15702139/170439781-ffc51db6-412c-4e1c-8cfd-bbf3d2a91865.png">

**Comment by dimovpetar** [comment] 2022-06-29 08:44
Hello @codefactor ,

#5428 is now part of the main branch. Now `aria-labelledby="ui5-popup-header"` is not added when the header doesn't exist. Do you still use version 0.31, or you have switched to newer one? 
Please also keep in mind that if you want to have accessible name, you should set the `accessible-name`, `accessible-name-ref` or provide header slot.

Best regards,
Petar

**Comment by dimovpetar** [comment] 2022-06-30 10:13
Hello,

If you require the #5428 to be merged in the branch you use, let us know.

Best regards,
Petar

**Closed by dimovpetar** 2022-06-30 10:13 UTC
Labels: bug, ACC, TOPIC RD, SF, author action
