### ISSUE TITLE
Wizard: Header does not scroll to the desired step

### ISSUE THREAD

**Issue by d3xter666** [SAP/ui5-webcomponents#3675] opened 2021-08-16 10:58 UTC
### **Bug Description**
On smaller screens where the navigation header of the Wizard is stacked, clicking on a step does not scroll to the proper place.

### **Expected Behavior**
The content should be scrolled to the header of the selected step

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/Wizard/
2. Set screen size, so that Wizard's header icons get stacked.
3. Make some progress with the Wizard, the standard way
4. Start navigating through steps by clicking the header's icons.

<img width="408" alt="Screenshot 2021-08-16 at 13 58 01" src="https://user-images.githubusercontent.com/3379948/129553502-ba061e5e-129d-41e1-b018-40712e4be414.png">

**Comment by niyap** [comment] 2021-12-08 07:27
Hello Colleagues,

The issue seems to be resolved. I was not able to reproduce the issue. Then I asked the reporter to check once again whether the issue is reproducible for him and he was not able to reproduce it as well, so I am closing the incident.

Kind Regards,
Niya

**Closed by niyap** 2021-12-08 07:27 UTC
Labels: Low Prio, TOPIC RL, 1.0 Release Testing
