### ISSUE TITLE
[Popover]: Popover cannot be closed if it is rendered as opened initially.

### ISSUE THREAD

**Issue by bennylalala** [SAP/ui5-webcomponents#10375] opened 2024-12-12 20:45 UTC
### Bug Description

Popover cannot be closed if it is rendered as opened initially.

### Expected Behaviour

Popover can be closed properly no matter it is opened or not initially.

### Isolated Example

It can be reproduced here  https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuXG4gICAgaHRtbCB7XG4gICAgICBmb3JjZWQtY29sb3ItYWRqdXN0OiBub25lO1xuICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpXCI-XG4gICAgPHN0eWxlPlxuICAgICAgICBib2R5IHtcbiAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgIH1cblxuICAgICAgICAucG9wb3Zlci1jb250ZW50IHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gICAgICAgIH1cblxuICAgICAgICAucG9wb3Zlci1mb290ZXIge1xuICAgICAgICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogZmxleC1lbmQ7XG4gICAgICAgICAgICB3aWR0aDogMTAwJTtcbiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAgICAgICAgICBwYWRkaW5nOiAwLjVyZW0gMDtcbiAgICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG5cbiAgICA8dWk1LWJ1dHRvbiBpZD1cImJ0blwiPk9wZW4gUG9wb3ZlcjwvdWk1LWJ1dHRvbj5cblxuICAgIDx1aTUtcG9wb3ZlciBvcGVuZXI9XCJidG5cIiBoZWFkZXItdGV4dD1cIk5ld3NsZXR0ZXIgc3Vic2NyaXB0aW9uXCIgb3Blbj5cbiBcbiAgICAgICAgPGRpdiBjbGFzcz1cInBvcG92ZXItY29udGVudFwiPlxuICAgICAgICAgICAgPHVpNS1sYWJlbCBmb3I9XCJlbWFpbElucHV0XCIgcmVxdWlyZWQgc2hvdy1jb2xvbj5FbWFpbDwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgPHVpNS1pbnB1dCBpZD1cImVtYWlsSW5wdXRcIiBzdHlsZT1cIm1pbi13aWR0aDogMTUwcHg7XCIgcGxhY2Vob2xkZXI9XCJFbnRlciBFbWFpbFwiPjwvdWk1LWlucHV0PlxuICAgICAgICAgICAgPHVpNS1sYWJlbD5Ob3RlOiBJZiB5b3Ugb3BlbiB0aGUgcGFnZSBpbiBtb2JpbGUsIGEgZGlhbG9nIHdvdWxkIGJlIGRpc3BsYXllZC48L3VpNS1sYWJlbD5cbiAgICAgICAgPC9kaXY-XG5cbiAgICAgICAgPGRpdiBzbG90PVwiZm9vdGVyXCIgY2xhc3M9XCJwb3BvdmVyLWZvb3RlclwiPlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJjbG9zZVBvcG92ZXJCdXR0b25cIiBkZXNpZ249XCJFbXBoYXNpemVkXCI-U3Vic2NyaWJlPC91aTUtYnV0dG9uPlxuICAgICAgICA8L2Rpdj5cblxuICAgIDwvdWk1LXBvcG92ZXI-XG5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1BvcG92ZXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGFiZWwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5cbmNvbnN0IGJ0biA9IFsuLi5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZShcInVpNS1idXR0b25cIildWzBdO1xuY29uc3QgcG9wb3ZlciA9IFsuLi5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZShcInVpNS1wb3BvdmVyXCIpXVswXTtcblxuYnRuLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG5cdHBvcG92ZXIub3BlbiA9ICFwb3BvdmVyLm9wZW47XG59KTsifX0

### Priority

Very High

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment] 2024-12-13 09:27
Hi @bennylalala,

The issue is duplicated of https://github.com/SAP/ui5-webcomponents/issues/10327 and it is fixed in main branch.

**Closed by nnaydenow** 2024-12-13 09:27 UTC
Labels: bug
