### ISSUE TITLE
Input's Cursor is Jumping on Safari

### ISSUE THREAD

**Issue by m1trix** [SAP/ui5-webcomponents#2632] opened 2021-01-06 08:08 UTC
**Describe the bug**
On Safari, when an `ui5-input` _(and input-based components)_ already has some value and you start typing anywhere other than the very end, at some point the cursor jumps to the very end. The issue only appears if you write relatively fast _(on some components like MultiComboBox, it always happens)_

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the [Input documentation page](https://sap.github.io/ui5-webcomponents/playground/components/Input/)
2. Click on any example
3. Write down some text
4. Put the cursor somewhere in between the text
5. Start typing relatively fast

**Isolated example**
Any input on the [Input documentation page](https://sap.github.io/ui5-webcomponents/playground/components/Input/)

**Expected behaviour**
The cursor should remain where it is.

**Screenshots**
![safari-jumping-cursor](https://user-images.githubusercontent.com/3427023/103744753-fb3c7000-5006-11eb-9247-87a079b2b3d3.gif)

**Context**
- UI5 Web Components version: `1.0.0-rc.10` & `1.0.0-rc.11` _(I haven't tested on older versions)_
- OS/Platform: `MacOS 11.1`
- Browser *(if relevant)*: `Safari 14.0.2`
- Other information: N/a

**Affected components** *(if known)*
Input, MultiInput, ComboBox, MultiComboBox _(with free text enabled)_, potentially others

**Log output / Any errors** in the console
No errors are logged

**Organization:** *SAP*

**Priority:** *(optional)* *High*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screen Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criteria

**Business impact:** *(mandatory for "Very High")*
Safari users will have bad time inserting text into these components.

**Comment by m1trix** [comment] 2021-01-06 08:16
It seems to be also happening when a suggestion shows up.
![safari-jumping-cursor-2](https://user-images.githubusercontent.com/3427023/103745465-34c1ab00-5008-11eb-8100-4c93d0398be3.gif)

**Comment by fifoosid** [comment] 2021-01-06 08:43
Might be related to #1761

**Comment by ilhan007** [comment] 2021-01-08 05:23
Hello @SAP/ui5-webcomponents-topic-rl I am forwarding this Input issue to you.

**Comment by fifoosid** [comment] 2021-01-08 10:54
This issue affects Combobox and MultiComboBox on Safari as well

**Comment by Martotko** [comment] 2021-01-21 13:54
Hi @m1trix,

I'm not able to reproduce the issue. Could you please check again if it still appears on your end, because maybe is already fixed.

Best regards,
Martin

**Comment by Martotko** [comment] 2021-01-26 14:38
This is an async issue related to row 903 of the Input.js

**Comment by MapTo0** [comment] 2021-12-09 22:36
Same as https://github.com/SAP/ui5-webcomponents/issues/4410

Browser issue. Looks like it is fixed in Safari Technology Preview (future version of Safari)

**Closed by MapTo0** 2021-12-09 22:36 UTC
Labels: bug, Medium Prio, TOPIC RL, Blocked, Autopilot
