### ISSUE TITLE
[ui5-tree-item-custom]: Does not highlight on hover when type="Active"

### ISSUE THREAD

**Issue by FMaulwurf** [SAP/ui5-webcomponents#7885] opened 2023-11-21 10:37 UTC
### Bug Description

The `ui5-tree-item-custom` webcomponent does not highlight on hover.

Following the documentation the custom tree item should highlight on hover or on click. However the highlight only happens on click. 

@Lukas742 created a sandbox here: https://codesandbox.io/s/ui5-webcomponents-forked-jhsm2x?file=/index.html:418-438

### Affected Component

ui5-tree-item-custom

### Expected Behaviour

The `ui5-tree-item-custom` should highlight on hover.

### Steps to Reproduce

1. check the Sandbox here https://codesandbox.io/s/ui5-webcomponents-forked-jhsm2x?file=/index.html:418-438
2. hover a tree item and you will not see any highlight
3. click a tree item and you will see the highlight

### Priority

None

### UI5 Web Components Version

1.19.1

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

MacOS 14.1.1 (23B81)

### Additional Context

My assumption that it should highlight comes from the react lib documentation:

```
Note: When set to Active or Navigation, the item will provide visual response upon press and hover, while with type Inactive and Detail - will not.
```
See: https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--docs

I reached out on Slack and they said this issue is within the web component and not the react wrapper.

### Organization

SAP SE

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment] 2023-11-21 12:01
Hello @SAP/ui5-webcomponents-topic-p,

I am not sure if this should be fixed or it is "by design"
Checking OpenUI5's tree implementation hover is not visible: https://openui5nightly.hana.ondemand.com/entity/sap.m.Tree/sample/sap.m.sample.Tree

But visual specification claims the following: `Please follow as in List (Horizon) - Interactive States.`
Which means that maybe tree items should have hover effect? 

Anyway I checked that some work on the topic has been don with #7527 
I noticed that `_mode` attribute should be set to all items in order to get everything going.
After adding _mode to all tree items the selector works and hover is visible.
Check: https://codesandbox.io/s/ui5-webcomponents-forked-w6l493?file=/index.html

Please consider editing the selector https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/themes/TreeItem.css#L24

to something like `:host(:not([_mode="None"]):not([_mode="Delete"]):not([active]):not([selected])) .ui5-li-root-tree:hover`

If this is by design just close the issue.

Best Regards,
Martin

**Comment by kgogov** [comment] 2024-03-21 09:30
Hello @MapTo0,

Apologize for our late reply. Thank you for your thoughtful report.
We've made changes to the `ui5-tree-item-custom` based on it (See change #8278).

Best Regards,
Konstnatin

**Closed by kgogov** 2024-03-21 09:30 UTC
Labels: bug, Low Prio, TOPIC P, SAP Signavio
