### ISSUE TITLE
UI5-Carousel works differently from Desktop Browser and Mobile Browser

### ISSUE THREAD

**Issue by Knightofhonour** [SAP/ui5-webcomponents#2345] opened 2020-10-12 10:00 UTC
**Describe the bug**
In Desktop Browser, when hide-navigation of ui5 carousel is set to true, no scrolling can be done. However, in mobile browser, scrolling can be done

**To reproduce**
https://github.com/Knightofhonour/ui5-Carousel
git clone the repo
unzip the node modules zip file
run command parcel src/index.html
check local host on both a mobile simulator and on desktop browser

**Expected behavior**
I understand that ui5-carousel is meant for scrolling, so I would like to clarify if this is as intended, or if scrolling should have been disabled for both browsers

**Screenshots**
![image](https://user-images.githubusercontent.com/48403373/95733380-a497f200-0cb4-11eb-9a64-a3df662cd1a3.png)
![image](https://user-images.githubusercontent.com/48403373/95733424-b24d7780-0cb4-11eb-9ad9-efd59d55c027.png)

**Comment by ilhan007** [comment] 2020-10-13 09:16
Hello @Knightofhonour 
the API is indeed not enough clear. 

Currently the [Fiori 3 guidelines](https://experience.sap.com/fiori-design-web/carousel/) suggests  that:
- On non-touch devices, the user can navigate with the paging buttons displayed on the left and right of the component.
- On touch devices, the carousel control makes use of the swipe gesture to navigate through the items. As a result, the paging buttons **are not displayed on touch devices.**

And this is pretty much how the component currently works - the property hideNavigation is an option to hide the navigation on desktop and has nothing to do with the scrolling.

I admit that it is a little inconsistent that on desktop you can hide the buttons, but **you can't scroll**,
and on mobile, the buttons are always hidden and **you can scroll**

This is already marked as a API review topic that we will refine at some point: https://github.com/SAP/ui5-webcomponents/issues/2347
We will keep the issue open until we provide a solution.

P.S.
In future the visibility of the navigation on mobile might change as there is also a proposal to be always visible on mobile, but it would require much time as there should be a change in the UX design first:
https://github.com/SAP/openui5/issues/2826

BR,
ilhan

**Comment by Knightofhonour** [comment] 2020-10-16 06:54
Hi @ilhan007 ,

I have also discovered a follow up issue. If you were to run the same repo on an Android Emulator (Android Tablet with API 27), it appears that scolling also cannot be done (hide-navigation was removed from the code).

[Screen Recording 2020-10-16 at 2.53.00 PM.mov.zip](https://github.com/SAP/ui5-webcomponents/files/5389709/Screen.Recording.2020-10-16.at.2.53.00.PM.mov.zip)

Is this a similar issue or a bug?

Regards,
David

**Comment by ilhan007** [comment] 2020-10-16 07:43
Hello @Knightofhonour 

Can you try it on real device, because the emulators do not always show exactly how something would work on a device.
And, we don't support emulators. To process the issue, it should be reproducible on a device. 

Here is the list of browsers, platforms and device support: https://sapui5.hana.ondemand.com/#/topic/74b59efa0eef48988d3b716bd0ecc933

If it is reproducible, it would be another bug, so you can create another issue.

BR,
ilhan

**Comment by ilhan007** [comment] 2021-05-31 13:36
Hello @gmkv could you also check this issue, not exactly bug, but possibly bad UX or API.

Currently the Fiori 3 guidelines suggests that:

- On non-touch devices, the user can navigate with the paging buttons displayed on the left and right of the component.
- On touch devices, the carousel control makes use of the swipe gesture to navigate through the items. As a result, the paging buttons are not displayed on touch devices.

And, this is pretty much how the Carousel currently works - the property hideNavigation (recently renamed to hideNavigationArrows) is an option to hide the navigation on desktop and has nothing to do with the scrolling.

I admit that it is a little inconsistent that 
- on desktop you can hide the navigation arrows ant you can't scroll,
- on mobile, the buttons are always hidden (no matter what is the value of the property), but you can scroll to the left/right

Could you check if the Carousel component is implemented bu the SAP Fiori 3 spec and behaves as expected and the same a sap.m.Carousel in terms of the above desktop/mobile use cases?

**Comment by gmkv** [comment] 2021-06-04 07:13
Hi @ilhan007 
The ui5-carousel component has been implemented correctly according to the Fiori 3 guidelines. 
On a desktop, you indeed can't do "swipe gestures" with the mouse and that's intended. If your desktop has a touch screen, the "swipe gestures" still work when using touch.

The sap.m.Carousel actually has a bug at the moment - it supports swipe gestures with the mouse.

**Comment by ilhan007** [comment] 2021-06-04 13:17
Hello @Knightofhonour 

we checked the component behaviour, particularly its navigation, and it turns out that the Carousel works as expected. 
However, we prepared a PR, that explains better how the Carousel is supposed to work on desktop/mobile: https://github.com/SAP/ui5-webcomponents/pull/3395

How it works:
- On non-touch devices, the user can navigate with the paging buttons displayed on the left and right of the component
and using the keyboard shortcuts (LEFT/RIGHT/UP/DOWN)
- On touch devices, the carousel control makes use of the swipe gesture to navigate through the items.
The paging buttons are never displayed on touch devices.

API
- hide-navigation-arrows: hides the navigation arrows (on mobile they are always hidden)

(1) hide-navigation-arrows: false
On desktop, the user can navigate with both navigation arrows and the keyboard shortcuts.
On mobile, the user  can swipe.

(2) hide-navigation-arrows: true
On desktop, the user can still navigate with the keyboard shortcuts.
On mobile, the user can swipe.

**Closed by ilhan007** 2021-06-04 13:17 UTC
Labels: API, Medium Prio, TOPIC RD, consulting
