### ISSUE TITLE
[build]: excessive memory usage on Windows

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7239] opened 2023-06-21 08:34 UTC
### Bug Description

We got reports for excessive memory usage when running the project under Windows, slowing down the development flow.

### Affected Component

@ui5/webcomponents-tools

### Expected Behaviour

The project should run without such excessive memory usage.

### Steps to Reproduce

1. Start the project
2. Monitor the Task manager for 30 min
3. Observe the node process memory usage
...

### Log Output, Stack Trace or Screenshots

<img width="852" alt="Screenshot 2023-06-21 at 11 27 52" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/4438cd67-b0ff-4567-a8ed-32eefde4350d">

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

Windows

### Additional Context

<img width="352" alt="Screenshot 2023-06-21 at 11 38 37" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/391d5f9f-aa93-4b26-97ca-c5f1397e9e14">

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment] 2024-08-05 07:28
Closing this issue as duplicate of https://github.com/SAP/ui5-webcomponents/issues/8824

**Closed by dimovpetar** 2024-08-05 07:28 UTC
Labels: bug, Medium Prio, TOPIC Core
