### ISSUE TITLE
Inputs with Suggestions - Up/Down Navigation

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3790] opened 2021-09-01 12:40 UTC
### **Bug Description**
Up/Down keyboard navigation is not fully supported for input components with suggestions (input, multiinput, combobox, multicombobox)

### **Expected Behavior**
_Notes:_ 
_- The focus in the input components is linear: input field <-> value state header <-> group header <-> list item_
_- The value state header should be always focusable in order to have linear focus_

UP ARROW:
1. Focus is in the input field and the picker is opened
 - do nothing
2. Focus is in the popup
- move focus one list item up and select item. Reflect focused item into the text input. 
- If the first list item is focused, moves focus to the value state item or group header, if present.
- If the first available item is focused (group header, value state, list item), moves the focus into the input field
_Note: ui5-combobox has a feature that 'navigates' in the list and updates the input field value, when the picker is closed._

DOWN ARROW:
1. Focus is in the input field and the picker is opened
- move focus to the corresponding item within the list box (should be the first visible
item). Update the field accordingly:
 -If group header - remove the autocompleted value and leave only the user input
 -If value state header - do not update the input field value
2. Focus is in the popup
- move focus one list item down and select item. Reflect focused item into the text input.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by niyap** [comment] 2021-11-02 11:59
The issue is fixed with the following pull request: #3976

**Closed by niyap** 2021-11-02 11:59 UTC
Labels: High Prio, TOPIC RL, 1.0 Release Testing
