### ISSUE TITLE
ui5-shellbar: mobile view search transparent background

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4059] opened 2021-10-01 19:45 UTC
### **Bug Description**
When `--sapShellColor` is transparent, the mobile search view has a transparent background and shows the shellbar underneath.
ie. sap_belize theme

### **Expected Behavior**
A guaranteed background for `.ui5-shellbar-search-full-width-wrapper`.

### **Steps to Reproduce**
1. https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/?sap-ui-theme=sap_belize&isrtl=false
2. shrink viewport width until "small"
3. open search

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/4755512/135674759-781616b3-f9f9-49eb-ad8e-95b3604a9cdd.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by plamenivanov91** [comment] 2021-10-04 13:32
Hello Colleagues,

I tested it and the issue is currently reproducible on the latest rc.
The issue is not reproducible on the default theme.

Regards,
Plamen

**Comment by nnaydenow** [comment] 2021-10-08 08:46
Hi @JarrettChan,

The ShellBar component was designed after Belize theme and released with Fiori 3 theme and it is not supposed to be used and supported in this scenario.

Regards,
Nayden

**Closed by nnaydenow** 2021-10-08 08:46 UTC
Labels: bug, TOPIC P
