### ISSUE TITLE
[SF_ACC][ui5-message-strip]: Please provide accessibleName to customize aria-label string

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#9651] opened 2024-08-07 08:14 UTC
### Bug Description

The message strip is read out incorrectly when there is a link which has own aria-label. For instance, our code likes below:

`<ui5-message-strip design="Information">Download the <a href="http://www.google.com" aria-label="download the template in zip file">template</a> file.</ui5-message-strip>`

Then JAWS will announce:
Information bar. Download the download the template in zip file file.

Because JAWS will replace link text with it's aria-label.

### Affected Component

ui5-message-strip

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment] 2024-08-07 14:00
Hello @i323808 ,

This speech output looks expected. Changing the `aria-label` of the `a` element changes the way it is announced. Why would you need to change it, and expect different output at the end?
Please provide more information about your use case.

Best regards,
Petar

**Comment by i323808** [comment] 2024-08-08 10:59
Hi @dimovpetar ,

Our design is embeding a link in the message strip likes below snapshot. 
<img width="439" alt="message_strip_with_link" src="https://github.com/user-attachments/assets/310d2e18-21f1-49e6-b930-9619a8bf8ec5">

We added an aria-label(**the download the template in zip file**) to the link for sufficient meaning. But JAWS will read out incorrectly for the MessageStrip once adding aria-label to the link, because JAWS will replace link text with it's aria-label, then read as 'Download the download the template in zip file file.'. So we need customize the accessible name of MessageStrip.

Incorrect behavior: Download **the download the template in zip file** file.
Expected behavior: Download the template file.

Thanks,
Jane

**Comment by dimovpetar** [comment] 2024-08-09 06:31
Hello @ui5-webcomponents-topic-rl,

Take a look at this feature request.

Best regards,
Petar

**Comment by ivoplashkov** [comment] 2024-08-13 10:58
Hello,

I was not able to reproduce the issue. The speech output seems to be always the same, no matter if I am using ui5-messagestrip or plain html - https://stackblitz.com/edit/js-8vatkh?file=index.html,index.js.

Could you please have a look and give me more information on how to reproduce the issue?
Best regards,
Ivaylo

**Comment by ivoplashkov** [comment] 2024-08-13 11:48
Hello @i323808,

Having a second look at this, do you want us to provide an accessibleName for the component or you think that there is an issue within the control?

Thank you in advance!
Best regards,
Ivaylo

**Comment by ivoplashkov** [comment] 2024-08-15 06:25
Hi @i323808,

Thank you for the quick response!

I have tested with JAWS 2024 and both the content and the aria-label seems to be read out. Could you please provide more information on the JAWS version you are using, do you see any difference in the speech for the ui5-messagestrip and the native example I have provided. Screenshot of the speech history would be valuable as well.

Thank you in advance!
Regards,
Ivaylo

**Comment by i323808** [comment] 2024-08-15 08:34
Hi @ivoplashkov ,

Please refer to the speech history provided by QAS team.
<img width="1355" alt="message_strip_with_link" src="https://github.com/user-attachments/assets/2cdc0d4d-ad70-4065-a4ef-40ae2bbed7b9">

Here is the UI design.
![message_strip_design](https://github.com/user-attachments/assets/64ed7b82-f293-46c5-a2c8-55c639edb438)

The MessageStrip is read out as 'Information Bar Download the **Download the assignment templates in a zip file**.' Because we add an aria-label(Download the assignment templates in a zip file) to the template link.
The expected behavior is read out as 'Information Bar Download the **template**.' for MessageStrip and read out as 'Download the assignment templates in a zip file' for Link.

BR,
Jane

**Comment by ivoplashkov** [comment] 2024-08-16 08:57
Hi @i323808,

Thank you for the provided information.

This seems to be an issue related to how JAWS treats anchor tags generally. The issue has nothing to do with ui5-messagestrip. You can check this native example where we have just an anchor tag with aria-label and content and the content is not being read at all - https://stackblitz.com/edit/js-8vatkh?file=index.html,package.json.

Since the issue has nothing to do with ui5-messagestrip, I am closing it.

Best regards,
Ivaylo

**Closed by ivoplashkov** 2024-08-16 08:57 UTC
Labels: bug, ACC, TOPIC RL, author action
