### ISSUE TITLE
[ui5-input] Suggestion Popover does not show

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4425] opened 2021-12-03 17:43 UTC
### **Bug Description**
Hi Team,
We are trying to upgrade to the new stable release version 1.0.x, but there seems to be a bug in the Input.js - which is preventing us from doing the upgrade. From what I can tell it is due to this change here: [PR#3997:0b3e12f3](https://github.com/SAP/ui5-webcomponents/commit/0b3e12f3331105de89160b675ec06826929b421e). When using the input with suggestions and attempting to search, the property `this.open` is getting set to true, but then on a rerender it is incorrectly getting set to false causing the responsive popover to close, [onAfterRendering](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Input.js#L581).

Thanks,
Allen

### **Expected Behavior**
Suggestion popover will be displayed when there are suggestions so the user can select one of the suggestions.

### **Steps to Reproduce**
1. https://codesandbox.io/s/wild-tree-e8hld?file=/src/index.js
2. type 'ti' in the input and notice the suggestion popover is not displayed.

### **Context**
- UI5 Web Components version: 1.0.1
- OS/Platform: All
- Browser: All 
- Affected component: ui5-input

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Bussiness impact: High

**Comment by gregorwolf** [comment] 2021-12-17 09:25
We're facing the same issue and it's very annoying to the users. Hope this can be fixed soon.

**Comment by gregorwolf** [comment] 2022-01-12 07:41
Are there any updates when this will be fixed? Would it help to file an Incident via SAP Support to get a speedup?

**Comment by MapTo0** [comment] 2022-02-01 15:19
Hello all,

The issue is quite complex and we are working on a general solution for all inputs. As current workaround you can use the `openPopover()` method of the component. I will update you as soon as we have a working proposal.

Best Regards!

**Comment by gregorwolf** [comment] 2022-02-01 16:28
Thank you for the update.

**Comment by texttechne** [comment] 2022-02-11 09:36
Hi @MapTo0,

calling the method `openPopover()` on the instance doesn't work or does not have any effect at all.
[Modified example](https://codesandbox.io/s/nifty-dust-wmwrp?file=/src/index.js)

**Closed** 2022-02-25 12:20 UTC
Labels: bug, TOPIC RL, SF
