### ISSUE TITLE
SideNavigation: Inconsistent icon sizes

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5825] opened 2022-09-16 05:34 UTC
**Describe the bug**
The `>` icon size is changing depending on the text length in the SideNavigation

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/sidenav-truncate-ij7bwe?file=/src/App.js:180-194)

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/sidenav-truncate-ij7bwe?file=/src/App.js:180-194)
2. Here the `>` icon sizes are different depending on the length of text in SideNavigationItem. Small icon for longer texts.

**Expected behavior**
The size of `>` icons should be consistent independent of text length.

**Screenshots**
<img width="282" alt="image" src="https://user-images.githubusercontent.com/93638146/190563514-a1a71f2d-eef7-4cf7-927e-611b0fedb78d.png">

**Comment by plamenivanov91** [comment] 2022-09-19 10:19
Hello @SAP/ui5-webcomponents-topic-rd ,

It seems that the expand icon scales its size depending on the space which remains for it.

Since I couldn't find any visual specification for this use, could you please verify if this is expected behavior or it should be fixed?

Regards,
Plamen Ivanov

**Closed** 2022-09-28 12:11 UTC
Labels: bug, Low Prio, TOPIC RD
