### ISSUE TITLE
[ui5-rating-indicator ]: repetitive announcements of accessible name in JAWS VPC Mode

### ISSUE THREAD

**Issue by I585157** [SAP/ui5-webcomponents#7656] opened 2023-10-02 20:56 UTC
### Bug Description

In JAWS VPC Mode, VPC focus goes to an invisible element before the first star which results in an extra announcement on the rating indicator's accessible name. This double announcement doesn't occur in openUI5. 

### Affected Component

Rating Indicator

### Expected Behaviour

When the accessible-name property is set, and VPC mode is on, JAWS first focuses on an invisible element before the first star to announce the accessible-name. Then, moving to the next element, the accessible name is read aloud again resulting in a duplicate announcement. 

### Isolated Example

https://ui5.sap.com/#/entity/sap.ui.webc.main.RatingIndicator/sample/sap.ui.webc.main.sample.RatingIndicator

### Steps to Reproduce

1. Navigate to https://ui5.sap.com/#/entity/sap.ui.webc.main.RatingIndicator/sample/sap.ui.webc.main.sample.RatingIndicator
2. Start JAWS in VPC mode
3. move to a rating indicator until you hear it's accessible name
4. move to the next element
5. Navigate to https://ui5.sap.com/#/entity/sap.m.RatingIndicator/sample/sap.m.sample.RatingIndicator to compare to openUI5 version
6. Start JAWS in VPC mode
7. move to a rating indicator
...

### Priority

None

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

Mac OS

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment] 2023-10-04 11:20
Hi @SAP/ui5-webcomponents-topic-rl 
When the Rating Indicator component has an accessible name (or accessible name ref) set, JAWS on VPC mode will announce the accessible name twice.

WebC with accessibleName https://jsbin.com/fukeduqefe/1/edit?html,output
WebC with accessibleNameRef https://jsbin.com/norimudefu/1/edit?html,output
OpenUI5 with ariaLabelledBy https://jsbin.com/qirexudovi/edit?html,output

Would you have a look?

**Comment by niyap** [comment] 2023-10-25 16:51
Hello @I585157,

Thanks for sharing your findings!

I have checked the ARIA standard as well as the HTML representation of ui5-rating-indicator web component in order to ensure that our implementation follows all the standards. Also, I tested with NVDA as a screen reader and the issue is not reproducible.
What I found out is that the issue is reproducible with native HTML as well: https://jsbin.com/qejequrumu/1/edit?html,output
As it is not related to the ui5-rating-indicator implementation and  we do not have influence over it, I am closing the issue.

Kind Regards,
Niya

**Closed by niyap** 2023-10-25 16:51 UTC
Labels: bug, ACC, High Prio, TOPIC RL, SF
