### ISSUE TITLE
ui5-dialog: Position and size error in 1280X800 resolution with 200% browser zoom

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3065] opened 2021-03-31 10:02 UTC
**Describe the bug**
hi, We use the dialog component in our project, with  1280X800 resolution and 200% browser zoom. And the dialog position and size is incorrect. 

**To reproduce**
1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11001
2. click the View Details Link
3. change computer resolution 1280X800 and browser zoom to 200%

**Screenshots**
![image](https://user-images.githubusercontent.com/78520316/113126649-71d5bc00-924a-11eb-9c4c-6d9c2db679e3.png)

**Context**
- UI5 Web Components version: 0.29.11
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:

- Is visual, styling one - Low and Medium

**Comment by unazko** [comment] 2021-04-01 12:05
Hello @sfsf-xweb-sh,

I've managed to reproduce the issue inside the provided application,
but I'm having hard time recognizing the cause of the issue as it isn't reproducible in the playground samples.

I've created the following snippet:
https://codesandbox.io/s/vibrant-buck-uwztv?file=/src/index.js

Could you please try to edit the snipped so the issue gets reproducible in there?

Best Regards,
Boyan

**Comment by unazko** [comment] 2021-04-05 09:14
Hello again @sfsf xweb-sh,

I was able to reproduce the issue with the snippet:
https://codesandbox.io/s/vibrant-buck-uwztv?file=/src/index.js
by adding an additional resizing step.

I've resized the browser window to the lowest possible width on chrome browser:
![DialogZoomed](https://user-images.githubusercontent.com/15860295/113558212-ea03ff00-9607-11eb-9fdb-1f3759053acf.png)

**Comment by unazko** [comment] 2021-04-05 09:24
Hello @sfsf-xweb-sh,

I deleted my message by mistake.

Could you please try to reproduce the issue in the following snippet as well:
https://codesandbox.io/s/vibrant-buck-uwztv?file=/src/index.js
so we can confirm that there is an issue with the dialog component.

Replacing the contents of the dialog in the snipped with the same content as in the application could be enough.

Best Regards,
Boyan

**Comment by gmkv** [comment] 2021-04-14 15:11
Hi @sfsf-xweb-sh 

You are setting width and height with very particular rem values which causes the dialog to render incorrectly at high zoom levels. At 1280x800 with 200% zoom, those values end up being bigger than the viewport.

![image](https://user-images.githubusercontent.com/22086365/114733547-1cba9f80-9d4c-11eb-93cf-85f408c74458.png)
I don't think this is a bug with ui5-dialog, therefore I will close the issue.

**Closed by gmkv** 2021-04-14 15:11 UTC
Labels: SF, author action
