### ISSUE TITLE
[ViewSettingsDialog] The group header is overlapped

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#5650] opened 2022-08-09 23:44 UTC
### **Bug Description**
The group header is overlapped. See the screenshots.
![image](https://user-images.githubusercontent.com/1995447/183780243-908511c5-832c-4be9-858c-a1d5017c9163.png)
![image](https://user-images.githubusercontent.com/1995447/183780264-9c1b85b0-643b-4284-9827-a93b1320a298.png)

### **Steps to Reproduce**
It is reproducible in playground https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/

### **Context**
- UI5 Web Components version: {1.6.0}
- OS/Platform: {MacOS}
- Browser: {Chrome}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by rchrdchn** [comment] 2022-08-17 17:43
Hi team - are there any updates on this issue? It seems high priority as it's highly visible on the interface side.

Thanks!

**Comment by jatinthaker** [comment] 2022-08-23 21:11
@kskondov when is this going to be picked up. This is in one of our high visibility interfaces that is making waves soon. Can we please expedite the fix or give us a workaround. You can reach out to any of the SF team members for questions.

**Comment by ilhan007** [comment] 2022-08-24 06:20
Hello @SAP/ui5-webcomponents-topic-b is it possible to pick this up sooner

Thank you,
ilhan

**Comment by ilhan007** [comment] 2022-08-26 06:46
The issue is resolved by this PR https://github.com/SAP/ui5-webcomponents/pull/5726

**Closed by ilhan007** 2022-08-26 06:46 UTC
Labels: bug, High Prio, TOPIC B, SF
