### ISSUE TITLE
[SF][A11y][Button]Button unavailable read twice in virtual PC mode

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#5703] opened 2022-08-23 08:06 UTC
**Describe the bug**
Hi team
For the iconOnly `Button`, when the buttons is disabled and has an `accessibleName` attribute, the "button unavailable" would read twice in JAWS 2022 VPC mode

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-button--default-story
2. Set `accessibleName=submit` `disabled=true` `icon=employee` and empty `children` attribute to `Button` component
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/27538066/186103889-c955beea-fe03-4443-b3b0-19db595c2ea9.png">

3. Enter VPC mode, use arrow down to read the button
4. See the button was announced twice
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/27538066/186104406-8158d820-544a-46d0-9945-6018e439a22d.png">

5. looks like the `accessibleRole=img` attribute of icon inside the button caused this issue. If we set the `accessibleRole` of internal `ui5-icon` to `presentation`, then the button announcement works fine in VPC mode.
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/27538066/186105890-bb0fc8a2-33c3-4ce6-924d-2c3658e5c4ac.png">

**Expected behavior**
The disabled iconOnly button should read once in VPC mode

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.3
Operating System: Windows
Browser: Chrome

**Comment by ndeshev** [comment] 2022-08-31 04:50
Related to: https://github.com/SAP/ui5-webcomponents/issues/5687; https://github.com/SAP/ui5-webcomponents/issues/5733 https://github.com/SAP/ui5-webcomponents/issues/5596 https://github.com/SAP/ui5-webcomponents/issues/5505 https://github.com/SAP/ui5-webcomponents/issues/5733

Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-b this seems to be an issue that  is currently being processed because of another reported problems, could you please close it when its done and notify the reporter.

**Comment by ee92** [comment] 2022-09-15 16:52
This issue also affects the ui5-rating-indicator component. Can you please check if the fix for this issue will also fix the ui5-rating-indicator? If not I can create a separate ticket for it. Thanks!

**Comment by unazko** [comment] 2022-10-11 06:57
Hello @ksblklu,

As you properly analysed the issue comes from the <code>img</code> role of the icon. That makes the screen reader cursor to stop first on the button and after that on the icon and causes those redundant announcements.

As per UX guidelines all icon-only button instances should have a tooltip.
Provide a tooltip for those ui5-button elements until the following component enhancement
https://github.com/SAP/ui5-webcomponents/issues/5733
is complete. This would make the inner icon decorative and the issue won't appear.

Best Regards,
Boyan Rakilovski

**Comment by ilhan007** [comment] 2022-11-24 08:30
Hello @SAP/ui5-webcomponents-topic-b, @unazko the author added new details to the issue, could you check?

Thank you

**Comment by unazko** [comment] 2022-12-16 10:05
Hi @ksblklu,

Apologies for the late response.
I wasn't able to reproduce this issue with the third disabled button with "Submit" text from the snipped:  https://codesandbox.io/s/charming-sara-w1oxs6?file=/src/App.js
Tried with JAWS 2022, 2021 on Chrome browser, windows machine.
Which browser and operation system you've used?

Best Regards,
Boyan

**Comment by ksblklu** [comment] 2023-01-31 07:08
Hi @unazko 
In https://codesandbox.io/s/charming-sara-w1oxs6?file=/src/App.js I can still reproduce this issue in Windows11, Chrome browser with JAWS 2022.2205.25. under VirtuaPC mode. I didn't add`tabindex` attribute to any of those buttons in CodeSandbox Example, so I think we should keep the buttons as it is.
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/27538066/215690386-d0cd5dda-0b0f-4a6a-b7b2-c556c8af1065.png">

**Comment by NHristov-sap** [comment] 2023-02-21 15:43
Hi @ksblklu,

The reported issue in fact is a JAWS issue, and it is already included in known JAWS issues for UI5 Classic (but here in WebComponents the situation is the same). You can check this JSBin, where the issue is reproducible with pure HTML:

[https://jsbin.com/dacididuxu/edit?html,output](https://jsbin.com/dacididuxu/edit?html,output)

That's why I am closing this issue.
Best Regards,
Nikolay Hristov

**Closed by NHristov-sap** 2023-02-21 15:43 UTC
Labels: bug, information required, High Prio, TOPIC B, SF, SF_ACC
