### ISSUE TITLE
[ui5-panel] Component Keyboard issue in windows chrome

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1814] opened 2020-06-16 09:22 UTC
**Describe the bug**

when i use [ui5-panel] Component in project. it's a simple case. i tab focus to the [ui5-panel] Component and then press 'Enter' key, the except behavior is the panel is collapsable, but the result is focus into inner button.

**Isolated example**
https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list?templateType=tgm&templateId=22

**Expected behavior**
In windows chrome the except behavior is the panel is collapsable

**Screenshots**
step1: i tab focus to the panel

<img width="1605" alt="1" src="https://user-images.githubusercontent.com/4457451/84751284-f7a3b600-afee-11ea-9d31-29ed3588e767.png">

step2: i press the enter key

<img width="1610" alt="2" src="https://user-images.githubusercontent.com/4457451/84751298-fa9ea680-afee-11ea-9aac-675c143029b1.png">

here is code.

![image](https://user-images.githubusercontent.com/4457451/84757137-57518f80-aff6-11ea-8810-9816d215618a.png)

**Context**
- UI5 Web Components version: Current version 1.0.0-rc.7
- OS/Platform: win10
- Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by fifoosid** [comment] 2020-06-16 11:32
Hello @alex-gilin 

I am not able to reproduce the issue in your system on my side. After focus is applyed to the Panel, on pressing Enter the panel is expanding/collapsing. I am attaching a video. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16850339/84769010-e0a89800-afdd-11ea-96cd-14b027fd8a31.gif)

Chrome Version: 83.0.4103.106 (Official Build), (64-bit) (the same)

**Comment by alex-zhang** [comment] 2020-06-17 07:02
@fifoosid  thanks for ur reply. it maybe a strange issue with my environment and i will make more tests for others  environment later.

**Comment by fifoosid** [comment] 2020-06-17 09:19
Okay. If you don't experience the issue, feel free to close it.

**Closed** 2020-06-17 09:27 UTC
Labels: SuccessFactors
