### ISSUE TITLE
[SF][1.4.0][A11y][Breadcrumbs]: Breadcumbs navigation item is not adapting correctly to HC themes under Windows

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#5507] opened 2022-07-14 06:07 UTC
### **Bug Description**
The color of Breadcrumbs item is not adapting correctly to HC theme under Windows system

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Windows
- Browser:Chrome
- Affected component: Breadcrumbs

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by TeodorTaushanov** [comment] 2022-07-14 11:55
Hi @ksblklu, can you provide a link where the issue is reproducible and probably a screenshot?

**Comment by TeodorTaushanov** [comment] 2022-07-19 09:51
Hi @ksblklu, the issue seems to be fixed in version 1.5. Can you upgrade to 1.5? If not, we'll fix it in 1.4.

**Closed by TeodorTaushanov** 2022-07-19 09:51 UTC
Labels: bug
