### ISSUE TITLE
[BUG] List On Selection Change Issue

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#5891] opened 2022-10-05 23:44 UTC
### **Bug Description**
When using the `Enter` Key the action is done twice.
The reason is that when using the `Enter` key, then the dialog is opened but since the dialog focuses the `Close` button then the previous Enter key that was activated keeps going and is applied on the `Close` btn.

### **Expected Behavior**
Only one action should be used when using the `Enter` key. Works as expected when using the `Space` key

### **Steps to Reproduce**
1. Go to '[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-fo0uwu?file=/src/index.js)'
2. Using the Keyboard focus on a List Item
3. Use the `Enter` key, view as nothing happens
4. Use the `Space` key, then it works as expected and the dialog will open up

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-fo0uwu?file=/src/index.js).

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: CodeSandbox
- Browser: Chrome
- Affected component: List and Dialog

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: WEF

**Comment by gmkv** [comment] 2022-10-06 07:15
Hi @SAP/ui5-webcomponents-topic-rd 
This issue is similar to #4861.
Pressing the Enter key on a list item is set to open a Dialog. Then, the focus shifts to the close button inside the dialog and then the dialog is immediately closed.
Would you have a look?

**Comment by TeodorTaushanov** [comment] 2022-10-18 14:57
The issue is fixed in the main branch.

**Closed** 2022-10-18 14:57 UTC
Labels: bug, Medium Prio, TOPIC RD
