### ISSUE TITLE
The requested UI5 version is outdated and has been removed

### ISSUE THREAD

**Issue by dimalapeto** [SAP/ui5-webcomponents#5404] opened 2022-06-24 09:25 UTC
### **Bug Description**
The locale JSON file is requesting in [registerLocaleDataLoader function](https://github.com/SAP/ui5-webcomponents/blob/v1.3.1/packages/base/src/asset-registries/LocaleData.js#L150) but it is removed and unavailable now.
This bug affects DateTimePicker input!
Click on calendar icon to open date picker returns an error:
![Screenshot_13](https://user-images.githubusercontent.com/18643415/175504484-0243eb55-b809-4794-8051-ab0ca541e223.png)
![image (2)](https://user-images.githubusercontent.com/18643415/175504566-6af2d95d-364d-42f4-8a5e-f0b131f8fa32.png)
![image (3)](https://user-images.githubusercontent.com/18643415/175504622-3d40f066-a146-4553-8283-75c189985fbe.png)
JSON file is unavailable:
![image (4)](https://user-images.githubusercontent.com/18643415/175504733-d231544c-c566-4cd6-9ea9-fe5d7f8ca75e.png)

### **Expected Behavior**
Click on calendar icon to open date picker enables to select data.

### **Steps to Reproduce**
1. Go to ['SAP BTP Citymap'](https://obs-city-map.ulvbf.sites.dxp.k8s.ondemand.com/)
2. Select Time Range Type - Absolute
3. Try to select 'From' date

### **Isolated Example**
The same error in your isolated example -  [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)!

### **Context**
- UI5 Web Components version: {1.3.1}
- OS/Platform: {Windows 10}
- Browser: {Google Chrome Version 102.0.5005.115 (Official Build) (64-bit)}
- Affected component: {DateTimePicker}

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP BTP}
- Business impact: {...}

**Comment by tsanislavgatev** [comment] 2022-06-24 11:50
Hello @dimalapeto ,

The issue is fixed with the following commit and will be available with the next version.
https://github.com/SAP/ui5-webcomponents/commit/a4df0bdbb55782aaa436a2af164a486aa102ad8c

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2022-06-24 11:50 UTC

**Comment by dimalapeto** [comment] 2022-06-24 12:08
> Hello @dimalapeto ,
> 
> The issue is fixed with the following commit and will be available with the next version. [a4df0bd](https://github.com/SAP/ui5-webcomponents/commit/a4df0bdbb55782aaa436a2af164a486aa102ad8c)
> 
> Best Regards, Tsanislav

Hello @tsanislavgatev 
Thank you for information!
Can you tell me will it be available in next major or minor version?

**Comment by ilhan007** [comment] 2022-07-01 08:58
Hi @dimalapeto we will have few days delay, the release will take place early next week as we are executing final pre-release checks.
