### ISSUE TITLE
ui5-table: column headers remain left-aligned in RTL mode

### ISSUE THREAD

**Issue by ndeshev** [SAP/ui5-webcomponents#3835] opened 2021-09-05 05:20 UTC
`ui5-table-column` elements are left-aligned, while the `ui5-table-row` are correctly aligned to the right, causing obvious misalignment.

### **Expected Behavior**
Both should be aligned to the right in RTL mode.

https://sap.github.io/ui5-webcomponents/playground/components/Table/?sap-ui-theme=sap_fiori_3&isrtl=true

Reproducible on all browsers.

![table-rtl](https://user-images.githubusercontent.com/1590151/132116223-44bb33ab-f238-4a2f-bdc7-345e704aafb1.JPG)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment] 2021-12-10 10:47
Hello Colleagues,

We analysed the issue and it is reproducible only in the Playground. Even there, if applyDirection is called as described here: https://sap.github.io/ui5-webcomponents/master/playground/advanced/rtl-and-compact-mode/ the issue is not reproducible anymore. 
The Core team will check the Playground issue, but as there is no issue in the ui5-table component, I am closing the incident.

Kind Regards,
Niya

**Closed by niyap** 2021-12-10 10:47 UTC
Labels: Low Prio, TOPIC RL, 1.0 Release Testing
