### ISSUE TITLE
File Uploader field and button are not vertically aligned

### ISSUE THREAD

**Issue by ybesnehard** [SAP/ui5-webcomponents#7081] opened 2023-05-24 07:16 UTC
### Bug Description

Hi Developers,
We are using the FileUploader in our SAP Product and the FileUploader Field and Button are not vertically aligned
If you look at the playground it is the case : https://sap.github.io/ui5-webcomponents/playground/components/FileUploader/

### Affected Component

FileUploader

### Expected Behaviour

FileUploader Field and Button should be vertically aligned

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/FileUploader/

### Priority

None

### UI5 Web Components Version

1.13.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment] 2023-05-24 08:10
Hi @ybesnehard,

Thank you for reporting this bug. 

The issue is duplicated to #7055, so I will close this one and you can keep progress in the other issue.

Best regards,
Petya

**Closed by petyabegovska** 2023-05-24 08:10 UTC
Labels: bug, duplicate
