### ISSUE TITLE
Switch - Focus applied incorrectly

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6778] opened 2023-03-23 12:35 UTC
### Bug Description

The focus is not applied correctly in some of our resources. 

When we look at the Web Component Documentation there it is applied correctly as a outside border of the track.

When using the testsuite it is shown incorrectly as a rectangle around the switch.
Same for the Github Playground when it is opened in Safari. When it is opened in Chrome the focus is applied correctly.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Switch/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="427" alt="image" src="https://user-images.githubusercontent.com/6813930/227205240-e401220c-b021-44f7-ba03-62dd431b85b9.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment] 2023-03-23 14:29
Hello @SAP/ui5-webcomponents-topic-b,

The focus border of the Switch displays incorrectly as a box instead of the correct rounded shape. I was able to reproduce the issue as described on the playground page in SauceLabs with Safari 16 & MacOS 13, but it is not reproducible on Chrome & Windows as stated above.

Could you please take a look at this?

Best regards,
Siyana

**Comment by hinzzx** [comment] 2023-11-15 15:58
Hello,

The issue is fixed in the main branch.

BR,
Stoyan

**Closed by hinzzx** 2023-11-15 15:58 UTC
Labels: bug, Medium Prio, TOPIC B
