### ISSUE TITLE
[Safari/Firefox] will focus on header of ui5-card after clicking header's  button

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#2951] opened 2021-03-17 06:33 UTC
hi,

I am from SuccessFactors Web Experience Shanghai team. My name is hubery and this account is our team account

**Describe the bug**
We add a button as an action slot to ui5-card. If the user click the button then the header will get the focus.

**To reproduce**

1. open this [link](https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11001)
2. click the "Create Activity" button

**Except Behavior**
This behavior is correct in chrome browser. when the user click the action button in the card header, the header should not get the focus.

**Screenshots**
![image](https://user-images.githubusercontent.com/78520316/111424699-13c6b600-872d-11eb-8105-f39235dc6bdd.png)

**Context**
- UI5 Web Components version:SFSF version  0.29.7
- OS/Platform: macOS
- Browser *(if relevant)*:   Safari Version 14.0.2 (16610.3.7.1.9) and Firefox 85.0 
- Other information: {...}

**Affected components** *(if known)*
ui5-card

**Organization:** *(if applicable)*
SFSF

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

**Comment by ilhan007** [comment] 2021-03-17 09:26
Hello @SAP/ui5-webcomponents-topic-rd could you please see this issue, that happens in Safari and FF.

**Comment by gmkv** [comment] 2021-03-17 09:48
May help in resolving the issue: 
The bug only occurs when the "click" is on text in the button.
If instead, the icon in that button is clicked, the issue does not occur.

**Comment by sfsf-xweb-sh** [comment] 2021-03-31 07:08
hi, 

any updates of this ticket.

**Comment by gmkv** [comment] 2021-04-05 14:01
Hello @SAP/ui5-webcomponents-topic-b. I believe this is an issue with the button not receiving a focus on Firefox and Safari under macOS. Please refer to the following [codesandbox](https://codesandbox.io/s/ui5-webcomponents-forked-od07u?file=/index.html). Clicking on the icon within the button leaves the button focused, while clicking on the actual text in the button does not.

**Comment by tsanislavgatev** [comment] 2021-07-02 11:18
Hello colleagues,
There is a browser issue that in mozilla or safari on macOS, there are focus on the buttons, so no focusin or focus out will be fired. We're currently looking for a workaround solution.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus

**Comment by alex-zhang** [comment] 2021-08-08 16:52
@tsanislavgatev  thanks

**Comment by alex-zhang** [comment] 2021-11-02 10:47
hi, thanks for your reply.

yes, the new version is fine for these feature for keyboard. I test it in chrome, firefox , and safari.

But it cause a new issue, only in safari.  the chrome, firefox is fine.

The behavior is when the user click the `Add Learning` button then the Panel Header will get the focus.
Expect behavior: when the user click the `Add Learning` button then the Panel Header should not get the focus.

> both in the list item button.

![1](https://user-images.githubusercontent.com/4457451/139831063-9c02d5b0-4f4f-46dd-b38e-93223cedf22a.gif)

But it's strange that if the button has icon, and i click the icon part and the behavior is correct.

![2](https://user-images.githubusercontent.com/4457451/139831295-9f3c622e-b4bb-4820-9f69-0a4c5fb113a4.gif)

**Comment by ilhan007** [comment] 2021-11-10 15:53
Pending Release - Fri 12 Nov

**Comment by sfsf-xweb-sh** [comment] 2022-03-09 09:11
hi,  @ilhan007  can you please to open it again. I test in my local and it not fixed(for safari) with version 1.2.1.

**Comment by ilhan007** [comment] 2022-03-09 09:25
Hello @tsanislavgatev could you check the issue. According to the author it's still reproducible with the latest version.

**Comment by tsanislavgatev** [comment] 2022-03-11 12:35
Hello @sfsf-xweb-sh ,

The issue is not reproducible for me.
I've tested it in playground with latest version:
https://sap.github.io/ui5-webcomponents/

https://user-images.githubusercontent.com/11508737/157867734-bdac919e-d8a3-4e9c-ac0f-f271123f5d9d.mov

Can you please check it again?

Best Regards,
Tsanislav

**Comment by sfsf-xweb-sh** [comment] 2022-03-17 07:51
@tsanislavgatev  hi,  thanks for your reply.

The case is in the card's slot for only safari browser.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/78520316/158761931-bde6e02f-f6f3-4e6e-b4b5-993ac7003171.png">

**Comment by tsanislavgatev** [comment] 2022-03-24 07:24
Hello @sfsf-xweb-sh ,

https://user-images.githubusercontent.com/11508737/159863895-3b474de0-dd7d-4062-a2c7-daeec7c188f4.mov


My previous video was also in safari.
I am attaching a video also from safari and card test page:


Best Regards,
Tsanislav

**Comment by sfsf-xweb-sh** [comment] 2022-03-25 07:30
hi,  @tsanislavgatev 

thanks for you reply.

Please help check it again, It's work not work for me.

I'll give you my local env, below:

OS: MacOS Monterey Version 12.2.1(21D62)
Safari: Version 15.3 (17612.4.9.1.8)

![image](https://user-images.githubusercontent.com/78520316/160074699-7d5b983f-38fc-4caa-a749-a7af2107a489.png)

**Comment by tsanislavgatev** [comment] 2022-04-05 06:42
Hello @sfsf-xweb-sh,

This issue isn't reproducing after mouse up.

We've tested it on few more computers on latest versions of MacOS and Safari.

Can you please check if the focus is set on mouse up, as it's when the click is fired.

Best Regards,
Tsanislav

**Comment by sfsf-xweb-sh** [comment] 2022-07-26 13:54
hi, please help close this ticket and thanks for your updates and reply.

it's seems works with latest versions of MacOS and Safari.

**Closed** 2022-07-29 12:03 UTC
Labels: bug, Medium Prio, TOPIC B, SF, author action
