### ISSUE TITLE
MultiComboBox: inconsistency when using a a placeholder and programatically changing selected items

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4897] opened 2022-03-14 17:17 UTC
### **Bug Description**
When using a placeholder text in the MultiComboBox component and setting the selected state of one of the items to `"true"`, the placeholder doesn't show up and only if no item is initially selected, the placeholder is displayed. This is in my opinion the expected behavior.
When programatically changing the selected state of an item, the placeholder is displayed if an item is selected, and not if no item is selected.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/9749730/158224807-5b537e7f-cf9b-42de-9174-a8c996ee7a7b.png">

### **Expected Behavior**
If no item is selected, the placeholder should be displayed, otherwise not.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-f7udfu?file=/index.html)
2. Toggle both MultiComboBoxes by clicking on the button
3. See the described behavior.

### **Isolated Example**
[If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).](https://codesandbox.io/s/ui5-webcomponents-forked-f7udfu?file=/src/index.js)

### **Context**
- UI5 Web Components version: 1.2.1

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### Additional informations

Originally raised in Slack: https://openui5.slack.com/archives/CSQEJ2J04/p1647038257463879?thread_ts=1646935282.760829&cid=CSQEJ2J04

**Comment by ndeshev** [comment] 2022-03-15 06:52
Hello @Lukas742, 

Thanks for reporting, I reproduced the issue and I'm assigning it to the dev team.

Colleagues, the issue is caused because the placeholder getter in the Multi ComboBox component ` get _getPlaceholder() ` is checking for tokens to determine whether or not to show placeholder, but by the time it is called by the re-rendering cycle after a programmatic change, the tokenizer is not yet created any.

**Closed** 2022-03-23 15:05 UTC
Labels: bug, Medium Prio, TOPIC RL
