### ISSUE TITLE
clicking on 'show more' link in NotificationListItem should not change the location to #. the text should also be translated

### ISSUE THREAD

**Issue by f-zou** [SAP/ui5-webcomponents#2778] opened 2021-02-04 10:53 UTC
**Describe the bug**
when the content in ui5-li-notification is too long, there is a 'show-more' link in content footer. By clicking on the link the location changes to '#'. this should not happen.  
Besides the 'show more' text should be translated according to the locale. 

**To reproduce**
1. Go to  https://components.furo.pro/?t=demo-FuroUi5NotificationListDisplay-0
2. click the 'Generate GRPC ERROR' button
3. click the "show more" link
4. you will see that the url location is changed to '#' 

**Screenshots**

![Bildschirmfoto 2021-02-04 um 11 43 04](https://user-images.githubusercontent.com/3601358/106882886-8e88c400-66df-11eb-8b75-9c997f3dea9f.png)

**Comment by ilhan007** [comment] 2021-02-04 11:29
Hello f-zou, thanks for reporting.

For the "#" we prepared a fix - https://github.com/SAP/ui5-webcomponents/pull/2779

For the showMore i18n - the text is translated on our side , for example, here it is in German and Italian:
<img width="664" alt="Screenshot 2021-02-04 at 1 29 08 PM" src="https://user-images.githubusercontent.com/15702139/106886826-04dff300-66ed-11eb-9a66-8dfbd06ae714.png">

<img width="732" alt="Screenshot 2021-02-04 at 1 25 54 PM" src="https://user-images.githubusercontent.com/15702139/106886795-fa255e00-66ec-11eb-8ecf-0ca21bc03247.png">

**Comment by f-zou** [comment] 2021-02-08 13:11
Thank you iIhan007!

**Comment by f-zou** [comment] 2021-04-08 06:36
hallo iIhan007

when will be this fix released ?

best regards
fan

**Comment by ilhan007** [comment] 2021-04-08 06:42
Hi @f-zou the fix was not good enough to be merged. It resolves the issue that you filed by removing the "href",
but I realised that without "href" pressing on ENTER stops working. We will iterate over the issue.

Really sorry for the delay!

**Comment by ilhan007** [comment] 2021-04-08 06:56
Hi @f-zou there seems to be  a problem with your app. When I navigate to https://components.furo.pro/?t=demo-FuroUi5NotificationListDisplay-0 I can't see the 'Generate GRPC ERROR' button any more.

**Comment by f-zou** [comment] 2021-04-08 12:55
Hi @ilhan007 
i have checked the site. the button is there. could you please refresh the site?
<img width="817" alt="Bildschirmfoto 2021-04-08 um 14 54 55" src="https://user-images.githubusercontent.com/3601358/114030023-6aca3180-987a-11eb-97a1-4f7bc70672ea.png">

**Comment by ilhan007** [comment] 2021-04-08 13:45
> Hi @ilhan007
> i have checked the site. the button is there. could you please refresh the site?
> <img alt="Bildschirmfoto 2021-04-08 um 14 54 55" width="817" src="https://user-images.githubusercontent.com/3601358/114030023-6aca3180-987a-11eb-97a1-4f7bc70672ea.png">

It's fine now, thanks

**Comment by ilhan007** [comment] 2021-04-08 13:49
Hello @SAP/ui5-webcomponents-topic-rd could help with the following issue.

**Issue**
Clicking the "showMore" of NotificationListItem causes browser location change.

**Root cause**
It is due to the fact that internally ui5-link with href="#" is rendered.

If we remove the "href", the issue will be resolved, bu then pressing ENTER over the "showMore" stops working.
So, we should come up with another solution.

**Steps**
Go to https://components.furo.pro/?t=demo-FuroUi5NotificationListDisplay-0
click the 'Generate GRPC ERROR' button
click the "show more" link
you will see that the url location is changed to '#'




BR,
ilhan

**Comment by gmkv** [comment] 2021-04-08 15:22
Hi @f-zou 
The issue seems to occur only in this app you provided.
Please check out this [minimal example](https://codesandbox.io/s/ui5-webcomponents-forked-j3evv?file=/index.html), where you can see that clicking on "Show more" will not change the URL of the page.
In that example, you can see all the event listeners for the click event on the "Show more" element:
![image](https://user-images.githubusercontent.com/22086365/114052707-f18d0780-9896-11eb-93d4-c8a100cd86db.png)

In the provided app, there are more listeners on that element. To me, it looks like one of those listeners is changing the URL - perhaps it's worth investigating in that direction.
![image](https://user-images.githubusercontent.com/22086365/114053040-3fa20b00-9897-11eb-8a21-0a69a9373cc1.png)

I don't see this issue being related to ui5-webcomponents, therefore I will close it.

**Closed by gmkv** 2021-04-08 15:22 UTC
Labels: Medium Prio, TOPIC RD, bug
