### ISSUE TITLE
Accessibility issue combobox

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5445] opened 2022-07-01 10:53 UTC
**Describe the bug**
Options not read out correctly when focussing.

**Isolated Example**
[CodeSandbox](https://codesandbox.io/s/ancient-fast-z5oszx?file=/src/App.js)

**To Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/ancient-fast-z5oszx?file=/src/App.js)
2. Open list of options in the combo box
3. Cycle through the options using UP and DOWN keys.

**Expected behavior**
Options should be read out like Entry 1 Text 1, Entry 2 Text 2..

**Screenshots**
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/93638146/176880802-5957de66-8611-4670-a72e-deb9ede2cc45.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` 1.4.0:
`@ui5/webcomponents-react` 0.25.6:
Operating System: Mac OS
Browser: Chrome

**Comment by elenastoyanovaa** [comment] 2022-07-26 13:01
Accessibility expert analysis:

The issue is reproducible in the playground samples as well.

Currently  we use the invisible messaging to announce the selected item. We call the announceSelectedItem in the combobox. For some reason (I think that this lead to double announcement) we do not include the item text nor the subtext in the announcement, which is incorrect. IMO we should include them as well, but we should test carefully before submitting anything. Some related PR:

https://github.com/SAP/ui5-webcomponents/pull/3358/files
https://github.com/SAP/ui5-webcomponents/pull/5478/files

**Comment by niyap** [comment] 2022-10-19 05:32
Hello @Bilal3120,

The issue about not announcing the additional text of an item is fixed with the following change: https://github.com/SAP/ui5-webcomponents/pull/5943
On the other hand, the issue about not always announcing the value of the combobox is a known screen reader issue and we do not have influence over it.
Here is an isolated example with native HTML elements where the issue is also reproducible: https://jsbin.com/buzakereye/edit?html,output.

Kind Regards,
Niya

**Closed by niyap** 2022-10-19 05:32 UTC
Labels: bug, ACC, TOPIC RL

**Comment by DikshaHub** [comment] 2024-07-02 04:48
Hi @niyap,

You mentioned that the issue with not announcing the additional text of an item was fixed in #5943. Could you please let me know which version this change was released in?

Thank you!

**Comment by DikshaHub** [comment] 2024-07-02 09:08
Thanks @nnaydenow
