### ISSUE TITLE
MultiComboBox & MultiInput: Inconsistent Keyboard Event Behavior in Regard to Tokens

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents#3406] opened 2021-06-07 11:11 UTC
### **Bug Description**
MultiComboBox & MultiInput behave differently when it comes to keyboard navigation of `Token`s.

MultiComboBox:
* input focussed & input has no value: backspace / arrow left will select the last token
* token focussed: arrow left / right will select prev / next token
  * last token focussed: arrow right focuses input

MultiInput:
* input focussed & input has no value: backspace / arrow left / arrow right don't change focus
* token focussed: same beahavior as MultiComboBox

Bug for MultiInput & MultiComboBox: 
*  penultimate token focussed => arrow right directly focusses input instead of last token

Inconsistencies of this behavior / Proposal for more consistency: Having the following two behaviors additionally would allow to cycle through all tokens and the input endlessly, i.e. tokens & input are treated as on the same level:
  * proposal: input focussed & input has no value: arrow right should select first token
  * proposal: first token focussed & arrow left: input focussed

### **Expected Behavior**
Consistent keyboard navigation for MultiComboBox & MultiInput

### **Steps to Reproduce**
Use the playground with prefilled tokens to reproduce described behavior.

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: Windows 
- Browser: FF & Chrome
- Affected component: MultiComboBox & MultiInput

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by elenastoyanovaa** [comment] 2021-06-07 11:40
Hello @texttechne ,

Thank you for the proposal. Our components follow the Fiori Guidelines and the existing Keyboard Interaction Specification for SAPUI5. As you can check the same example for SAPUI5 for the MultiComboBox https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox the behavior you described for the ui5-multicombobox is desired, not a bug. 

The bug you reported regarding the skipping of the rightmost token is known to us as well as the issue you described for the ui5-multiinput (one cannot access the tokens via keyboard). They will be fixed as part of https://github.com/SAP/ui5-webcomponents/issues/3090 Additionally all supported keyboard combinations will be described in the playground also as part of issue #3090 . 

Kind Regards,
Elens

**Closed by elenastoyanovaa** 2021-06-07 11:40 UTC
Labels: TOPIC RL, duplicate
