### ISSUE TITLE
[Input]:  'unselected' is announced when the suggestion item is selected

### ISSUE THREAD

**Issue by AlexYanSap** [SAP/ui5-webcomponents#9314] opened 2024-06-27 06:55 UTC
### Describe the bug

When using Input with suggestion items. 'unselected' will be announced when the suggestion item is selected. It's not expected and we (SFSF) have received the reports from the customers.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--docs#more-examples

### Reproduction steps

1. open screen reader
2. type 'a' in the input
3. select any selectable suggestion item
4. 'unselected' will be announced 

### Expected Behaviour

when an item e.g., 'ABC' is selected, 'ABC is selected' should be announced.

### UI5 Web Components for React Version

1.29.2

### UI5 Web Components Version

2.0.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by AlexYanSap** [comment] 2024-06-28 01:38
Hi @kineticjs, 
I used NVDA as the SR, and its version is 2024.1.
Edge version is 123.0.2420.81 (Official build) (64-bit)

**Comment by GerganaKremenska** [comment] 2024-07-08 11:46
Hello @AlexYanSap,

I have tested with JAWS 2024 + Chrome(our testing enviourment) and the issue is not reproducible.
Please reffer to video: 

https://github.com/SAP/ui5-webcomponents/assets/22882174/bdca3e5f-4300-4914-81a3-332a594fb2dc


UI5 Web Components provide the prerequisites for screen reader support based on the HTML, ARIA, and WCAG standards. All screen readers that follow those standards should work fine. Nevertheless, there are deviations in the interpretation depending on the combination of browser and screen reader. UI5 Web Components focus on compliance with the standards, rely on automated checks for accessibility and manual tests with reference testing environments. 

For Screen Reader Support, we recommend using JAWS 2021 + Chrome (latest), and for HTML/ARIA validation the recommended testing tool is [Access Assistant](https://chrome.google.com/webstore/detail/access-assistant/ojiighldhdmahfdnhfdebnpmlbiemdfm). UI5 Web Components support other environments to the extent of providing a valid HTML and ARIA implementation following the WCAG standards.

Please note that reference testing environments may change over time to reflect changes in the usage of different browsers, their maintenance period, and increased accessibility compliance.

When reporting issues with different testing environments, please ensure that the issue is not false positive, a real accessibility concern is present and there is an impact over the users. Therefore, we recommend to retest the issue using the mentioned reference testing tools and additionally with plain HTML.

This seems as a false positive therefor i am closing the issue.

Best Regards,
Gergana

**Closed by GerganaKremenska** 2024-07-08 11:46 UTC
Labels: bug, SAP SF
