### ISSUE TITLE
Timeline Item visual issue on compact density

### ISSUE THREAD

**Issue by guedes4g** [SAP/ui5-webcomponents#4252] opened 2021-11-03 12:59 UTC
### **Bug Description**
Timeline visual bug on Timeline item :before pseudo element when using compact UI

![image](https://user-images.githubusercontent.com/29311988/140060640-307788e1-58c6-46f7-a934-d9feaae8e2fc.png)

--- 
![image](https://user-images.githubusercontent.com/29311988/140064200-fada0405-1021-4f0d-8302-77acb949bdcd.png)

### **Expected Behavior**
Line to not overlap the icon

### **Steps to Reproduce**
1. Use timeline with compact density

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: Mac
- Browser: Chrome 94.0.4606.114 (Platform version: 14150.74.0)
- Affected component: Timeline

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)
- Organization: SAP - PE - LX Labs
- Business impact: Low

**Comment by gabrielkurtz** [comment] 2021-11-03 13:06
Hi! This is also happening when manually setting the margin sizes between Timeline Items

**Comment by LidiyaGeorgieva** [comment] 2021-11-03 14:05
Hello @SAP/ui5-webcomponents-topic-b,

You can test this issue here: https://sap.github.io/ui5-webcomponents/playground/components/Timeline/?sap-ui-theme=sap_fiori_3&isrtl=false

Best Regards,
Lidiya

**Comment by tsanislavgatev** [comment] 2021-11-04 09:48
Hello,

The issue is fixed in the master branch and it's no longer reproducible.
The master branch can be checked here: https://sap.github.io/ui5-webcomponents/master/playground/components/Timeline/?sap-ui-theme=sap_fiori_3&isrtl=false

Best Regards,
Tsanislav

**Closed by tsanislavgatev** 2021-11-04 09:48 UTC
Labels: bug, Low Prio, TOPIC B
